### ISSUE TITLE
'gcloud-python' install pulls in Sphinx and its many dependencies

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#1995]
Which is Just Wrong(TM).

**Comment by dhermes** [comment]
Ew. How?

**Comment by tseaver** [comment]
Just saw it while installing into a fresh virtualenv, using `easy_install` to test #1972.  It looks like it *downloads* Sphinx et aliae, but doesn't actually install them.

**Comment by daspecster** [comment]
I get this on a fresh venv after `pip install gcloud`
```bash
╰─$ pip freeze
enum34==1.1.6
futures==3.0.5
gax-google-logging-v2==0.7.12
gax-google-pubsub-v1==0.7.12
gcloud==0.17.0
google-gax==0.12.3
googleapis-common-protos==1.2.0
grpc-google-logging-v2==0.7.12
grpc-google-pubsub-v1==0.7.12
grpcio==0.15.0
httplib2==0.9.2
oauth2client==2.2.0
ply==3.8
protobuf==3.0.0b3
pyasn1==0.1.9
pyasn1-modules==0.0.8
rsa==3.4.2
six==1.10.0
```

**Comment by tseaver** [comment]
```bash
$ /opt/Python-2.7.11/bin/virtualenv /tmp/issue-1972
New python executable in /tmp/issue-1972/bin/python
Installing setuptools, pip, wheel...done.
$ /tmp/issue-1972/bin/easy_install gcloud-python
Processing gcloud-python
Writing /home/tseaver/projects/agendaless/Google/src/gcloud-python/setup.cfg
Running setup.py -q bdist_egg --dist-dir /home/tseaver/projects/agendaless/Google/src/gcloud-python/egg-dist-tmp-YQMxOd
creating /tmp/issue-1972/lib/python2.7/site-packages/gcloud-0.17.0-py2.7.egg
Extracting gcloud-0.17.0-py2.7.egg to /tmp/issue-1972/lib/python2.7/site-packages
Adding gcloud 0.17.0 to easy-install.pth file

Installed /tmp/issue-1972/lib/python2.7/site-packages/gcloud-0.17.0-py2.7.egg
Processing dependencies for gcloud==0.17.0
Searching for gax-google-logging-v2>=0.7.10
Reading https://pypi.python.org/simple/gax-google-logging-v2/
Best match: gax-google-logging-v2 0.7.12
Downloading https://pypi.python.org/packages/31/37/b3748a60c54eca1f4c3448c7cb953dc2eedc6ab6365d4c85f609abac052e/gax-google-logging-v2-0.7.12.tar.gz#md5=3913450988ff858afa8409d472e430c1
Processing gax-google-logging-v2-0.7.12.tar.gz
Writing /tmp/easy_install-zEZthE/gax-google-logging-v2-0.7.12/setup.cfg
Running gax-google-logging-v2-0.7.12/setup.py -q bdist_egg --dist-dir /tmp/easy_install-zEZthE/gax-google-logging-v2-0.7.12/egg-dist-tmp-Hd8ahx
no previously-included directories found matching '.tox'
zip_safe flag not set; analyzing archive contents...
Moving gax_google_logging_v2-0.7.12-py2.7.egg to /tmp/issue-1972/lib/python2.7/site-packages
Adding gax-google-logging-v2 0.7.12 to easy-install.pth file

Installed /tmp/issue-1972/lib/python2.7/site-packages/gax_google_logging_v2-0.7.12-py2.7.egg
Searching for gax-google-pubsub-v1>=0.7.10
Reading https://pypi.python.org/simple/gax-google-pubsub-v1/
Best match: gax-google-pubsub-v1 0.7.12
Downloading https://pypi.python.org/packages/96/b5/8562f2ecdba9883341f9f69e9d66a0e620b5445dcaf0a87ebf314c4d09fb/gax-google-pubsub-v1-0.7.12.tar.gz#md5=1a08377ebbb5e03d6264805e6a50cc25
Processing gax-google-pubsub-v1-0.7.12.tar.gz
Writing /tmp/easy_install-65VV3A/gax-google-pubsub-v1-0.7.12/setup.cfg
Running gax-google-pubsub-v1-0.7.12/setup.py -q bdist_egg --dist-dir /tmp/easy_install-65VV3A/gax-google-pubsub-v1-0.7.12/egg-dist-tmp-WtUcqN
no previously-included directories found matching '.tox'
zip_safe flag not set; analyzing archive contents...
Moving gax_google_pubsub_v1-0.7.12-py2.7.egg to /tmp/issue-1972/lib/python2.7/site-packages
Adding gax-google-pubsub-v1 0.7.12 to easy-install.pth file

Installed /tmp/issue-1972/lib/python2.7/site-packages/gax_google_pubsub_v1-0.7.12-py2.7.egg
Searching for google-gax>=0.12.1
Reading https://pypi.python.org/simple/google-gax/
Best match: google-gax 0.12.3
Downloading https://pypi.python.org/packages/25/64/ecec8bf3dd43c91669a69bea378e0684c891405750db4c105bdc42f29cf7/google-gax-0.12.3.tar.gz#md5=49b2bf7d3b5cc0e75648d17ac03ff04e
Processing google-gax-0.12.3.tar.gz
Writing /tmp/easy_install-VUexVh/google-gax-0.12.3/setup.cfg
Running google-gax-0.12.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-VUexVh/google-gax-0.12.3/egg-dist-tmp-JzFVLP
zip_safe flag not set; analyzing archive contents...
Moving google_gax-0.12.3-py2.7.egg to /tmp/issue-1972/lib/python2.7/site-packages
Adding google-gax 0.12.3 to easy-install.pth file

Installed /tmp/issue-1972/lib/python2.7/site-packages/google_gax-0.12.3-py2.7.egg
Searching for grpcio>=0.14.0
Reading https://pypi.python.org/simple/grpcio/
Best match: grpcio 0.15.0
Downloading https://pypi.python.org/packages/d1/d7/9bf18818763e0f7debe6706705f61ce89aa5636d93083776a6167320d573/grpcio-0.15.0.tar.gz#md5=ca43a6b84a67ccdd7dd96eafb67fc0eb
Processing grpcio-0.15.0.tar.gz
Writing /tmp/easy_install-W3hcQ0/grpcio-0.15.0/setup.cfg
Running grpcio-0.15.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-W3hcQ0/grpcio-0.15.0/egg-dist-tmp-OMX6VY

Installed /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/protobuf-3.0.0b3-py2.7.egg
Searching for futures>=2.2.0
Reading https://pypi.python.org/simple/futures/
Best match: futures 3.0.5
Downloading https://pypi.python.org/packages/55/db/97c1ca37edab586a1ae03d6892b6633d8eaa23b23ac40c7e5bbc55423c78/futures-3.0.5.tar.gz#md5=ced2c365e518242512d7a398b515ff95
Processing futures-3.0.5.tar.gz
Writing /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-pzHRBh/futures-3.0.5/setup.cfg
Running futures-3.0.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-pzHRBh/futures-3.0.5/egg-dist-tmp-fxqyar
creating /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/futures-3.0.5-py2.7.egg
Extracting futures-3.0.5-py2.7.egg to /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs

Installed /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/futures-3.0.5-py2.7.egg
Searching for enum34>=1.0.4
Reading https://pypi.python.org/simple/enum34/
Best match: enum34 1.1.6
Downloading https://pypi.python.org/packages/e8/26/a6101edcf724453845c850281b96b89a10dac6bd98edebc82634fccce6a5/enum34-1.1.6.zip#md5=61ad7871532d4ce2d77fac2579237a9e
Processing enum34-1.1.6.zip
Writing /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-UHg51s/enum34-1.1.6/setup.cfg
Running enum34-1.1.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-UHg51s/enum34-1.1.6/egg-dist-tmp-TEVwMx
zip_safe flag not set; analyzing archive contents...
Moving enum34-1.1.6-py2.7.egg to /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs

Installed /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/enum34-1.1.6-py2.7.egg
Searching for six>=1.10
Reading https://pypi.python.org/simple/six/
Best match: six 1.10.0
Downloading https://pypi.python.org/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55
Processing six-1.10.0.tar.gz
Writing /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-HI_GJ1/six-1.10.0/setup.cfg
Running six-1.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-HI_GJ1/six-1.10.0/egg-dist-tmp-BO0_fb
no previously-included directories found matching 'documentation/_build'
zip_safe flag not set; analyzing archive contents...
six: module references __path__
creating /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/six-1.10.0-py2.7.egg
Extracting six-1.10.0-py2.7.egg to /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs

Installed /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/six-1.10.0-py2.7.egg
Searching for sphinx_rtd_theme>=0.1.8
Reading https://pypi.python.org/simple/sphinx_rtd_theme/
Best match: sphinx-rtd-theme 0.1.10a0
Downloading https://pypi.python.org/packages/da/6b/1b75f13d8aa3333f19c6cdf1f0bc9f52ea739cae464fbee050307c121857/sphinx_rtd_theme-0.1.10a0.tar.gz#md5=83bd95cae55aa8b773a8cc3a41094282
Processing sphinx_rtd_theme-0.1.10a0.tar.gz
Writing /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-RdZMG2/sphinx_rtd_theme-0.1.10a0/setup.cfg
Running sphinx_rtd_theme-0.1.10a0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-RdZMG2/sphinx_rtd_theme-0.1.10a0/egg-dist-tmp-hrhDX_
/tmp/issue-1972/lib/python2.7/site-packages/setuptools/dist.py:295: UserWarning: Normalizing '0.1.10-alpha' to '0.1.10a0'
  normalized_version,
creating /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/sphinx_rtd_theme-0.1.10a0-py2.7.egg
Extracting sphinx_rtd_theme-0.1.10a0-py2.7.egg to /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs

Installed /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/sphinx_rtd_theme-0.1.10a0-py2.7.egg
Searching for sphinx>=1.3
Reading https://pypi.python.org/simple/sphinx/
Best match: Sphinx 1.4.5
Downloading https://pypi.python.org/packages/8b/78/eeea2b837f911cdc301f5f05163f9729a2381cadd03ccf35b25afe816c90/Sphinx-1.4.5.tar.gz#md5=5c2cd2dac45dfa6123d067e32a89e89a
Processing Sphinx-1.4.5.tar.gz
Writing /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-hIhqyX/Sphinx-1.4.5/setup.cfg
Running Sphinx-1.4.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-hIhqyX/Sphinx-1.4.5/egg-dist-tmp-pP6ecW
warning: no files found matching 'TODO'
warning: no files found matching 'ez_setup.py'
no previously-included directories found matching 'doc/_build'
creating /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/Sphinx-1.4.5-py2.7.egg
Extracting Sphinx-1.4.5-py2.7.egg to /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs

Installed /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/Sphinx-1.4.5-py2.7.egg
Searching for imagesize
Reading https://pypi.python.org/simple/imagesize/
Best match: imagesize 0.7.1
Downloading https://pypi.python.org/packages/53/72/6c6f1e787d9cab2cc733cf042f125abec07209a58308831c9f292504e826/imagesize-0.7.1.tar.gz#md5=976148283286a6ba5f69b0f81aef8052
Processing imagesize-0.7.1.tar.gz
Writing /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-VS3n3J/imagesize-0.7.1/setup.cfg
Running imagesize-0.7.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-VS3n3J/imagesize-0.7.1/egg-dist-tmp-7xJgCX
zip_safe flag not set; analyzing archive contents...
Moving imagesize-0.7.1-py2.7.egg to /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs

Installed /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/imagesize-0.7.1-py2.7.egg
Searching for alabaster<0.8,>=0.7
Reading https://pypi.python.org/simple/alabaster/
Best match: alabaster 0.7.8
Downloading https://pypi.python.org/packages/46/01/3539c406b47b0e44464a2b6c7b51871300d815b9d7b07c98309c9270bd50/alabaster-0.7.8.tar.gz#md5=346a71e8a6d51dff2e02086fdd9c5ffe
Processing alabaster-0.7.8.tar.gz
Writing /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-XokL5j/alabaster-0.7.8/setup.cfg
Running alabaster-0.7.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-XokL5j/alabaster-0.7.8/egg-dist-tmp-ts_Ul5
warning: no files found matching 'README.md'
warning: no previously-included files matching '.*.swp' found under directory 'alabaster'
zip_safe flag not set; analyzing archive contents...
alabaster.__init__: module references __file__
creating /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/alabaster-0.7.8-py2.7.egg
Extracting alabaster-0.7.8-py2.7.egg to /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs

Installed /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/alabaster-0.7.8-py2.7.egg
Searching for babel!=2.0,>=1.3
Reading https://pypi.python.org/simple/babel/
Best match: Babel 2.3.4
Downloading https://pypi.python.org/packages/6e/96/ba2a2462ed25ca0e651fb7b66e7080f5315f91425a07ea5b34d7c870c114/Babel-2.3.4.tar.gz#md5=afa20bc55b0e991833030129ad498f35
Processing Babel-2.3.4.tar.gz
Writing /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-hUX0ki/Babel-2.3.4/setup.cfg
Running Babel-2.3.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-hUX0ki/Babel-2.3.4/egg-dist-tmp-ICVG46
warning: no previously-included files matching '*' found under directory 'docs/_build'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyo' found under directory 'tests'
creating /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/Babel-2.3.4-py2.7.egg
Extracting Babel-2.3.4-py2.7.egg to /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs

Installed /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/Babel-2.3.4-py2.7.egg
Searching for snowballstemmer>=1.1
Reading https://pypi.python.org/simple/snowballstemmer/
Best match: snowballstemmer 1.2.1
Downloading https://pypi.python.org/packages/20/6b/d2a7cb176d4d664d94a6debf52cd8dbae1f7203c8e42426daa077051d59c/snowballstemmer-1.2.1.tar.gz#md5=643b019667a708a922172e33a99bf2fa
Processing snowballstemmer-1.2.1.tar.gz
Writing /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-vHQi08/snowballstemmer-1.2.1/setup.cfg
Running snowballstemmer-1.2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-vHQi08/snowballstemmer-1.2.1/egg-dist-tmp-LoUuG5
warning: no files found matching '*.py' under directory 'src'
zip_safe flag not set; analyzing archive contents...
Moving snowballstemmer-1.2.1-py2.7.egg to /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs

Installed /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/snowballstemmer-1.2.1-py2.7.egg
Searching for docutils>=0.11
Reading https://pypi.python.org/simple/docutils/
Best match: docutils 0.12
Downloading https://pypi.python.org/packages/37/38/ceda70135b9144d84884ae2fc5886c6baac4edea39550f28bcd144c1234d/docutils-0.12.tar.gz#md5=4622263b62c5c771c03502afa3157768
Processing docutils-0.12.tar.gz
Writing /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-rvWB2u/docutils-0.12/setup.cfg
Running docutils-0.12/setup.py -q bdist_egg --dist-dir /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-rvWB2u/docutils-0.12/egg-dist-tmp-6XC3SZ
warning: no files found matching 'MANIFEST'
warning: no files found matching '*' under directory 'extras'
warning: no previously-included files matching '.cvsignore' found under directory '*'
warning: no previously-included files matching '*.pyc' found under directory '*'
warning: no previously-included files matching '*~' found under directory '*'
warning: no previously-included files matching '.DS_Store' found under directory '*'
zip_safe flag not set; analyzing archive contents...
docutils.writers.docutils_xml: module references __path__
docutils.writers.odf_odt.__init__: module references __file__
docutils.writers.s5_html.__init__: module references __file__
docutils.writers.html4css1.__init__: module references __file__
docutils.writers.pep_html.__init__: module references __file__
docutils.writers.latex2e.__init__: module references __file__
docutils.parsers.rst.directives.misc: module references __file__
creating /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/docutils-0.12-py2.7.egg
Extracting docutils-0.12-py2.7.egg to /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs

Installed /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/docutils-0.12-py2.7.egg
Searching for Pygments>=2.0
Reading https://pypi.python.org/simple/Pygments/
Best match: Pygments 2.1.3
Downloading https://pypi.python.org/packages/b8/67/ab177979be1c81bc99c8d0592ef22d547e70bb4c6815c383286ed5dec504/Pygments-2.1.3.tar.gz#md5=ed3fba2467c8afcda4d317e4ef2c6150
Processing Pygments-2.1.3.tar.gz
Writing /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-cGjEGJ/Pygments-2.1.3/setup.cfg
Running Pygments-2.1.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-cGjEGJ/Pygments-2.1.3/egg-dist-tmp-hlicZE
creating /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/Pygments-2.1.3-py2.7.egg
Extracting Pygments-2.1.3-py2.7.egg to /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs

Installed /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/Pygments-2.1.3-py2.7.egg
Searching for Jinja2>=2.3
Reading https://pypi.python.org/simple/Jinja2/
Best match: Jinja2 2.8
Downloading https://pypi.python.org/packages/f2/2f/0b98b06a345a761bec91a079ccae392d282690c2d8272e708f4d10829e22/Jinja2-2.8.tar.gz#md5=edb51693fe22c53cee5403775c71a99e
Processing Jinja2-2.8.tar.gz
Writing /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-Hk0Q3F/Jinja2-2.8/setup.cfg
Running Jinja2-2.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-Hk0Q3F/Jinja2-2.8/egg-dist-tmp-HtrE8F
warning: no files found matching 'run-tests.py'
warning: no files found matching '*' under directory 'custom_fixers'
warning: no files found matching '*' under directory 'jinja2/testsuite/res'
warning: no previously-included files matching '*' found under directory 'docs/_build'
warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
creating /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/Jinja2-2.8-py2.7.egg
Extracting Jinja2-2.8-py2.7.egg to /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs

Installed /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/Jinja2-2.8-py2.7.egg
Searching for pytz>=0a
Reading https://pypi.python.org/simple/pytz/
Best match: pytz 2016.6.1
Downloading https://pypi.python.org/packages/79/a7/74bf57f5b10bebb8e605dc277484bddc5559ad8cf5082c90fcd64ab5dcc6/pytz-2016.6.1-py2.7.egg#md5=3b1dd4a944e92e84a6510faf81abd655
Processing pytz-2016.6.1-py2.7.egg
Moving pytz-2016.6.1-py2.7.egg to /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs

Installed /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/pytz-2016.6.1-py2.7.egg
Searching for MarkupSafe
Reading https://pypi.python.org/simple/MarkupSafe/
Best match: MarkupSafe 0.23
Downloading https://pypi.python.org/packages/c0/41/bae1254e0396c0cc8cf1751cb7d9afc90a602353695af5952530482c963f/MarkupSafe-0.23.tar.gz#md5=f5ab3deee4c37cd6a922fb81e730da6e
Processing MarkupSafe-0.23.tar.gz
Writing /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-XbCKPu/MarkupSafe-0.23/setup.cfg
Running MarkupSafe-0.23/setup.py -q bdist_egg --dist-dir /tmp/easy_install-W3hcQ0/grpcio-0.15.0/temp/easy_install-XbCKPu/MarkupSafe-0.23/egg-dist-tmp-YvIpFr
creating /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/MarkupSafe-0.23-py2.7-linux-x86_64.egg
Extracting MarkupSafe-0.23-py2.7-linux-x86_64.egg to /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs

Installed /tmp/easy_install-W3hcQ0/grpcio-0.15.0/.eggs/MarkupSafe-0.23-py2.7-linux-x86_64.egg
```

**Comment by daspecster** [comment]
So this must be something with `east_install` then?

```bash
(gcloud-python-rest)╭─daspecster@Toms-MacBook  ~
╰─$ pip install gcloud
Collecting gcloud
  Using cached gcloud-0.17.0.tar.gz
Collecting httplib2>=0.9.1 (from gcloud)
Collecting googleapis-common-protos (from gcloud)
Collecting oauth2client>=2.0.1 (from gcloud)
Collecting protobuf!=3.0.0.b2.post1,>=3.0.0b2 (from gcloud)
  Using cached protobuf-3.0.0b3-py2-none-any.whl
Collecting six (from gcloud)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting grpcio>=0.14.0 (from gcloud)
  Using cached grpcio-0.15.0-cp27-cp27m-macosx_10_10_intel.whl
Collecting google-gax>=0.12.1 (from gcloud)
Collecting gax-google-pubsub-v1>=0.7.10 (from gcloud)
  Downloading gax-google-pubsub-v1-0.7.12.tar.gz
Collecting gax-google-logging-v2>=0.7.10 (from gcloud)
  Downloading gax-google-logging-v2-0.7.12.tar.gz
Collecting rsa>=3.1.4 (from oauth2client>=2.0.1->gcloud)
  Using cached rsa-3.4.2-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client>=2.0.1->gcloud)
  Using cached pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting pyasn1>=0.1.7 (from oauth2client>=2.0.1->gcloud)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./.virtualenvs/gcloud-python-rest/lib/python2.7/site-packages (from protobuf!=3.0.0.b2.post1,>=3.0.0b2->gcloud)
Collecting futures>=2.2.0 (from grpcio>=0.14.0->gcloud)
  Using cached futures-3.0.5-py2-none-any.whl
Collecting enum34>=1.0.4 (from grpcio>=0.14.0->gcloud)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting ply==3.8 (from google-gax>=0.12.1->gcloud)
Collecting grpc-google-pubsub-v1>=0.7.12 (from gax-google-pubsub-v1>=0.7.10->gcloud)
  Downloading grpc-google-pubsub-v1-0.7.12.tar.gz
Collecting grpc-google-logging-v2>=0.7.12 (from gax-google-logging-v2>=0.7.10->gcloud)
  Downloading grpc-google-logging-v2-0.7.12.tar.gz
Installing collected packages: httplib2, six, protobuf, googleapis-common-protos, pyasn1, rsa, pyasn1-modules, oauth2client, futures, enum34, grpcio, ply, google-gax, grpc-google-pubsub-v1, gax-google-pubsub-v1, grpc-google-logging-v2, gax-google-logging-v2, gcloud
  Running setup.py install for grpc-google-pubsub-v1 ... done
  Running setup.py install for gax-google-pubsub-v1 ... done
  Running setup.py install for grpc-google-logging-v2 ... done
  Running setup.py install for gax-google-logging-v2 ... done
  Running setup.py install for gcloud ... done
Successfully installed enum34-1.1.6 futures-3.0.5 gax-google-logging-v2-0.7.12 gax-google-pubsub-v1-0.7.12 gcloud-0.17.0 google-gax-0.12.3 googleapis-common-protos-1.2.0 grpc-google-logging-v2-0.7.12 grpc-google-pubsub-v1-0.7.12 grpcio-0.15.0 httplib2-0.9.2 oauth2client-2.2.0 ply-3.8 protobuf-3.0.0b3 pyasn1-0.1.9 pyasn1-modules-0.0.8 rsa-3.4.2 six-1.10.0
```

**Comment by hir3npatel** [comment]
pip uses easy_install, I think?

I get this trace when doing pip install -r requirements.txt

> No local packages or download links found for Jinja2>=2.3
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ETtN9l/grpcio/setup.py", line 267, in <module>
        cmdclass=COMMAND_CLASS,
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 634, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('Jinja2>=2.3')

I guess some package that grpcio requires, then wants Sphinx and everything that comes with it. I'm not freezing versions in requirements.txt though.

**Comment by tseaver** [comment]
> pip uses easy_install, I think?

Nope -- it uses `setuptools`, but not the `easy_install` script.

With the current `0.20` release of `google-cloud`:

```bash
$ /opt/Python-2.7.11/bin/virtualenv /tmp/gcp-1995
New python executable in /tmp/gcp-1995/bin/python
Installing setuptools, pip, wheel...done.
$ /tmp/gcp-1995/bin/pip install google-cloud
Collecting google-cloud
  ...
Installing collected packages: httplib2, six, protobuf, googleapis-common-protos, pyasn1, rsa, pyasn1-modules, oauth2client, google-cloud-core, google-cloud-resource-manager, google-cloud-dns, google-cloud-bigquery, google-cloud-translate, google-cloud-language, enum34, futures, grpcio, google-cloud-datastore, google-cloud-monitoring, google-cloud-vision, google-cloud-storage, ply, future, google-gax, grpc-google-pubsub-v1, grpc-google-iam-v1, gapic-google-pubsub-v1, google-cloud-pubsub, grpc-google-logging-v2, gapic-google-logging-v2, google-cloud-logging, google-cloud-error-reporting, google-cloud-bigtable, google-cloud
Successfully installed enum34-1.1.6 future-0.15.2 futures-3.0.5 gapic-google-logging-v2-0.10.1 gapic-google-pubsub-v1-0.10.1 google-cloud-0.20.0 google-cloud-bigquery-0.20.0 google-cloud-bigtable-0.20.0 google-cloud-core-0.20.0 google-cloud-datastore-0.20.0 google-cloud-dns-0.20.0 google-cloud-error-reporting-0.20.0 google-cloud-language-0.20.0 google-cloud-logging-0.20.0 google-cloud-monitoring-0.20.0 google-cloud-pubsub-0.20.0 google-cloud-resource-manager-0.20.0 google-cloud-storage-0.20.0 google-cloud-translate-0.20.0 google-cloud-vision-0.20.0 google-gax-0.14.1 googleapis-common-protos-1.3.5 grpc-google-iam-v1-0.10.1 grpc-google-logging-v2-0.10.1 grpc-google-pubsub-v1-0.10.1 grpcio-1.0.0 httplib2-0.9.2 oauth2client-3.0.0 ply-3.8 protobuf-3.1.0.post1 pyasn1-0.1.9 pyasn1-modules-0.0.8 rsa-3.4.2 six-1.10.0
[/home/tseaver] 
$ /tmp/gcp-1995/bin/pip freeze
-f file:///home/tseaver/.pip/wheels
enum34==1.1.6
future==0.15.2
futures==3.0.5
gapic-google-logging-v2==0.10.1
gapic-google-pubsub-v1==0.10.1
google-cloud==0.20.0
google-cloud-bigquery==0.20.0
google-cloud-bigtable==0.20.0
google-cloud-core==0.20.0
google-cloud-datastore==0.20.0
google-cloud-dns==0.20.0
google-cloud-error-reporting==0.20.0
google-cloud-language==0.20.0
google-cloud-logging==0.20.0
google-cloud-monitoring==0.20.0
google-cloud-pubsub==0.20.0
google-cloud-resource-manager==0.20.0
google-cloud-storage==0.20.0
google-cloud-translate==0.20.0
google-cloud-vision==0.20.0
google-gax==0.14.1
googleapis-common-protos==1.3.5
grpc-google-iam-v1==0.10.1
grpc-google-logging-v2==0.10.1
grpc-google-pubsub-v1==0.10.1
grpcio==1.0.0
httplib2==0.9.2
oauth2client==3.0.0
ply==3.8
protobuf==3.1.0.post1
pyasn1==0.1.9
pyasn1-modules==0.0.8
rsa==3.4.2
six==1.10.0
```

In a separate environment, using `easy_install`:

```bash
$ /opt/Python-2.7.11/bin/virtualenv /tmp/gcp-1995-easy_install
New python executable in /tmp/gcp-1995-easy_install/bin/python
Installing setuptools, pip, wheel...done.
$ /tmp/gcp-1995-easy_install/bin/easy_install google-cloud
Searching for google-cloud
...
Finished processing dependencies for google-cloud
$ ls -laF /tmp/gcp-1995-easy_install/lib/python2.7/site-packages/ | grep -i sphinx
```

But I *do* see Sphinx being downloaded and installed into a tempdir during the first command:  `grpcio` has a [`setup_requires` which includes `Sphinx`](https://github.com/grpc/grpc/blob/master/setup.py#L209).  `pip` doesn't surface this issue because it uses the built wheel for `grpcio`.
