### ISSUE TITLE
What setup is required to get Translate system tests running?

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#2063]
I have the Translate API enabled, but see the following when running `tox -e system-tests`:

```python
======================================================================
ERROR: test_detect_language (translate.TestTranslate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/system_tests/translate.py", line 55, in test_detect_language
    detections = Config.CLIENT.detect_language(values)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/gcloud/translate/client.py", line 121, in detect_language
    method='GET', path='/detect', query_params=query_params)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/gcloud/connection.py", line 347, in api_request
    error_info=method + ' ' + url)
BadRequest: 400 Bad Request (GET https://www.googleapis.com/language/translate/v2/detect?key=None&q=takoy&q=fa%C3%A7ade&q=s%27il+vous+plait)

======================================================================
ERROR: test_get_languages (translate.TestTranslate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/system_tests/translate.py", line 43, in test_get_languages
    result = Config.CLIENT.get_languages()
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/gcloud/translate/client.py", line 79, in get_languages
    method='GET', path='/languages', query_params=query_params)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/gcloud/connection.py", line 347, in api_request
    error_info=method + ' ' + url)
BadRequest: 400 Bad Request (GET https://www.googleapis.com/language/translate/v2/languages?key=None&target=en)

======================================================================
ERROR: test_translate (translate.TestTranslate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/system_tests/translate.py", line 65, in test_translate
    target_language='de')
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/gcloud/translate/client.py", line 212, in translate
    method='GET', path='', query_params=query_params)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/gcloud/connection.py", line 347, in api_request
    error_info=method + ' ' + url)
BadRequest: 400 Bad Request (GET https://www.googleapis.com/language/translate/v2?key=None&target=de&q=hvala+ti&q=dankon&q=Me+llamo+Jeff&q=My+name+is+Jeff)

----------------------------------------------------------------------
```

**Comment by dhermes** [comment]
`key=None` is the issue, there is a `GCLOUD_TESTS_API_KEY` env. var. set on Travis

**Comment by tseaver** [comment]
The usage docs should probably point to the API docs for setting up the key (why doesn't the API support service accounts again?)

**Comment by dhermes** [comment]
> why doesn't the API support service accounts again?

@jgeewax 

----

> The usage docs should probably point to the API docs for setting up the key

From [usage doc][1]

![screen shot 2016-08-09 at 10 10 19 am](https://cloud.githubusercontent.com/assets/520669/17525863/85d8f2fe-5e19-11e6-86f1-73a79ff9b2ed.png)

which links out to https://cloud.google.com/translate/v2/translating-text-with-rest#auth which doesn't seem to exist anymore. Maybe we could use https://support.google.com/cloud/answer/6158862

[1]: http://gcloud-python.readthedocs.io/en/latest/translate-usage.html

**Comment by tseaver** [comment]
I think all of us are able to run the `translate` system tests, so we can close for my initial intention.  The docs issue might stlll need to remain for our users, though.
