### ISSUE TITLE
'test_list_subscriptions' barfs sporadically due to gRPC 'UNAVAILABLE' error

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#2111]
`topic.exist()` raises a new [flaky error](https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/152815281#L627-L653), likely due to the cutover to use gRPC by default.

```python
======================================================================
ERROR: test_list_subscriptions (pubsub.TestPubsub)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/system_tests/pubsub.py", line 127, in test_list_subscriptions
    self.assertFalse(topic.exists())
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/gcloud/pubsub/topic.py", line 179, in exists
    api.topic_get(topic_path=self.full_name)
...
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 203, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
GaxError: GaxError(RPC failed, caused by AbortionError(code=StatusCode.UNAVAILABLE, details="{"created":"@1471388632.560540215","description":"Secure read failed","file":"src/core/lib/security/transport/secure_endpoint.c","file_line":157,"grpc_status":14,"referenced_errors":[{"created":"@1471388632.560504209","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235}]}"))
```

**Comment by dhermes** [comment]
Aw man :(

**Comment by dhermes** [comment]
@tseaver This is the only open `flaky` issue left, so that's comforting

**Comment by tseaver** [comment]
I'm going to put on my Pollyanna/Candide hat and claim that #2195 has resolved this issue.

**Comment by tseaver** [comment]
[Nope](https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/155569740#L851-L877).

**Comment by dhermes** [comment]
@tseaver Close out until it shows up again in the wild?

**Comment by tseaver** [comment]
SGTM
