### ISSUE TITLE
test_analyze_entities:  salience outside expected range

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#2274]
From: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/158529136#L1224-L1232

```python
======================================================================
FAIL: test_analyze_entities (language.TestLanguage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/system_tests/language.py", line 103, in test_analyze_entities
    self._check_analyze_entities_result(entities)
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/system_tests/language.py", line 77, in _check_analyze_entities_result
    self.assertTrue(0.7 < entity1.salience < 0.8)
AssertionError: False is not true
```

**Comment by tseaver** [comment]
Similar error in `test_anaylze_entities_from_blob`:

```python
======================================================================
FAIL: test_analyze_entities_from_blob (language.TestLanguage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/system_tests/language.py", line 117, in test_analyze_entities_from_blob
    self._check_analyze_entities_result(entities)
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/system_tests/language.py", line 77, in _check_analyze_entities_result
    self.assertTrue(0.7 < entity1.salience < 0.8)
AssertionError: False is not true
```

**Comment by dhermes** [comment]
Indeed. Le sigh.

```
$ nosetests system_tests/language.py --pdb
> /usr/lib/python2.7/unittest/case.py(422)assertTrue()
-> raise self.failureException(msg)
(Pdb) u
> .../gcloud-python/system_tests/language.py(77)_check_analyze_entities_result()
-> self.assertTrue(0.7 < entity1.salience < 0.8)
(Pdb) entity1
<google.cloud.language.entity.Entity object at 0x7f1fc87e07d0>
(Pdb) entity1.salience
0.81992269
(Pdb) 
```

**Comment by dhermes** [comment]
@jgeewax Can you weigh in here? The actual output of the API seems to be a moving target. Note that the input is a simple sentence that hasn't changed:

```
Michelangelo Caravaggio, Italian painter, is known for 'The Calling of Saint Matthew'.
```

**Comment by dhermes** [comment]
In the meanwhile I'm going to let this set of tests go green, working on a PR now

**Comment by dhermes** [comment]
@jgeewax Can you weigh in here?

**Comment by jgeewax** [comment]
I expect that the underlying model used here will evolve and "get better" over time. We should assert that there is a salience that is non-zero -- but how "salient" something is as determined by the algorithm can't be frozen.

If we get back a zero, missing, etc, that means that the API contract is just "broken", but 0.75 today and 0.82 tomorrow doesn't mean our client is busted...
