### ISSUE TITLE
datastore, client.get_multi error

### ISSUE THREAD

**Issue by matheuspatury** [GoogleCloudPlatform/google-cloud-python#2314]
I'm using an GCE instance with scope cloud-platform to get multiple entities from datastore, but **sometimes** this error happens:

```python
Traceback (most recent call last):
  File "main.py", line 85, in get_entities
    r = ds_client.get_multi(data)
  File "/opt/python3/lib/python3.4/site-packages/gcloud/datastore/client.py", line 301, in get_multi
    transaction_id=transaction and transaction.id,
  File "/opt/python3/lib/python3.4/site-packages/gcloud/datastore/client.py", line 123, in _extended_lookup
    transaction_id=transaction_id,
  File "/opt/python3/lib/python3.4/site-packages/gcloud/datastore/connection.py", line 209, in lookup
    _datastore_pb2.LookupResponse)
  File "/opt/python3/lib/python3.4/site-packages/gcloud/datastore/connection.py", line 124, in _rpc
    data=request_pb.SerializeToString())
  File "/opt/python3/lib/python3.4/site-packages/gcloud/datastore/connection.py", line 93, in _request
    method='POST', headers=headers, body=data)
  File "/opt/python3/lib/python3.4/site-packages/oauth2client/transport.py", line 153, in new_request
    credentials._refresh(orig_request_method)
  File "/opt/python3/lib/python3.4/site-packages/oauth2client/contrib/gce.py", line 134, in _refresh
    self._retrieve_info(http_request)
  File "/opt/python3/lib/python3.4/site-packages/oauth2client/contrib/gce.py", line 117, in _retrieve_info
    self.service_account_email = info['email']
KeyError: 'email'
```

ds_client = gcloud.datastore.Client()
gcloud version= 0.18.1

**Comment by tseaver** [comment]
What version of `oauth2client`?

**Comment by matheuspatury** [comment]
oauth2client version = 3.0.0

**Comment by dhermes** [comment]
Closing in favor of https://github.com/google/oauth2client/issues/645

@matheuspatury Can you weigh in there?
