### ISSUE TITLE
Saving large values to indexed properties raises _Rendezvous exception

### ISSUE THREAD

**Issue by Bogdanp** [GoogleCloudPlatform/google-cloud-python#2422]
Given this code:

```python
from google.cloud import datastore
from google.cloud.datastore import Entity

client = datastore.Client()
with client.transaction() as xact:
    e = Entity(client.key("Test", "123"))
    e.update({"x": "a" * 1500000})
    xact.put(e)
```

version 0.19 of this library raises the following exception on `.put`:

```python
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    xact.put(e)
  File "/Users/bogdan/.virtualenvs/bread/lib/python2.7/site-packages/google/cloud/datastore/batch.py", line 302, in __exit__
    self.commit()
  File "/Users/bogdan/.virtualenvs/bread/lib/python2.7/site-packages/google/cloud/datastore/transaction.py", line 167, in commit
    super(Transaction, self).commit()
  File "/Users/bogdan/.virtualenvs/bread/lib/python2.7/site-packages/google/cloud/datastore/batch.py", line 274, in commit
    self._commit()
  File "/Users/bogdan/.virtualenvs/bread/lib/python2.7/site-packages/google/cloud/datastore/batch.py", line 251, in _commit
    self.project, self._commit_request, self._id)
  File "/Users/bogdan/.virtualenvs/bread/lib/python2.7/site-packages/google/cloud/datastore/connection.py", line 584, in commit
    response = self._datastore_api.commit(project, request)
  File "/Users/bogdan/.virtualenvs/bread/lib/python2.7/site-packages/google/cloud/datastore/connection.py", line 314, in commit
    return self._stub.Commit(request_pb)
  File "/Users/bogdan/.virtualenvs/bread/lib/python2.7/site-packages/grpc/_channel.py", line 481, in __call__
    return _end_unary_response_blocking(state, False, deadline)
  File "/Users/bogdan/.virtualenvs/bread/lib/python2.7/site-packages/grpc/_channel.py", line 432, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, The value of property "x" is longer than 1048487 bytes.)>
```

Previously, this used to raise `gcloud.exceptions.BadRequest`. It seems like this exception should be caught by the library and a more appropriate one should be raised in its stead.

*EDIT*: It turns out the following snippet has the same issue so this is not transaction specific:

```python
from google.cloud import datastore
from google.cloud.datastore import Entity

client = datastore.Client()
e = Entity(client.key("Test", "123"))
e.update({"x": "a" * 1500000})
client.put(e)
```

*EDIT 2*: This does not work either, raising the same exception:

```python
from google.cloud import datastore
from google.cloud.datastore import Entity

client = datastore.Client()
e = Entity(client.key("Test", "123"), exclude_from_indexes=("x",))
e.update({"x": "a" * 1500000})
client.put(e)
```

**Comment by dhermes** [comment]
@Bogdanp Thanks for the heads up. We currently just have an [ad-hoc translation][1] for such errors, so it's kind of a "wait and see".

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/4258b764f401f8c890aefb5a6316d0d73ced66e7/google/cloud/datastore/connection.py#L315-L317
