### ISSUE TITLE
Stackdriver ErrorReporter Unexpected Type

### ISSUE THREAD

**Issue by Teddy-Schmitz** [GoogleCloudPlatform/google-cloud-python#2521]
Hello,

The stack driver error_reporting client throws a ValueError Unexpected type.  Here is the code

```python
from google.cloud import error_reporting
error_reporter = error_reporting.Client()

try:
    raise NameError
except Exception:
    error_reporter.report_exception()
```
And the error
```python
/home/teddy/.virtualenvs/rewards/bin/python /home/teddy/PycharmProjects/rewards/workers/error_test.py
Traceback (most recent call last):
  File "/home/teddy/PycharmProjects/rewards/workers/error_test.py", line 5, in <module>
    raise NameError
NameError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/teddy/PycharmProjects/rewards/workers/error_test.py", line 7, in <module>
    error_reporter.report_exception()
  File "/home/teddy/.virtualenvs/rewards/lib/python3.5/site-packages/google/cloud/error_reporting/client.py", line 251, in report_exception
    user=user)
  File "/home/teddy/.virtualenvs/rewards/lib/python3.5/site-packages/google/cloud/error_reporting/client.py", line 183, in _send_error_report
    logger.log_struct(payload)
  File "/home/teddy/.virtualenvs/rewards/lib/python3.5/site-packages/google/cloud/logging/logger.py", line 226, in log_struct
    client.logging_api.write_entries([entry_resource])
  File "/home/teddy/.virtualenvs/rewards/lib/python3.5/site-packages/google/cloud/logging/_gax.py", line 108, in write_entries
    entry_pbs = [_log_entry_mapping_to_pb(entry) for entry in entries]
  File "/home/teddy/.virtualenvs/rewards/lib/python3.5/site-packages/google/cloud/logging/_gax.py", line 108, in <listcomp>
    entry_pbs = [_log_entry_mapping_to_pb(entry) for entry in entries]
  File "/home/teddy/.virtualenvs/rewards/lib/python3.5/site-packages/google/cloud/logging/_gax.py", line 604, in _log_entry_mapping_to_pb
    entry_pb.json_payload[key] = value
  File "/home/teddy/.virtualenvs/rewards/lib/python3.5/site-packages/google/protobuf/internal/well_known_types.py", line 732, in __setitem__
    _SetStructValue(self.fields[key], value)
  File "/home/teddy/.virtualenvs/rewards/lib/python3.5/site-packages/google/protobuf/internal/well_known_types.py", line 702, in _SetStructValue
    raise ValueError('Unexpected type')
ValueError: Unexpected type
```
It looks like a dict of `{'service': 'python'}` is getting passed to `_SetStructValue` and there is no check for a dict so it is raising a `ValueError`.

**Comment by dhermes** [comment]
@waprin Can you weigh in here?

**Comment by waprin** [comment]
Slightly tied up at the moment but will try to take a look at this asap.

**Comment by waprin** [comment]
@Teddy-Schmitz working on getting this fixed, but in the meantime if you switch to HTTP instead of gRPC by setting `GOOGLE_CLOUD_DISABLE_GRPC` to 1, it will workaround this issue.
