### ISSUE TITLE
Vision raises TypeError: b'...' is not JSON serializable on Python 3

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#2525]
Simple reproducible case:

```python
import io
import os

from google.cloud import vision

vision_client = vision.Client()

file_name = os.path.join(
    os.path.dirname(__file__),
    'resources/wakeupcat.jpg')

with io.open(file_name, 'rb') as image_file:
    image = vision_client.image(
        content=image_file.read())

labels = image.detect_labels()

print('Labels:')
for label in labels:
    print(label.description)
```

works fine on Python 2, fails on Python 3.

**Comment by jonparrott** [comment]
Stack trace:

```
Traceback (most recent call last):
  File "quickstart.py", line 51, in <module>
    run_quickstart()
  File "quickstart.py", line 38, in run_quickstart
    image = vision_client.image(
  File "/Users/jonwayne/.pyenv/versions/3.4.3/lib/python3.4/site-packages/google/cloud/vision/image.py", line 139, in detect_labels
    return self._detect_annotation(feature)
  File "/Users/jonwayne/.pyenv/versions/3.4.3/lib/python3.4/site-packages/google/cloud/vision/image.py", line 105, in _detect_annotation
    result = self.client.annotate(self, [feature])
  File "/Users/jonwayne/.pyenv/versions/3.4.3/lib/python3.4/site-packages/google/cloud/vision/client.py", line 106, in annotate
    data=data)
  File "/Users/jonwayne/.pyenv/versions/3.4.3/lib/python3.4/site-packages/google/cloud/connection.py", line 341, in api_request
    data = json.dumps(data)
  File "/Users/jonwayne/.pyenv/versions/3.4.3/lib/python3.4/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/Users/jonwayne/.pyenv/versions/3.4.3/lib/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/jonwayne/.pyenv/versions/3.4.3/lib/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "/Users/jonwayne/.pyenv/versions/3.4.3/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
```

**Comment by dhermes** [comment]
Same issue fixed by #2520?

**Comment by jonparrott** [comment]
Seems like it, vision probably just needs a similar patch.

**Comment by dhermes** [comment]
Oh my blindness!

@daspecster Do the system tests for vision not cover this?

**Comment by daspecster** [comment]
Zoinks! That bytes. I will get on this right now.

**Comment by jonparrott** [comment]
> That bytes

heheh.

**Comment by daspecster** [comment]
@dhermes Also, sadly there are no system tests for this.
I made an issue to add system tests though.

https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2526

**Comment by dhermes** [comment]
Ah. That is no good. We should not have pushed to PyPI without system tests. Live and learn.

**Comment by daspecster** [comment]
Agreed. I don't think we even brought it up anywhere.

@dhermes I don't think I have access to the system test project(`precise-truck`?) to add things like images and audio  to run the tests on.

**Comment by dhermes** [comment]
@daspecster Get them working locally first and then we can cross that bridge?

**Comment by daspecster** [comment]
Ok, will do.

**Comment by daspecster** [comment]
@jonparrott just merged the fix for this. Let me know if you run into any more issues! Thanks!

**Comment by jonparrott** [comment]
Thanks, will await the next release before I can test it.

**Comment by meta221** [comment]
I'm waiting for the fix for this issue to be released. @jonparrott Do you know when the next release will be?

**Comment by jonparrott** [comment]
It's been released, @meta221
