### ISSUE TITLE
google.cloud.logging 'module' object has no attribute 'Client'

### ISSUE THREAD

**Issue by wakahiu** [GoogleCloudPlatform/google-cloud-python#2544]
I'm trying to run a simple python example from the[ tutorial page ](https://googlecloudplatform.github.io/google-cloud-python/stable/logging-usage.html)

```
>>> from google.cloud import logging
>>> client = logging.Client()
```
And getting the error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Client'
```

I've created and exported the credentials using

```
export GOOGLE_APPLICATION_CREDENTIALS="/path/to/keyfile.json"
```

Running python in a virtual env having installed the SDK using

```
pip install google-cloud
```

**Comment by daspecster** [comment]
Hello @wakahiu!

Did you have google-cloud or gcloud-python installed before?

In version 0.19.0 the library switched to namespace packages and it seems that pip doesn't handle this quite right when upgrading.

I would recommend starting with a fresh virtualenv and installing google-cloud from there.

I was able to get a logging client just now without errors.

**Comment by dhermes** [comment]
@daspecster It might be a clean install, since he has a valid `google.cloud.logging` module object.

I'm not 100% on this but I'm pretty sure it was because of a namespace collision in 0.19.0 made `google.cloud.logging` a namespace package (which could have no members). In 0.20.0 it should work just fine.

@wakahiu Can you give the output of `pip show google-cloud` and `pip show google-cloud-logging`?

**Comment by wakahiu** [comment]
@daspecster and @dhermes 

The outputs of `pip show google-cloud` is
```
---
Metadata-Version: 2.0
Name: google-cloud
Version: 0.20.0
Summary: API Client library for Google Cloud
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: jjg+google-cloud-python@google.com
Installer: pip
License: Apache 2.0
Location: /root/v_env/tensorflow_python2/lib/python2.7/site-packages
Requires: google-cloud-vision, google-cloud-resource-manager, google-cloud-dns, google-cloud-bigquery, google-cloud-language, google-cloud-datastore, google-cloud-monitoring, google-cloud-logging, google-cloud-storage, google-cloud-pubsub, google-cloud-core, google-cloud-error-reporting, google-cloud-translate, google-cloud-bigtable
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  License :: OSI Approved :: Apache Software License
  Operating System :: OS Independent
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Topic :: Internet
```

and  `pip show google-cloud-logging`

```
---
Metadata-Version: 2.0
Name: google-cloud-logging
Version: 0.20.0
Summary: Python Client for Stackdriver Logging
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: jjg+google-cloud-python@google.com
Installer: pip
License: Apache 2.0
Location: /root/v_env/tensorflow_python2/lib/python2.7/site-packages
Requires: google-gax, grpcio, gapic-google-logging-v2, google-cloud-core, grpc-google-logging-v2
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  License :: OSI Approved :: Apache Software License
  Operating System :: OS Independent
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Topic :: Internet
```

**Comment by dhermes** [comment]
@wakahiu Your error is unrelated to credentials, but thanks for the info.

It doesn't seem possible that the attribute would be missing (see [source][1]) **unless** you have another library around that is making `google.cloud.logging` a namespace package. Can you try installing in a fresh virtualenv and see if you get the same error?

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/umbrella-0.20.0/logging/google/cloud/logging/__init__.py

**Comment by daspecster** [comment]
@wakahiu @dhermes, `pip freeze` output might be useful?

**Comment by dhermes** [comment]
Sure it would, though it may be too much noise if it lists the global install :wink:

**Comment by wakahiu** [comment]
@daspecster and @dhermes  the output to `pip freeze` is

``` 
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
boto3==1.4.0
botocore==1.4.57
certifi==2016.9.26
chardet==2.0.1
colorama==0.2.5
docutils==0.12
enum34==1.1.6
funcsigs==1.0.2
future==0.15.2
futures==3.0.5
gapic-google-logging-v2==0.10.1
gapic-google-pubsub-v1==0.10.1
gax-google-logging-v2==0.8.3
gax-google-pubsub-v1==0.8.3
gcloud==0.18.3
google-api-python-client==1.5.3
google-cloud==0.20.0
google-cloud-bigquery==0.20.0
google-cloud-bigtable==0.20.0
google-cloud-core==0.20.0
google-cloud-datastore==0.20.1
google-cloud-dns==0.20.0
google-cloud-error-reporting==0.20.0
google-cloud-language==0.20.0
google-cloud-logging==0.20.0
google-cloud-monitoring==0.20.0
google-cloud-pubsub==0.20.0
google-cloud-resource-manager==0.20.0
google-cloud-storage==0.20.0
google-cloud-translate==0.20.0
google-cloud-vision==0.20.0
google-gax==0.14.1
googleapis-common-protos==1.3.5
grpc-google-iam-v1==0.10.1
grpc-google-logging-v2==0.10.1
grpc-google-pubsub-v1==0.10.1
grpcio==1.0.0
html5lib==0.999
httplib2==0.9.2
jmespath==0.9.0
mock==2.0.0
numpy==1.11.1
oauth2client==3.0.0
pbr==1.10.0
ply==3.8
protobuf==3.1.0.post1
pyasn1==0.1.9
pyasn1-modules==0.0.8
python-dateutil==2.5.3
requests==2.2.1
rsa==3.4.2
s3transfer==0.1.4
simplejson==3.8.2
singledispatch==3.4.0.3
six==1.10.0
tensorflow==0.10.0
tornado==4.4.1
uritemplate==0.6
urllib3==1.7.1
virtualenv==15.0.3
```

Note all the ``google-cloud*`` are at least 0.20. Could it be the ``googleapis``?

Doing `pip freeze` outside the virtual env shows
```
....
google-api-python-client==1.5.3
google-cloud==0.20.0
google-cloud-bigquery==0.20.0
google-cloud-bigtable==0.20.0
google-cloud-core==0.20.0
google-cloud-datastore==0.20.1
google-cloud-dns==0.20.0
google-cloud-error-reporting==0.20.0
google-cloud-language==0.20.0
google-cloud-logging==0.20.0
google-cloud-monitoring==0.20.0
google-cloud-pubsub==0.20.0
google-cloud-resource-manager==0.20.0
google-cloud-storage==0.20.0
google-cloud-translate==0.20.0
google-cloud-vision==0.20.0
...
```

**Comment by daspecster** [comment]
@wakahiu my guess is that `gcloud==0.18.3` is the culprit.

**Comment by dhermes** [comment]
Rather than stipulating about your current install (via `pip freeze`) can you install in a fresh virtualenv and see if the issue persists?

**Comment by wakahiu** [comment]
A couple of things.

First off I am running a nvidia-docker container + venv if it helps.

I've nuked my virtual env and deleted the system pip packages using `pip freeze | xargs pip uninstall -y`. I've tried installing from source as shown [here](http://google-cloud-python.readthedocs.io/en/stable/) and realized the following.

1. I'm able to run the following code successfully in interactive mode. 
```
$python
>>> import google.cloud
>>> print (google.cloud.__file__)
>>> from google.cloud import logging
>>> client = logging.Client()

/root/venv_tensorflow/lib/python2.7/site-packages/gapic_google_logging_v2-0.10.1-py2.7.egg/google/cloud/__init__.pyc
```

2. In a script named logging.py. I run the exact same code but get an error.
```
$python logging.py

/root/venv_tensorflow/lib/python2.7/site-packages/gapic_google_logging_v2-0.10.1-py2.7.egg/google/cloud/__init__.pyc

Traceback (most recent call last):
  File "/root/host_mount/code/behold-ai-learning/scripts/simple.py", line 3, in <module>
    from google.cloud import logging
  File "/root/venv_tensorflow/lib/python2.7/site-packages/google_cloud_logging-0.20.0-py2.7.egg/google/cloud/logging/__init__.py", line 18, in <module>
    from google.cloud.logging.client import Client
  File "/root/venv_tensorflow/lib/python2.7/site-packages/google_cloud_logging-0.20.0-py2.7.egg/google/cloud/logging/client.py", line 37, in <module>
    from google.cloud.client import JSONClient
  File "/root/venv_tensorflow/lib/python2.7/site-packages/google_cloud_core-0.20.0-py2.7.egg/google/cloud/client.py", line 17, in <module>
    from oauth2client.service_account import ServiceAccountCredentials
  File "build/bdist.linux-x86_64/egg/oauth2client/service_account.py", line 25, in <module>
  File "build/bdist.linux-x86_64/egg/oauth2client/client.py", line 24, in <module>
  File "/root/host_mount/code/behold-ai-learning/scripts/logging.py", line 1, in <module>
    from google.cloud import logging
ImportError: cannot import name logging
```

First of all, note that both modules are finding google.cloud in the exact same location. ie 
``/root/venv_tensorflow/lib/python2.7/site-packages/gapic_google_logging_v2-0.10.1-py2.7.egg/google/cloud/__init__.pyc``

**Comment by wakahiu** [comment]
I figured out what was the problem, I was running ``python logging.py`` in a directory that had another logging module and it picked up that instead. I can now run in both interactive mode and thanks.
