### ISSUE TITLE
BigQuery: KeyError when getting query results

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#2585]
[Sample app that reproduces this](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/176f161cae3d4f01b01456a6e403faf6645414a1/bigquery/cloud-client/simple_app.py)

Stacktrace:

```
Traceback (most recent call last):
  File "simple_app.py", line 57, in <module>
    query_shakespeare()
  File "simple_app.py", line 47, in query_shakespeare
    page_token=page_token)
  File "lib/python2.7/site-packages/google/cloud/bigquery/query.py", line 401, in fetch_data
    rows_data = _rows_from_json(response.get('rows', ()), self.schema)
  File "lib/python2.7/site-packages/google/cloud/bigquery/_helpers.py", line 98, in _rows_from_json
    for item in cell['v']])
  File "lib/python2.7/site-packages/google/cloud/bigquery/_helpers.py", line 61, in _record_from_json
    for subfield, cell in zip(field.fields, value['f']):
KeyError: 'f'
```

----

Stepping into the debugger:

```python
ipdb> value
{u'v': {u'f': [{u'v': u'hamlet'}, {u'v': u'5318'}]}}
ipdb> field.__dict__
{'field_type': u'RECORD', 'description': None, 'name': u'title', 'fields': [<google.cloud.bigquery.schema.SchemaField object at 0x7f4ba9227550>, <google.cloud.bigquery.schema.SchemaField object at 0x7f4ba9227690>], 'mode': u'REPEATED'}
```

(Added by @dhermes)

**Comment by jonparrott** [comment]
Possibly a dupe of https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2354, in either case this provides a simple reproducable sample.

**Comment by dhermes** [comment]
Definite dupe. @jonparrott You can decide which one to close.

**Comment by jonparrott** [comment]
Ah man, I don't want power. I just want the illusion of power. I say whoever decides to fix it should decide.
