### ISSUE TITLE
Deadline Exceeded & Multithreading

### ISSUE THREAD

**Issue by dmitry-saritasa** [GoogleCloudPlatform/google-cloud-python#2654]
I'm trying to parallelize writes into BigTable with Python Threads and getting 2 errors (see below). I'm not making any reads, updates or deletes, just pure new inserts. 

# System Info
```bash
$ uname -a                                                                                   
Linux dmitrypc.npb.saritasa.io 4.7.7-200.fc24.x86_64 #1 SMP Sat Oct 8 00:21:59 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ python --version                           
Python 2.7.12

$ pip list installed | grep google
20:gax-google-logging-v2 (0.8.3)
21:gax-google-pubsub-v1 (0.8.3)
23:google-cloud-bigtable (0.20.0)
24:google-cloud-core (0.20.0)
25:google-gax (0.12.5)
26:googleapis-common-protos (1.3.5)
28:grpc-google-logging-v2 (0.8.1)
29:grpc-google-pubsub-v1 (0.8.1)
```

# Error 1

```python
rm -rf trivver.log && time python create.py

Exception in thread Thread-27:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "create.py", line 22, in writer
    record.save()
  File "/home/dmitry/Projects/trivver/storm/libs/db/models.py", line 326, in save
    self._persist(instance_id)
  File "/home/dmitry/Projects/trivver/storm/libs/db/models.py", line 300, in _persist
    self.backend.save(self, instance_id)
  File "/home/dmitry/Projects/trivver/storm/libs/db/models.py", line 211, in save
    row.commit()
  File "/home/dmitry/Projects/experiments/storm/petrel/chapter3/example1/petrel/lib/python2.7/site-packages/gcloud/bigtable/row.py", line 399, in commit
    client._data_stub.MutateRow(request_pb, client.timeout_seconds)
  File "/home/dmitry/Projects/experiments/storm/petrel/chapter3/example1/petrel/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 305, in __call__
    self._request_serializer, self._response_deserializer)
  File "/home/dmitry/Projects/experiments/storm/petrel/chapter3/example1/petrel/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 203, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
ExpirationError: ExpirationError(code=StatusCode.DEADLINE_EXCEEDED, details="Deadline Exceeded")

```

If I run fewer threads like 100 I never get such exception

# Error 2

At the end of code execution I see the following console output after exception.

```bash
Done
E1031 15:12:22.408661218   17997 network_status_tracker.c:48] Memory leaked as all network endpoints were not shut down
python create.py  0.00s user 0.00s system 0% cpu 1:40.44 total
```

**Do I need to call explicit method to disconnect connection?** I have not found anything in the documentation

this is my **create.py**:

```python

import threading

import config as cfg
from boltons.debugutils import pdb_on_exception, pdb_on_signal
from libs.db.connections import connect
from topology.data import records, simulation

log = cfg.config.loggers.trivver

# pdb_on_signal()
# pdb_on_exception()

count_v = 0
count_e = 0

connection = connect(*cfg.config.db_connection_params, admin=True)


def writer(record):
    log.debug("Writing {}/{}".format(
        threading.currentThread().getName(), record))
    record.save()
    return


def counters(record):
    global count_e, count_v

    if isinstance(record, records.ViewabilityRecord):
        count_v += 1
    if isinstance(record, records.EngagementRecord):
        count_e += 1

counter = 0
streamer = simulation.streams.SimulationStreamer(cfg.config)
threads = []

for data in streamer:

    # conn = data.save()
    t = threading.Thread(target=writer, args=(data,))
    threads.append(t)
    t.start()
    counters(data)
    counter += 1
    if counter > 10000:
        print('Done')
        exit(1)

```

this is code related to saving:
**line 211 of File "/home/dmitry/Projects/trivver/storm/libs/db/models.py", line 211, in save
    row.commit()**

```python
class BigTableBackend(object):
    __metaclass__ = Singleton
    _tables = LRU()

    def _get_connection(self, instance_id=None):
        """Return BigTable connection if established
        """
        if not hasattr(self, 'conn'):
            self.conn = get_connection(instance_id)
        return self.conn

    @cachedmethod('_tables')
    def get_table(self, name, instance_id=None):
        """Get BigTable table instance
        """
        return self._get_connection(instance_id).table(name)

    def get_column_family(self, table, column_family_id):
        """Get Column Family of the table
        """
        return table.column_family(column_family_id)

    def create_table(self, name, instance_id=None):
        """Create BigTable table
        """
        table = self.get_table(name)
        table.create()
        return table

    def create_column_family(self, table, column_family_id):
        """Create BigTable table column family
        """
        cf = self.get_column_family(table, column_family_id)
        cf.create()
        return cf

    def save(self, record, instance_id=None):
        """Save record in BigTable table
        """
        row_key = record.row_key
        tbl = self.get_table(record.Meta.table, instance_id)
        row = tbl.row(row_key)
        # go through column families and call set cell
        # to persist column value in DB
        # None can't be converted to bytes used to store data
        # in BT therefore we check and persist only non NULL
        # values
        for column_family, columns in record.__column_families__.items():
            for col in columns:
                val = getattr(record, col, None)
                if val:
                    row.set_cell(
                        column_family, col, val)
        row.commit()
```

this is how I make and manage connections to BigTable instance (that's related to these lines of code @ create.py)

```python
from libs.db.connections import connect
connection = connect(*cfg.config.db_connection_params, admin=True)
```

**libs/db/connections.py**

```python
from gcloud import bigtable
from oauth2client.service_account import ServiceAccountCredentials

from .exceptions import ConnectionError

scopes = ['https://www.googleapis.com/auth/sqlservice.admin']

__all__ = [
    'connect', 'get_db', 'get_connection'
]

_connection_settings = {}
_connections = {}
_dbs = {}


def register_connection(key, project_id, instance_id, admin=False, **kwargs):
    """Register db connection credentials
    Args:
        project_id (str): Google ID of the project
        instance_id (str): Google ID of the Bigtable instance
        admin (bool): If you need to run admin-level commands
            like to create tables/column families etc

    This function will store connection in a global dictionary of connections

    """
    global _connection_settings

    conn_settings = {
        'key': key,
        'project_id': project_id,
        'admin': admin
    }

    conn_settings.update(kwargs)
    _connection_settings[instance_id] = conn_settings


def disconnect(instance_id):
    """Disconnect the connection
    Args:
        instance_id (str): Google ID of the Bigtable instance
    """
    global _connections
    global _dbs

    if instance_id in _connections:
        # get_connection(instance_id=instance_id).close()
        del _connections[instance_id]
    if instance_id in _dbs:
        del _dbs[instance_id]


def get_connection(instance_id=None, reconnect=False):
    """
    Get connection from a dictionary of registered connections
    If no connection is registered for given instance_id
    the new connection will be established and registered

    Args:
        instance_id (str): Google ID of the Bigtable instance

    Returns:
        Bigtable instance of the connection


    """
    global _connections
    global _connection_settings

    # Delete if reconnect asked
    if reconnect:
        disconnect(instance_id)

    # If not instance_id is given and we have only a single
    # registered connection - return it
    if not instance_id:
        instances = _connections.keys()
        if len(instances) == 1:
            return _connections[instances.pop()]
        elif len(instances) > 1:
            raise AttributeError('Instance ID should be provided')
        else:
            raise ConnectionError('No connections registered yet')

    key = _connection_settings[instance_id].get('key')
    pid = _connection_settings[instance_id].get('project_id')
    admin = _connection_settings[instance_id].get('admin', False)

    # if not connection is registered,
    # create new connection
    if instance_id not in _connections:
        try:
            credentials = ServiceAccountCredentials.from_json_keyfile_name(
                key, scopes=scopes)
            client = bigtable.Client(
                project=pid, credentials=credentials, admin=admin)
            client.start()
            _connections[instance_id] = client.instance(instance_id)
            _dbs[instance_id] = client

        except Exception, e:
            raise ConnectionError(
                "Cannot connect to bigtable %s :\n%s" % (instance_id, e))
    return _connections[instance_id]


def get_db(instance_id, reconnect=False):
    global _dbs

    if reconnect:
        disconnect(instance_id)

    if instance_id not in _dbs:
        conn = get_connection(instance_id)
    return _dbs[instance_id]


def connect(key, project_id, instance_id, admin=False, **kwargs):
    """Primary function to call when we need to establish a new
    connection

    Args:
        project_id (str): Google ID of the project
        instance_id (str): Google ID of the Bigtable instance
        admin (bool): If you need to run admin-level commands
            like to create tables/column families etc

    Returns:
        Bigtable instance of the connection

    """
    global _connections

    if instance_id not in _connections:
        register_connection(
            key, project_id, instance_id, admin, **kwargs)

    # TODO: reconnect doesn't work, need debug
    # when you change admin=True->False with reconnect=True, no changes
    # reflected
    return get_connection(
        instance_id, kwargs.get('reconnect', False))
```

# Error 3
also in the log I see a lot of messagges like the following. 

```log
143:[2016-10-31 15:10:50,611][oauth2client.client][INFO]Refreshing access_token
145:[2016-10-31 15:10:50,710][oauth2client.client][INFO]Refreshing access_token
146:[2016-10-31 15:10:50,712][oauth2client.client][INFO]Refreshing access_token
147:[2016-10-31 15:10:50,714][oauth2client.client][INFO]Refreshing access_token
149:[2016-10-31 15:10:50,909][oauth2client.client][INFO]Refreshing access_token
150:[2016-10-31 15:10:50,911][oauth2client.client][INFO]Refreshing access_token
153:[2016-10-31 15:10:51,045][oauth2client.client][INFO]Refreshing access_token
155:[2016-10-31 15:10:51,177][oauth2client.client][INFO]Refreshing access_token
157:[2016-10-31 15:10:51,364][oauth2client.client][INFO]Refreshing access_token
158:[2016-10-31 15:10:51,365][oauth2client.client][INFO]Refreshing access_token
164:[2016-10-31 15:10:51,614][oauth2client.client][INFO]Refreshing access_token
167:[2016-10-31 15:10:51,863][oauth2client.client][INFO]Refreshing access_token
168:[2016-10-31 15:10:51,868][oauth2client.client][INFO]Refreshing access_token
170:[2016-10-31 15:10:51,981][oauth2client.client][INFO]Refreshing access_token
174:[2016-10-31 15:10:52,294][oauth2client.client][INFO]Refreshing access_token
176:[2016-10-31 15:10:52,340][oauth2client.client][INFO]Refreshing access_token
177:[2016-10-31 15:10:52,341][oauth2client.client][INFO]Refreshing access_token
178:[2016-10-31 15:10:52,520][oauth2client.client][INFO]Refreshing access_token
179:[2016-10-31 15:10:52,525][oauth2client.client][INFO]Refreshing access_token
181:[2016-10-31 15:10:52,625][oauth2client.client][INFO]Refreshing access_token
183:[2016-10-31 15:10:52,858][oauth2client.client][INFO]Refreshing access_token
185:[2016-10-31 15:10:52,952][oauth2client.client][INFO]Refreshing access_token
186:[2016-10-31 15:10:52,956][oauth2client.client][INFO]Refreshing access_token
190:[2016-10-31 15:10:53,099][oauth2client.client][INFO]Refreshing access_token
194:[2016-10-31 15:10:53,233][oauth2client.client][INFO]Refreshing access_token

```

**Comment by dmitry-saritasa** [comment]
also if I'm trying to persist 1000 records, (I think due to exceptions) I only get 30% persisted

```
=> 8132
hbase(main):010:0> count 'engagement'
461 row(s) in 2.1230 seconds

hbase(main):012:0> count 'viewability'
Current count: 1000, row: 1#A\xD6\x05\xF2!\x00\x00\x00#100                                                                         
Current count: 2000, row: 1#A\xD6\x05\xF4{\x80\x00\x00#100                                                                         
Current count: 3000, row: 2#A\xD6\x05\xF1y\x80\x00\x00#100                                                                         
Current count: 4000, row: 2#A\xD6\x05\xF4=@\x00\x00#100                                                                            
Current count: 5000, row: 3#A\xD6\x05\xF1k\xC0\x00\x00#100                                                                         
Current count: 6000, row: 3#A\xD6\x05\xF42\x00\x00\x00#100                                                                         
Current count: 7000, row: 4#A\xD6\x05\xF1`\xC0\x00\x00#100                                                                         
Current count: 8000, row: 4#A\xD6\x05\xF4%\x80\x00\x00#100                                                                         
8466 row(s) in 1.8690 seconds

=> 8466
hbase(main):013:0>


=> 461
hbase(main):011:0> count 'engagement'
486 row(s) in 1.5380 seconds

=> 486
```

as you can see 
8466−8132+486−461 = 359 records only got persisted. However, I sent 1,000 row.commit() ops against SDK.

thanks,
Dmitry

**Comment by dhermes** [comment]
@dmitry-saritasa Wow that's a lot to say.

- The `[INFO]Refreshing access_token` in your logs is because `oauth2client` is getting a new token in each thread, so they are racing
- The `Memory leaked as all network endpoints` message is being tracked: https://github.com/grpc/grpc/issues/7849. Though it seems scary, it isn't the problem for your application failing

**Comment by dmitry-saritasa** [comment]
even if I remove threading to
```python

if __name__ == '__main__':

    count_v = 0
    count_e = 0
    counter = 0

    connection = connect(*cfg.config.db_connection_params, admin=True)
    streamer = simulation.streams.SimulationStreamer(cfg.config)
    threads = []

    for data in streamer:

        # conn = data.save()
        # t = threading.Thread(target=writer, args=(data,))
        # threads.append(t)
        # t.start()
        # counters(data)
        # t.join()
        writer(data)
        counter += 1
        if counter > 1000:
            print('Done')
            exit(1)
```

I get no exceptions, but I don't persist nearly 1000 records

**before I run python create.py**
```
hbase(main):013:0> count 'viewability'
Current count: 1000, row: 1#A\xD6\x05\xF2!\x00\x00\x00#100                                                                                     
Current count: 2000, row: 1#A\xD6\x05\xF4{\x80\x00\x00#100                                                                                     
Current count: 3000, row: 2#A\xD6\x05\xF11\x00\x00\x00#100                                                                                     
Current count: 4000, row: 2#A\xD6\x05\xF3\xF9\xC0\x00\x00#100                                                                                  
Current count: 5000, row: 3#A\xD6\x05\xF0\xF5\x00\x00\x00#100                                                                                  
Current count: 6000, row: 3#A\xD6\x05\xF3\xBC\x80\x00\x00#100                                                                                  
Current count: 7000, row: 4#A\xD6\x05\xF0\xBB\xC0\x00\x00#100                                                                                  
Current count: 8000, row: 4#A\xD6\x05\xF3\x84\x00\x00\x00#100                                                                                  
8773 row(s) in 1.8380 seconds

=> 8773
hbase(main):014:0> count 'engagement'
504 row(s) in 1.4040 seconds

=> 504
hbase(main):015:0> count 'viewability'
Current count: 1000, row: 1#A\xD6\x05\xF2!\x00\x00\x00#100                                                                                     
Current count: 2000, row: 1#A\xD6\x05\xF4{\x80\x00\x00#100                                                                                     
Current count: 3000, row: 2#A\xD6\x05\xF1\x19\x80\x00\x00#100                                                                                  
Current count: 4000, row: 2#A\xD6\x05\xF3\xE4@\x00\x00#100                                                                                     
Current count: 5000, row: 3#A\xD6\x05\xF0\xC3@\x00\x00#100                                                                                     
Current count: 6000, row: 3#A\xD6\x05\xF3\x86\x80\x00\x00#100                                                                                  
Current count: 7000, row: 4#A\xD6\x05\xF0h\x00\x00\x00#100                                                                                     
Current count: 8000, row: 4#A\xD6\x05\xF3-\xC0\x00\x00#100                                                                                     
8942 row(s) in 1.8540 seconds
```

I have 504 records in engagement table and 8942 in viewability table

**after I run python create.py that issue 1000 writes into those tables combined on a random basis**
```
hbase(main):018:0> count 'viewability'
Current count: 1000, row: 1#A\xD6\x05\xF2!\x00\x00\x00#100                                                                                     
Current count: 2000, row: 1#A\xD6\x05\xF4{\x80\x00\x00#100                                                                                     
Current count: 3000, row: 2#A\xD6\x05\xF1\x19\x80\x00\x00#100                                                                                  
Current count: 4000, row: 2#A\xD6\x05\xF3\xE4@\x00\x00#100                                                                                     
Current count: 5000, row: 3#A\xD6\x05\xF0\xC3@\x00\x00#100                                                                                     
Current count: 6000, row: 3#A\xD6\x05\xF3\x86\x80\x00\x00#100                                                                                  
Current count: 7000, row: 4#A\xD6\x05\xF0h\x00\x00\x00#100                                                                                     
Current count: 8000, row: 4#A\xD6\x05\xF3-\xC0\x00\x00#100                                                                                     
8942 row(s) in 2.0830 seconds

=> 8942
hbase(main):019:0> count 'engagement'
531 row(s) in 1.4920 seconds

=> 531
```

531-504 + 8942-8773 = 196 rows persisted only so far. 

Thanks,
Dmitry

**Comment by dhermes** [comment]
@dmitry-saritasa Unfortunately I can't debug your entire app. Any way you could slim down the code into a [Gist][1] that uses mostly / only code elements from this library? This way we can zoom in on the problem and try to help.

[1]: https://gist.github.com/

**Comment by dmitry-saritasa** [comment]
okay will try to do that. Is there a way through SDK to see status of row.commit() operation? I.e. failed because of...

**Comment by dhermes** [comment]
`row.commit()` will raise an exception if it fails

**Comment by dmitry-saritasa** [comment]
```
pip install faker
```

then in hbase shell

```
hbase(main):009:0> disable 'viewability'
Oct 31, 2016 5:42:43 PM com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@b56d8a7] Created with target bigtableadmin.googleapis.com:443
0 row(s) in 0.8820 seconds

hbase(main):010:0> drop 'viewability'
0 row(s) in 0.7630 seconds

hbase(main):011:0> create 'viewability', 'stat'
0 row(s) in 0.5460 seconds

=> Hbase::Table - viewability
hbase(main):012:0> count 'viewability'
0 row(s) in 1.5820 seconds

=> 0
hbase(main):013:0> 
```

**logconfig.ini**
https://gist.github.com/dmitry-saritasa/9811e1afec650b54b04dcc96e0074a6f

**demo.py**
https://gist.github.com/dmitry-saritasa/51090453d1c3803e46e3f8543b1a64e7

run it with

```bash
rm -rf trivver.log && time python demo.py
```

and you will get plenty of DEADLINE_EXCEEDED exceptions

**Comment by daspecster** [comment]
@dmitry-saritasa, I noticed that you're first stacktrace is using some older version of `gcloud` although you `pip freeze` looks like it's using the newer `google-cloud`.  So something might be amiss there.

```python
  File "/home/dmitry/Projects/experiments/storm/petrel/chapter3/example1/petrel/lib/python2.7/site-packages/gcloud/bigtable/row.py", line 399, in commit
    client._data_stub.MutateRow(request_pb, client.timeout_seconds)
```
It appears that the timeout logic has [changed](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/94aa18c6a6d16ae29183df70ee9422e2b4b1fd1c/bigtable/google/cloud/bigtable/row.py#L399) a bit since [then](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/3ee623e9a9762356fa1cd0abf74a1410e81b2243/gcloud/bigtable/row.py#L399).

Do you have a stack trace when using `google-cloud`?

**Comment by dmitry-saritasa** [comment]
Indeed once moved to google.cloud instead of gcloud the problem is gone, It seems I referenced older documentation/example (can't find where) which was using gcloud instead.

Thank you Guys!
