### ISSUE TITLE
AttributeError: 'module' object has no attribute 'LoggingServiceV2Stub'

### ISSUE THREAD

**Issue by jacobgmathew** [GoogleCloudPlatform/google-cloud-python#2688]
I'm running into an error with google.cloud.logging. 

`pip show google-cloud-python` says I am on version: 0.20.0

When I run:
```
import google.cloud.logging
google.cloud.logging.Client().logger('test-logger').log_text('test message')
```
I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/logger.py", line 192, in log_text
    client.logging_api.write_entries([entry_resource])
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/client.py", line 89, in logging_api
    generated = GeneratedLoggingAPI()
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/gapic/logging/v2/logging_service_v2_api.py", line 179, in __init__
    logging_pb2.LoggingServiceV2Stub,
AttributeError: 'module' object has no attribute 'LoggingServiceV2Stub'
```

**Comment by daspecster** [comment]
Hello @jacobgmathew!

You may need to update `pip install --upgrade gapic-google-logging-v2`.

**Comment by jacobgmathew** [comment]
That worked. Thanks!
