### ISSUE TITLE
Installing keras library on google app engine

### ISSUE THREAD

**Issue by mokhoo** [GoogleCloudPlatform/google-cloud-python#2718]
Hi All,
I am trying to install keras library to use it on google app engine. First, this library needs the following libraries:
numpy
scipy
theano

first, I had a problem in installing numpy, and when i say install, I mean I run the following in my application directory:
`pip install -t . numpy
`
when I use numpy in my application I get the following error:

```
Traceback (most recent call last):
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/home/a_mokhtar85/src/tutorial-project-149019/python_gae_quickstart-2016-11-09-11-02/main.py", line 8, in <module>
    import numpy as np
  File "/home/a_mokhtar85/src/tutorial-project-149019/python_gae_quickstart-2016-11-09-11-02/numpy/__init__.py", line 142, in <module>
    obj = __import__(path[0])
    from . import add_newdocs
  File "/home/a_mokhtar85/src/tutorial-project-149019/python_gae_quickstart-2016-11-09-11-02/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/a_mokhtar85/src/tutorial-project-149019/python_gae_quickstart-2016-11-09-11-02/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/a_mokhtar85/src/tutorial-project-149019/python_gae_quickstart-2016-11-09-11-02/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/a_mokhtar85/src/tutorial-project-149019/python_gae_quickstart-2016-11-09-11-02/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/sandbox.py", line 963, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named numpy.core.multiarray
```
I solved this issue by using the pre installed numpy library by adding it in the app.yaml as follows:

```
libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: numpy
  version: "1.6.1"
```
Now, when I installed scipy, theano and keras:
```
pip install -t . scipy
pip install -t . theano
pip install -t . keras
```

When I deploy (or preview) the application, I get the following error when I import keras:
```

Traceback (most recent call last):
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/home/a_mokhtar85/src/tutorial-project-149019/python_gae_quickstart-2016-11-09-11-02/main.py", line 9, in <module>
    from keras.models import Sequential
  File "/home/a_mokhtar85/src/tutorial-project-149019/python_gae_quickstart-2016-11-09-11-02/lib/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/home/a_mokhtar85/src/tutorial-project-149019/python_gae_quickstart-2016-11-09-11-02/lib/keras/backend/__init__.py", line 18, in <module>
    _keras_base_dir = os.path.expanduser('~')
  File "/usr/lib/python2.7/posixpath.py", line 268, in expanduser
    import pwd
  File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/sandbox.py", line 963, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named pwd


```

If I run python on the shell, everything works fine, I mean I can import keras and the rest of code works, however, when I deploy or run using 
`dev_appserver.py app.yaml `
I get the errors above. 

Thanks,

**Comment by dhermes** [comment]
Here is the App Engine issue tracker: https://code.google.com/p/googleappengine/issues/list

This library is a Python client library for Google Cloud APIs (it is not part of App Engine)
