### ISSUE TITLE
datastore emulator Unknown request URIs

### ISSUE THREAD

**Issue by mattwarrenrnp** [GoogleCloudPlatform/google-cloud-python#2744]
running into an issue with gcloud-python not being able to communicate with the datastore emulator.

was able to reproduce this on both python 2.7.12 and 3.5.1
gcloud-python is 0.18.3

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattwarren/Work/cui-svc/venv/lib/python2.7/site-packages/gcloud/datastore/client.py", line 329, in put
    self.put_multi(entities=[entity])
  File "/Users/mattwarren/Work/cui-svc/venv/lib/python2.7/site-packages/gcloud/datastore/client.py", line 355, in put_multi
    current.commit()
  File "/Users/mattwarren/Work/cui-svc/venv/lib/python2.7/site-packages/gcloud/datastore/batch.py", line 260, in commit
    self._commit()
  File "/Users/mattwarren/Work/cui-svc/venv/lib/python2.7/site-packages/gcloud/datastore/batch.py", line 243, in _commit
    self.project, self._commit_request, self._id)
  File "/Users/mattwarren/Work/cui-svc/venv/lib/python2.7/site-packages/gcloud/datastore/connection.py", line 342, in commit
    _datastore_pb2.CommitResponse)
  File "/Users/mattwarren/Work/cui-svc/venv/lib/python2.7/site-packages/gcloud/datastore/connection.py", line 124, in _rpc
    data=request_pb.SerializeToString())
  File "/Users/mattwarren/Work/cui-svc/venv/lib/python2.7/site-packages/gcloud/datastore/connection.py", line 97, in _request
    error_status = status_pb2.Status.FromString(content)
  File "/Users/mattwarren/Work/cui-svc/venv/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 780, in FromString
    message.MergeFromString(s)
  File "/Users/mattwarren/Work/cui-svc/venv/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1087, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/Users/mattwarren/Work/cui-svc/venv/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1113, in InternalParse
    new_pos = local_SkipField(buffer, new_pos, end, tag_bytes)
  File "/Users/mattwarren/Work/cui-svc/venv/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "/Users/mattwarren/Work/cui-svc/venv/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 820, in _RaiseInvalidWireType
    raise _DecodeError('Tag had invalid wire type.')
google.protobuf.message.DecodeError: Tag had invalid wire type.
```

Here's how to reproduce:

```
$  gcloud beta emulators datastore start --project=proj &
$  $(gcloud beta emulators datastore env-init) 
$  python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from gcloud import datastore

client = datastore.Client()
entity = datastore.Entity(client.key('Test1'))
client.put(entity)
>>> 
>>> client = datastore.Client()
>>> entity = datastore.Entity(client.key('Test1'))
>>> client.put(entity)
[datastore] Nov 16, 2016 4:32:47 PM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
[datastore] INFO: Adding handler(s) to newly registered Channel.
[datastore] Nov 16, 2016 4:32:48 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[datastore] INFO: Detected non-HTTP/2 connection.
[datastore] Nov 16, 2016 4:32:48 PM io.gapi.emulators.netty.NotFoundHandler handleRequest
[datastore] INFO: Unknown request URI: /datastore/v1beta3/projects/proj:commit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattwarren/Work/cui-svc/nl_api/venv/lib/python3.5/site-packages/gcloud/datastore/client.py", line 329, in put
    self.put_multi(entities=[entity])
  File "/Users/mattwarren/Work/cui-svc/nl_api/venv/lib/python3.5/site-packages/gcloud/datastore/client.py", line 355, in put_multi
    current.commit()
  File "/Users/mattwarren/Work/cui-svc/nl_api/venv/lib/python3.5/site-packages/gcloud/datastore/batch.py", line 260, in commit
    self._commit()
  File "/Users/mattwarren/Work/cui-svc/nl_api/venv/lib/python3.5/site-packages/gcloud/datastore/batch.py", line 243, in _commit
    self.project, self._commit_request, self._id)
  File "/Users/mattwarren/Work/cui-svc/nl_api/venv/lib/python3.5/site-packages/gcloud/datastore/connection.py", line 342, in commit
    _datastore_pb2.CommitResponse)
  File "/Users/mattwarren/Work/cui-svc/nl_api/venv/lib/python3.5/site-packages/gcloud/datastore/connection.py", line 124, in _rpc
    data=request_pb.SerializeToString())
  File "/Users/mattwarren/Work/cui-svc/nl_api/venv/lib/python3.5/site-packages/gcloud/datastore/connection.py", line 97, in _request
    error_status = status_pb2.Status.FromString(content)
  File "/Users/mattwarren/Work/cui-svc/nl_api/venv/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 780, in FromString
    message.MergeFromString(s)
  File "/Users/mattwarren/Work/cui-svc/nl_api/venv/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1087, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/Users/mattwarren/Work/cui-svc/nl_api/venv/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1113, in InternalParse
    new_pos = local_SkipField(buffer, new_pos, end, tag_bytes)
  File "/Users/mattwarren/Work/cui-svc/nl_api/venv/lib/python3.5/site-packages/google/protobuf/internal/decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "/Users/mattwarren/Work/cui-svc/nl_api/venv/lib/python3.5/site-packages/google/protobuf/internal/decoder.py", line 820, in _RaiseInvalidWireType
    raise _DecodeError('Tag had invalid wire type.')
google.protobuf.message.DecodeError: Tag had invalid wire type.
```

you can see the `[datastore]` lines in that output to suggest an unknown URI.

**Comment by daspecster** [comment]
@mattwarrenrnp, any reason you're using an older version of `gcloud`?

This might work by starting with a fresh venv and the latest version of datastore, `pip install --upgrade google-cloud`.

**Comment by dhermes** [comment]
@mattwarrenrnp Please upgrade from `gcloud` to `google-cloud`. The underlying emulator shipped with the `gcloud` CLI has changed since that release, which explains the failing code.

----

Sidebar: @jonparrott Would it be strange to do a new release of `gcloud` that just throws an `ImportError` with instructions to upgrade to `google-cloud`?

**Comment by dhermes** [comment]
@mattwarrenrnp Thanks for forcing us to think about deprecation messaging!
