### ISSUE TITLE
error with Topic.exists() when topic does not exist

### ISSUE THREAD

**Issue by ele-atl** [GoogleCloudPlatform/google-cloud-python#2794]
When calling exists() on a topic which does not exist, I get the following error:

```
 >>>t.exists()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub/topic.py", line 179, in exists
    api.topic_get(topic_path=self.full_name)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub/_gax.py", line 126, in topic_get
    topic_pb = self._gax_api.get_topic(topic_path)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/gapic/pubsub/v1/publisher_api.py", line 314, in get_topic
    return self._get_topic(request, options)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 481, in inner
    return api_caller(api_call, this_settings, request)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 469, in base_caller
    return api_call(*args)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 434, in inner
    errors.create_error('RPC failed', cause=exception))
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 430, in inner
    return a_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 64, in inner
    return a_func(*updated_args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 481, in __call__
    return _end_unary_response_blocking(state, False, deadline)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 432, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
ValueError: RPC failed: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Invalid resource name given (name=projects/PROJECT-NAME/topics/TOPIC-NAME). Refer to https://cloud.google.com/pubsub/overview#names for more information.)>

```

**Comment by daspecster** [comment]
@ele-atl thanks for reporting!

I was unable to reproduce by just calling `exists()` on a non-existent topic.
Can you add some more to your example, like how you created the topic?

Here's the code I tried...
```python
>>> from google.cloud import pubsub
>>> c = pubsub.Client()
>>> t = c.topic('test')
>>> t.exists()
False
```

**Comment by ele-atl** [comment]
sorry, my mistake…
I realised after trying your example that I used an invalid name for my test topic.
Thanks for your time

**Comment by daspecster** [comment]
No problem! I'm glad it was something simple!
