### ISSUE TITLE
AttributeError: 'Credentials' object has no attribute 'authorize'

### ISSUE THREAD

**Issue by Fkawala** [GoogleCloudPlatform/google-cloud-python#2832]
Hello, 

To run this snippet : 
```python
import google
import google.cloud.logging
import google.cloud.logging.handlers 

client = google.cloud.logging.Client()
handler = google.cloud.logging.handlers.CloudLoggingHandler(client=client, name="xyz")
```
Fails as follow
```bash
Traceback (most recent call last):
  File "s.py", line 6, in <module>
    handler = google.cloud.logging.handlers.CloudLoggingHandler(client=client, name="xyz")
  File "/path/to/venv/lib/python3.5/site-packages/google/cloud/logging/handlers/handlers.py", line 80, in __init__
    self.transport = transport(client, name)
  File "/path/to/venv/lib/python3.5/site-packages/google/cloud/logging/handlers/transports/background_thread.py", line 154, in __init__
    http = client._connection.credentials.authorize(http)
AttributeError: 'Credentials' object has no attribute 'authorize'
```
I test this in a fresh virtualenv whose freeze shows
```
enum34==1.1.6
future==0.16.0
gapic-google-logging-v2==0.10.1
google-auth==0.4.0
google-auth-httplib2==0.0.2
google-cloud-core==0.22.0
google-cloud-logging==0.21.0
google-gax==0.14.1
googleapis-common-protos==1.5.0
grpc-google-logging-v2==0.10.1
grpcio==1.0.1
httplib2==0.9.2
oauth2client==4.0.0
ply==3.8
protobuf==3.1.0.post1
pyasn1==0.1.9
pyasn1-modules==0.0.8
rsa==3.4.2
six==1.10.0
```
 `pip show google-cloud-logging` shows 
```
Name: google-cloud-logging
Version: 0.21.0
Summary: Python Client for Stackdriver Logging
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: jjg+google-cloud-python@google.com
License: Apache 2.0
Location: /path/to/venv/lib/python3.5/site-packages
Requires: google-gax, gapic-google-logging-v2, grpc-google-logging-v2, grpcio, google-cloud-core
```
and `pip show google-cloud-core` shows
```
Name: google-cloud-core
Version: 0.22.0
Summary: API Client library for Google Cloud: Core Helpers
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: jjg+google-cloud-python@google.com
License: Apache 2.0
Location: /path/to/venv/lib/python3.5/site-packages
Requires: protobuf, google-auth-httplib2, six, httplib2, google-auth, googleapis-common-protos
```

I do this test in a blank directory with only the json credentials and the above mentioned script. To run the snippet I do  `GCLOUD_PROJECT=my-project GOOGLE_APPLICATION_CREDENTIALS=my-cred.json python snippet.py`

Could it had something to do with the new version of `google-cloud-core` (0.22.0 published 2016-12-06) ?

Bests,
François.

**Comment by Fkawala** [comment]
To downgrade the `google-cloud-core` to version 0.21.0 solves the problem.

**Comment by jonparrott** [comment]
@dhermes this is why we released 0.21.1, right?

**Comment by dhermes** [comment]
@jonparrott beat me to it @Fkawala. I stupidly relesed `0.21.0` without version upper bounds, so `0.21.1` is the exact same release, except putting upper bounds on the subpackages (and bumping the version for HappyBase, which is also the same code).

#2828 will at least improve the messaging.

**Comment by PLPeeters** [comment]
This issue is present again with version `0.27.0`. Downgrading to `0.26.1` solves the issue.

**Comment by viyh** [comment]
+1

**Comment by william-silversmith** [comment]
FYI it looks like the issue is caused by HAS_GOOGLE_AUTH being False:

```try:
    import google.auth
    import google.auth.credentials
    import google_auth_httplib2
    HAS_GOOGLE_AUTH = True
except ImportError:  # pragma: NO COVER
    HAS_GOOGLE_AUTH = False
```

It can be mitigated by running `pip install google-auth-httplib2`. By the way, the instruction is missing the 'p' in httplib2 on this page: https://pypi.python.org/pypi/google-auth-httplib2
