### ISSUE TITLE
httplib2.sslhandshakerror

### ISSUE THREAD

**Issue by SJonny95** [GoogleCloudPlatform/google-cloud-python#2912]
have tried everything I can find to get this to work...

I'm working on a project for my school with Google Vision Api on Raspberry Pi. The python code is:

```python
import argparse
import base64
import picamera

from googleapiclient import discovery
from oauth2client.client import GoogleCredentials
from googleapiclient.discovery import build

def main():

    """Run a label request on a single image"""

    credentials = GoogleCredentials.get_application_default()
	

    service = build('vision', 'v1', credentials=credentials)

    with open('coca.jpeg', 'rb') as image:
        image_content = base64.b64encode(image.read())
        service_request = service.images().annotate(body={
            'requests': [{
                'image': {
                    'content': image_content.decode('UTF-8')
                },
                'features': [{
                    'type': 'LOGO_DETECTION',
                    'maxResults': 1
                }]
            }]
        })
        response = service_request.execute()
	print response
	print " \n\n"

        try:
             label = response['responses'][0]['logoAnnotations'][0]['description']
        except:
             label = "No response."
        print label
if __name__ == '__main__':
    main()
```

and the problem is:

```
root@raspberrypi:/home/pi# python camera-vision-logo.py 
Traceback (most recent call last):
  File "camera-vision-logo.py", line 56, in <module>
    main()
  File "camera-vision-logo.py", line 27, in main
    service = build('vision', 'v1', credentials=credentials)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 222, in build
    cache)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 269, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1059, in connect
    raise SSLHandshakeError(e)
httplib2.SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
root@raspberrypi:/home/pi# 
```

HOW CAN I SOLVE THIS PROBLEM?? 

Thanks so much for the answers!

**Comment by dhermes** [comment]
@SJonny95 Your code uses a different library than this one, namely `google-api-python-client`.

Please file an issue on their issue tracker: https://github.com/google/google-api-python-client/issues/new

If you don't get a response there, let us know and we can try to help.

FWIW, the most likely problem is that you don't have OpenSSL installed "correctly" on the Raspberry Pi, but I don't know anything about the OS on the Raspberry Pi.

**Comment by dhermes** [comment]
@JustinBeckwith you've got a script that is on a rampage. Mind checking it out? I've so far been assigned over 400 issues.

**Comment by JustinBeckwith** [comment]
Apologies for the noise - this should only be assigning closed issues, so none of it is actionable.  Hopefully done in the next hour or so.
