### ISSUE TITLE
tox -e docs -> ConfigError: substitution key 'posargs' not found

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/google-cloud-python#2955]
Getting this error on Mac OS Python when I run `tox -e docs`. Any ideas?

```python
Traceback (most recent call last):
  File "/usr/local/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/Library/Python/2.7/site-packages/tox/session.py", line 38, in main
    config = prepare(args)
  File "/Library/Python/2.7/site-packages/tox/session.py", line 26, in prepare
    config = parseconfig(args)
  File "/Library/Python/2.7/site-packages/tox/config.py", line 219, in parseconfig
    parseini(config, inipath)
  File "/Library/Python/2.7/site-packages/tox/config.py", line 661, in __init__
    self.make_envconfig(name, section, reader._subs, config)
  File "/Library/Python/2.7/site-packages/tox/config.py", line 689, in make_envconfig
    res = meth(env_attr.name, env_attr.default)
  File "/Library/Python/2.7/site-packages/tox/config.py", line 854, in getargvlist
    return _ArgvlistReader.getargvlist(self, s)
  File "/Library/Python/2.7/site-packages/tox/config.py", line 1003, in getargvlist
    replaced = reader._replace(current_command)
  File "/Library/Python/2.7/site-packages/tox/config.py", line 972, in _replace
    return RE_ITEM_REF.sub(self._replace_match, x)
  File "/Library/Python/2.7/site-packages/tox/config.py", line 968, in _replace_match
    return handler(match)
  File "/Library/Python/2.7/site-packages/tox/config.py", line 938, in _replace_substitution
    val = self._substitute_from_other_section(sub_key)
  File "/Library/Python/2.7/site-packages/tox/config.py", line 927, in _substitute_from_other_section
    return self._replace(x)
  File "/Library/Python/2.7/site-packages/tox/config.py", line 972, in _replace
    return RE_ITEM_REF.sub(self._replace_match, x)
  File "/Library/Python/2.7/site-packages/tox/config.py", line 968, in _replace_match
    return handler(match)
  File "/Library/Python/2.7/site-packages/tox/config.py", line 938, in _replace_substitution
    val = self._substitute_from_other_section(sub_key)
  File "/Library/Python/2.7/site-packages/tox/config.py", line 932, in _substitute_from_other_section
    "substitution key %r not found" % key)
tox.ConfigError: ConfigError: substitution key 'posargs' not found
```

**Comment by dhermes** [comment]
You have an out-of-date version of `tox` is my first guess

**Comment by waprin** [comment]
@dhermes good call, thanks.
