### ISSUE TITLE
pubsub fails with error from gax

### ISSUE THREAD

**Issue by rwillard** [GoogleCloudPlatform/google-cloud-python#2975]
Looks like a recent update to google-gax is broken with pip. https://github.com/googleapis/gax-python/issues/152.

I was getting this error
```
Traceback (most recent call last):
  File "/tracking_sub/worker_sub_pool.py", line 19, in <module>
    from google.cloud import pubsub
  File "/usr/local/lib/python3.4/dist-packages/google/cloud/pubsub/__init__.py", line 27, in <module>
    from google.cloud.pubsub.client import Client
  File "/usr/local/lib/python3.4/dist-packages/google/cloud/pubsub/client.py", line 28, in <module>
    from google.cloud.pubsub._gax import _PublisherAPI as GAXPublisherAPI
  File "/usr/local/lib/python3.4/dist-packages/google/cloud/pubsub/_gax.py", line 19, in <module>
    from google.cloud.gapic.pubsub.v1.publisher_client import PublisherClient
  File "/usr/local/lib/python3.4/dist-packages/google/cloud/gapic/pubsub/v1/publisher_client.py", line 30, in <module>
    from google.gax import api_callable
  File "/usr/local/lib/python3.4/dist-packages/google/gax/__init__.py", line 49, in <module>
    with open('%s%sVERSION' % (CUR_DIR, os.path.sep), 'r') as version_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/VERSION'
```

I'm using version 0.22.0 `google-cloud-pubsub==0.22.0`
I was able to fix this problem by including a previous version of google-gax in my requirements.txt file.  `google-gax==0.15.1`

Could google-cloud-pubsub also use a versioned package of google-gax and other packages to avoid similar problems in the future?

**Comment by rwillard** [comment]
Makes sense, thank you!

**Comment by dhermes** [comment]
Thanks for understanding! (And filing)
