### ISSUE TITLE
AttributeError: 'str' object has no attribute '_credentials'  

### ISSUE THREAD

**Issue by kevmo314** [GoogleCloudPlatform/google-cloud-python#3071]
Hi, I'm trying the example code and it's failing with the following exception:

```
>>> c = error_reporting.Client(project='<my-project-str>')
>>> try:
...   raise NameError
... except Exception:
...   c.report_exception()
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/opt/python/3.6.0/lib/python3.6/site-packages/google/cloud/error_reporting/client.py", line 348, in report_exception
    user=user)
  File "/opt/python/3.6.0/lib/python3.6/site-packages/google/cloud/error_reporting/client.py", line 277, in _send_error_report
    self.report_errors_api.report_error_event(error_report)
  File "/opt/python/3.6.0/lib/python3.6/site-packages/google/cloud/error_reporting/client.py", line 162, in report_errors_api
    self._report_errors_api = make_report_error_api(self._project)
  File "/opt/python/3.6.0/lib/python3.6/site-packages/google/cloud/error_reporting/_gax.py", line 39, in make_report_error_api
    client._credentials,
AttributeError: 'str' object has no attribute '_credentials'
```

Reading the source, this seems like a rather obvious error:

https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/error_reporting/google/cloud/error_reporting/client.py#L162

`self._project` is a string and at https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/error_reporting/google/cloud/error_reporting/_gax.py#L29 it's treated like a client object. Is this not the case?

**Comment by dhermes** [comment]
I would agree, it **does** seem like a rather obvious error. Thanks for reporting! 

In the meantime, you can avoid this by setting `GOOGLE_CLOUD_DISABLE_GRPC=True`, but we'll get a fix out.

**Comment by robhaswell** [comment]
Thanks for catching this. Please can you roll `0.23.1` so we can deploy this fix?

**Comment by daspecster** [comment]
@lukesneeringer I can setup the release for this if you want?

**Comment by lukesneeringer** [comment]
Yes please.

**Comment by daspecster** [comment]
@robhaswell [google-cloud-error-reporting 0.23.1](https://pypi.python.org/pypi/google-cloud-error-reporting/0.23.1) is up on PyPi.

**Comment by robhaswell** [comment]
Wonderful, thank you.
