### ISSUE TITLE
AttributeError when calling storage.bucket.exists

### ISSUE THREAD

**Issue by drzero42** [GoogleCloudPlatform/google-cloud-python#3076]
```
$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import storage
>>> client = storage.Client()
>>> bucket = client.get_bucket("test-bucket")
>>> bucket.exists("testfile.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abo/.local/lib/python3.5/site-packages/google/cloud/storage/bucket.py", line 147, in exists
    client._connection.api_request(
AttributeError: 'str' object has no attribute '_connection'

$ pip3 show google-cloud-storage
---
Metadata-Version: 2.0
Name: google-cloud-storage
Version: 0.22.0
Summary: Python Client for Google Cloud Storage
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: jjg+google-cloud-python@google.com
Installer: pip
License: Apache 2.0
Location: /home/abo/.local/lib/python3.5/site-packages
Requires: google-cloud-core
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  License :: OSI Approved :: Apache Software License
  Operating System :: OS Independent
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Topic :: Internet

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

$ uname -a
Linux bofh42 4.8.0-39-generic #42~16.04.1-Ubuntu SMP Mon Feb 20 15:06:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```

When I use the exists method on a bucket, the above AttributeError is produced. It does not matter if the blob actually exists or not.

**Comment by dhermes** [comment]
@drzero42 Check out the docs for `bucket.exists()`. It takes an optional client and you passed in a string in that place. This method is intended to check if the **bucket** exists. If you want to check if a blob / storage object exists:

```python
>>> blob bucket.blob('testfile.txt')
>>> blob.exists()
True
```

**Comment by drzero42** [comment]
@dhermes Ahh, sorry, my bad. Read the docs wrong. Thank you.
