### ISSUE TITLE
Logging system tests broken

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3078]
https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/205851892#L2768

```python
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/system_tests/logging_.py", line 440, in test_update_sink
    self.assertFalse(sink.exists())
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/.tox/system-tests/lib/python2.7/site-packages/google/cloud/logging/sink.py", line 138, in exists
    client.sinks_api.sink_get(self.project, self.name)
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/.tox/system-tests/lib/python2.7/site-packages/google/cloud/logging/client.py", line 134, in sinks_api
    self._sinks_api = make_gax_sinks_api(self)
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/.tox/system-tests/lib/python2.7/site-packages/google/cloud/logging/_gax.py", line 573, in make_gax_sinks_api
    channel=channel, lib_name='gccl', lib_version=__version__)
TypeError: __init__() got an unexpected keyword argument 'lib_name'
```

Preliminarily assigning to Luke.

**Comment by lukesneeringer** [comment]
Yep, that belongs to me. Thanks.
