### ISSUE TITLE
Speech throwing DistributionNotFound error

### ISSUE THREAD

**Issue by jacobtomlinson** [GoogleCloudPlatform/google-cloud-python#3097]
### OS
`MacOS Sierra`

### Python
`Python 2.7.11`

### pip freeze
```
appdirs==1.4.2
dill==0.2.6
enum34==1.1.6
future==0.16.0
futures==3.0.5
gapic-google-cloud-speech-v1beta1==0.15.2
google-auth==0.8.0
google-auth-httplib2==0.0.2
google-cloud-core==0.23.1
google-cloud-speech==0.23.0
google-gax==0.15.7
googleapis-common-protos==1.5.2
grpcio==1.1.3
httplib2==0.10.3
oauth2client==3.0.0
packaging==16.8
ply==3.8
proto-google-cloud-speech-v1beta1==0.15.1
protobuf==3.2.0
pyasn1==0.2.3
pyasn1-modules==0.0.8
pyparsing==2.1.10
rsa==3.4.2
six==1.10.0
```

### Stacktrace
```bash
$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 53, in <module>
    run_quickstart()
  File "quickstart.py", line 45, in run_quickstart
    alternatives = speech_client.speech_api.sync_recognize(audio_sample)
  File "/private/tmp/speech/venv/lib/python2.7/site-packages/google/cloud/speech/client.py", line 108, in speech_api
    self._speech_api = GAPICSpeechAPI(self)
  File "/private/tmp/speech/venv/lib/python2.7/site-packages/google/cloud/speech/_gax.py", line 52, in __init__
    lib_version=__version__,
  File "/private/tmp/speech/venv/lib/python2.7/site-packages/google/cloud/gapic/speech/v1beta1/speech_client.py", line 156, in __init__
    app_version=app_version)
  File "/private/tmp/speech/venv/lib/python2.7/site-packages/google/gapic/longrunning/operations_client.py", line 155, in __init__
    'gapic-google-longrunning-v1', ).version
  File "/private/tmp/speech/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 552, in get_distribution
    dist = get_provider(dist)
  File "/private/tmp/speech/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 426, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/private/tmp/speech/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/private/tmp/speech/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gapic-google-longrunning-v1' distribution was not found and is required by the application
```
### Steps to reproduce

```bash
# Setup new environment
mkdir /tmp/speech && cd /tmp/speech
virtualenv venv && source venv/bin/activate

# Install cloud speech
pip install google-cloud-speech==0.23.0

# Get example script and audio resource from GoogleCloudPlatform/python-docs-samples
curl https://raw.githubusercontent.com/GoogleCloudPlatform/python-docs-samples/master/speech/cloud-client/quickstart.py > quickstart.py
mkdir resources && curl https://github.com/GoogleCloudPlatform/python-docs-samples/raw/master/speech/cloud-client/resources/audio.raw > resources/audio.raw

# Run the script
python quickstart.py
```

**Comment by dhermes** [comment]
It definitely doesn't exist: https://pypi.python.org/pypi/gapic-google-longrunning-v1

This package does: https://pypi.python.org/pypi/gapic-google-longrunning

Now this error [is in `google-gax`][1]?

/cc @lukesneeringer 

[1]: https://github.com/googleapis/gax-python/blob/56210906ca979c1b768c535c5c2f64e490d5530e/google/gapic/longrunning/operations_client.py#L153-L155

**Comment by tseaver** [comment]
https://github.com/googleapis/gax-python/issues/170

**Comment by lukesneeringer** [comment]
Fixing. That is an autogen problem.

**Comment by lukesneeringer** [comment]
Will be fixed as soon as https://github.com/googleapis/gax-python/issues/171 is approved and passes CI (if either of you want to give it a once-over, I would appreciate it).

**Comment by lukesneeringer** [comment]
I also added googleapis/gax-python#172 so that we fix our automated testing to catch this sort of thing.

**Comment by frankyn** [comment]
@lukesneeringer is there a workaround while the PRs are in flight?

**Comment by lukesneeringer** [comment]
@frankyn I actually already pushed a `google-gax==0.15.8` to PyPI (since I acknowledge that it is Saturday and the review process will be slow, and it broke an entire library).

**Comment by frankyn** [comment]
Thanks @lukesneeringer !

I have a student stuck on this issue. Should the student be okay with running the following?

`pip install --upgrade google-cloud-speech`

**Comment by lukesneeringer** [comment]
I cannot remember for sure if `--upgrade google-cloud-speech` will implicitly update every dependency, and the gax version is still pinned at `>= 0.15.6` right now.

You can try it. If it does not work, do the command I gave above.

**Comment by frankyn** [comment]
Ah, I didn't see that. Thanks @lukesneeringer!

**Comment by lukesneeringer** [comment]
@jacobtomlinson Can you confirm that you are unblocked? If so, I will close this.

**Comment by jacobtomlinson** [comment]
@lukesneeringer Yep! That's great thanks.
