### ISSUE TITLE
Spanner system tests failing

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/google-cloud-python#3162]
Running the tests locally with `GOOGLE_CLOUD_TESTS_CREATE_SPANNER_INSTANCE=True`, the tests pass.

I think it's something with the configuration of travis or the setup.

```
======================================================================
ERROR: setUpModule (spanner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/system_tests/spanner.py", line 85, in setUpModule
    created_op = Config.INSTANCE.create()
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/.tox/system-tests/lib/python2.7/site-packages/google/cloud/spanner/instance.py", line 224, in create
    options=options,
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/.tox/system-tests/lib/python2.7/site-packages/google/cloud/gapic/spanner_admin_instance/v1/instance_admin_client.py", line 564, in create_instance
    self._create_instance(request, options), self.operations_client,
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/.tox/system-tests/lib/python2.7/site-packages/google/gax/api_callable.py", line 419, in inner
    return api_caller(api_call, this_settings, request)
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/.tox/system-tests/lib/python2.7/site-packages/google/gax/api_callable.py", line 407, in base_caller
    return api_call(*args)
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/.tox/system-tests/lib/python2.7/site-packages/google/gax/api_callable.py", line 368, in inner
    return a_func(*args, **kwargs)
  File "/home/travis/build/GoogleCloudPlatform/google-cloud-python/.tox/system-tests/lib/python2.7/site-packages/google/gax/retry.py", line 126, in inner
    ' classified as transient', exception)
RetryError: GaxError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Invalid CreateInstance request.)>)
```

See: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/211892379#L2442

@tseaver do you have access to the project(maybe I do too and don't know it?) to recreate the instance or check that it exists?

**Comment by lukesneeringer** [comment]
@daspecster Set the `GOOGLE_CLOUD_TESTS_CREATE_SPANNER_INSTANCE` on your system to `true`. Do they still fail?

Note: The tests are [working on CircleCI on the CI branch][1]. Given that I am hoping to merge that in later today, it will supercede this.

  [1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1256

**Comment by daspecster** [comment]
@lukesneeringer they do pass for me.

I haven't been able to reproduce the failure locally.

**Comment by nilleb** [comment]
I reproduce this issue using 
`google-cloud-spanner-0.23.1 gapic-google-cloud-spanner-admin-database-v1-0.15.3 gapic-google-cloud-spanner-admin-instance-v1-0.15.3 gapic-google-cloud-spanner-v1-0.15.3 proto-google-cloud-spanner-admin-instance-v1-0.15.3 proto-google-cloud-spanner-v1-0.15.3`

**Comment by lukesneeringer** [comment]
@nilleb What is the specific failure you are getting?

**Comment by nilleb** [comment]
@lukesneeringer all the instance creations I've tried to complete yesterday were failing with a StatusCode.INVALID_ARGUMENT. This is the reason for which I've found this issue via a simple Google search.

**Comment by lukesneeringer** [comment]
Can you provide a traceback?
