### ISSUE TITLE
Installing from clean Python fails on 'packaging.version' dependency

### ISSUE THREAD

**Issue by BrandonY** [GoogleCloudPlatform/google-cloud-python#3200]
1. OS type and version: Ubuntu
2. Python version and virtual environment information: Python 2.7.6
3. google-cloud-python version: 0.23.0
4. Stacktrace if available

```
>   Running setup.py install for proto-google-cloud-datastore-v1
>     Skipping installation of /usr/local/google/home/yarbrough/venv3/venv3/lib/python2.7/site-packages/google/__init__.py (namespace package)
>     Skipping installation of /usr/local/google/home/yarbrough/venv3/venv3/lib/python2.7/site-packages/google/cloud/__init__.py (namespace package)
>     Skipping installation of /usr/local/google/home/yarbrough/venv3/venv3/lib/python2.7/site-packages/google/cloud/proto/__init__.py (namespace package)
>     Skipping installation of /usr/local/google/home/yarbrough/venv3/venv3/lib/python2.7/site-packages/google/cloud/proto/datastore/__init__.py (namespace package)
>     
>     warning: no previously-included files matching '*.py[co]' found anywhere in distribution
>     warning: no previously-included files matching '__pycache__' found anywhere in distribution
>     Installing /usr/local/google/home/yarbrough/venv3/venv3/lib/python2.7/site-packages/proto_google_cloud_datastore_v1-0.90.3-py2.7-nspkg.pth
>   Found existing installation: setuptools 3.6
>     Uninstalling setuptools:
>       Successfully uninstalled setuptools
>   Running setup.py install for dill
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/usr/local/buildtools/current/sitecustomize/sitecustomize.py", line 152, in SetupPathsAndImport
>         return real_import(name, globals, locals, fromlist, level)
>       File "/usr/local/google/home/yarbrough/venv3/venv3/local/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
>         import setuptools.version
>       File "/usr/local/google/home/yarbrough/venv3/venv3/local/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
>         import pkg_resources
>       File "/usr/local/google/home/yarbrough/venv3/venv3/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 70, in <module>
>         import packaging.version
>     ImportError: No module named packaging.version
>     Complete output from command /usr/local/google/home/yarbrough/venv3/venv3/bin/python -c "import setuptools, tokenize;__file__='/usr/local/google/home/yarbrough/venv3/venv3/build/dill/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-anVbwa-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/google/home/yarbrough/venv3/venv3/include/site/python2.7:
>     Traceback (most recent call last):
> 
>   File "<string>", line 1, in <module>
> 
>   File "/usr/local/buildtools/current/sitecustomize/sitecustomize.py", line 152, in SetupPathsAndImport
> 
>     return real_import(name, globals, locals, fromlist, level)
> 
>   File "/usr/local/google/home/yarbrough/venv3/venv3/local/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
> 
>     import setuptools.version
> 
>   File "/usr/local/google/home/yarbrough/venv3/venv3/local/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
> 
>     import pkg_resources
> 
>   File "/usr/local/google/home/yarbrough/venv3/venv3/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 70, in <module>
> 
>     import packaging.version
> 
> ImportError: No module named packaging.version
> 
> ----------------------------------------
> Cleaning up...
> Command /usr/local/google/home/yarbrough/venv3/venv3/bin/python -c "import setuptools, tokenize;__file__='/usr/local/google/home/yarbrough/venv3/venv3/build/dill/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-anVbwa-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/google/home/yarbrough/venv3/venv3/include/site/python2.7 failed with error code 1 in /usr/local/google/home/yarbrough/venv3/venv3/build/dill
> Traceback (most recent call last):
>   File "/usr/local/google/home/yarbrough/venv3/venv3/bin/pip", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/google/home/yarbrough/venv3/venv3/local/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
>     return command.main(cmd_args)
>   File "/usr/local/google/home/yarbrough/venv3/venv3/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
>     text = '\n'.join(complete_log)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)
```

5. Steps to reproduce

    1. Create a brand new venv environment.
    2. Run "pip install --upgrade google-cloud"

You can fix this error by separately installing the packaging and the appdirs packages, so I assume they are simply missing dependencies.

**Comment by jonparrott** [comment]
@BrandonY can you give me the output of `pip --version` and `pip freeze | grep setuptools`?

**Comment by daspecster** [comment]
@BrandonY thanks for reporting!

I'm attempting to reproduce now.

**Comment by BrandonY** [comment]
I created a new virtualenv and tried again. Same issue for me.

$> pip --version
pip 1.5.6 from /homedir/venv3/local/lib/python2.7/site-packages (python 2.7)
$> pip freeze | grep setuptools
(No output)

I created another virtualenv and installed packaging and appdirs, then installed google-cloud, and that time I was completely successful.

**Comment by jonparrott** [comment]
pip 1.5.6 is pretty ancient. I suspect you'll have no issues with a newer pip.

**Comment by lukesneeringer** [comment]
Concur. Try upgrading pip (it is on [9.0.1][] now).
I am closing this issue, but please feel free to re-open if that does not fix your problem.

  [9.0.1]: https://pypi.python.org/pypi/pip/9.0.1
