### ISSUE TITLE
KeyError: 'list_logs' for Google Cloud Logging

### ISSUE THREAD

**Issue by sparkline-paolo** [GoogleCloudPlatform/google-cloud-python#3251]
After updating to the latest pips, I am now encountering this keyerror when using google-cloud logging.  Any thoughts?

```
$ pip show google-cloud
Name: google-cloud
Version: 0.23.0
Summary: API Client library for Google Cloud
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: jjg+google-cloud-python@google.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: google-cloud-resource-manager, google-cloud-storage, google-cloud-monitoring, google-cloud-bigtable, google-cloud-language, google-cloud-vision, google-cloud-bigquery, google-cloud-runtimeconfig, google-cloud-logging, google-cloud-translate, google-cloud-core, google-cloud-datastore, google-cloud-speech, google-cloud-spanner, google-cloud-error-reporting, google-cloud-dns, google-cloud-pubsub
```

Code example
```
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import logging
>>> project = 'test'
>>> keyfile = 'keyfile.json'
>>> loggingclient = logging.Client.from_service_account_json(keyfile, project)
>>> logger = loggingclient.logger("Test")
>>> logger.log_text("test log")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/logger.py", line 202, in log_text
    client.logging_api.write_entries([entry_resource])
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/client.py", line 120, in logging_api
    self._logging_api = make_gax_logging_api(self)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/_gax.py", line 539, in make_gax_logging_api
    channel=channel, lib_name='gccl', lib_version=__version__)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/gapic/logging/v2/logging_service_v2_client.py", line 234, in __init__
    settings=defaults['list_logs'])
KeyError: 'list_logs'
```

**Comment by lukesneeringer** [comment]
Thanks for reporting! We will look into this.

**Comment by dhermes** [comment]
@waprin Any ideas?

**Comment by sparkline-paolo** [comment]
so I reinstalled everything from scratch and I can't reproduce this error anymore. feel free to close this issue guys

**Comment by waprin** [comment]
Yeah I had no ideas btw, sorry.
