### ISSUE TITLE
Authentication hangs with no error message for vision API example

### ISSUE THREAD

**Issue by benjamin-fenker-tessella** [GoogleCloudPlatform/google-cloud-python#3252]
The vision API example [here](https://cloud.google.com/vision/docs/fulltext-annotations#importing_libraries) appears to fail during authentication without reporting an error message. Note that `GOOGLE_APPLICATION_CREDENTIALS` does point to a JSON key (although I don't claim infallibility on this). 

```
$ python doctext.py receipt.jpg -out_file out.jpg
^CTraceback (most recent call last):
  File "doctext.py", line 88, in <module>
    render_doc_text(args.detect_file, args.out_file)
  File "doctext.py", line 68, in render_doc_text
    bounds = get_document_bounds(filein, FeatureType.PAGE)
  File "doctext.py", line 40, in get_document_bounds
    document = image.detect_full_text()
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/cloud/vision/image.py", line 195, in detect_full_text
    annotations = self.detect(features)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/cloud/vision/image.py", line 143, in detect
    return self._detect_annotation(images)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/cloud/vision/image.py", line 117, in _detect_annotation
    return self.client._vision_api.annotate(images)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/cloud/vision/_gax.py", line 69, in annotate
    responses = annotator_client.batch_annotate_images(requests).responses
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/cloud/gapic/vision/v1/image_annotator_client.py", line 181, in batch_annotate_images
    return self._batch_annotate_images(request, options)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/gax/api_callable.py", line 419, in inner
    return api_caller(api_call, this_settings, request)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/gax/api_callable.py", line 407, in base_caller
    return api_call(*args)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/gax/api_callable.py", line 368, in inner
    return a_func(*args, **kwargs)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/gax/retry.py", line 120, in inner
    return to_call(*args)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/gax/retry.py", line 68, in inner
    return a_func(*updated_args, **kwargs)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/grpc/_channel.py", line 506, in __call__
    credentials)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/grpc/_channel.py", line 500, in _blocking
    _handle_event(completion_queue.poll(), state,
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 114, in grpc._cython.cygrpc.CompletionQueue.poll (src/python/grpcio/grpc/_cython/cygrpc.c:10475)
KeyboardInterrupt

Ubuntu
`python` is version `3.4.3`
`google-cloud` is version `0.23.0`
`google-cloud-vision` is version `0.23.3`
```

**Comment by lukesneeringer** [comment]
Hi @benjamin-fenker-tessella. Thanks for reporting.

We will look into this. Even if your authentication file is not correct, it should not _hang_. :-)

**Comment by benjamin-fenker-tessella** [comment]
Well it did eventually time out with this error, which maybe helps more:

Traceback (most recent call last):
  File "doctext.py", line 88, in <module>
    render_doc_text(args.detect_file, args.out_file)
  File "doctext.py", line 68, in render_doc_text
    bounds = get_document_bounds(filein, FeatureType.PAGE)
  File "doctext.py", line 40, in get_document_bounds
    document = image.detect_full_text()
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/cloud/vision/image.py", line 195, in detect_full_text
    annotations = self.detect(features)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/cloud/vision/image.py", line 143, in detect
    return self._detect_annotation(images)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/cloud/vision/image.py", line 117, in _detect_annotation
    return self.client._vision_api.annotate(images)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/cloud/vision/_gax.py", line 69, in annotate
    responses = annotator_client.batch_annotate_images(requests).responses
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/cloud/gapic/vision/v1/image_annotator_client.py", line 181, in batch_annotate_images
    return self._batch_annotate_images(request, options)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/gax/api_callable.py", line 419, in inner
    return api_caller(api_call, this_settings, request)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/gax/api_callable.py", line 407, in base_caller
    return api_call(*args)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/gax/api_callable.py", line 368, in inner
    return a_func(*args, **kwargs)
  File "/home/fenkb/google-vision/lib/python3.4/site-packages/google/gax/retry.py", line 143, in inner
    raise exc
google.gax.errors.RetryError: GaxError(Retry total timeout exceeded with exception, caused by <_Rendezvous of RPC that terminated with (StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded)>)

**Comment by lukesneeringer** [comment]
It does, thank you.

**Comment by lukesneeringer** [comment]
Can you still give us the full `pip freeze`?

**Comment by benjamin-fenker-tessella** [comment]
Sure!

appdirs==1.4.3
cachetools==2.0.0
Cython==0.25.2
decorator==4.0.11
dill==0.2.6
enum34==1.1.6
future==0.16.0
gapic-google-cloud-datastore-v1==0.15.3
gapic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3
gapic-google-cloud-pubsub-v1==0.15.3
gapic-google-cloud-spanner-admin-database-v1==0.15.3
gapic-google-cloud-spanner-admin-instance-v1==0.15.3
gapic-google-cloud-spanner-v1==0.15.3
gapic-google-cloud-speech-v1beta1==0.15.3
gapic-google-cloud-vision-v1==0.90.3
google-auth==0.10.0
google-auth-httplib2==0.0.2
google-cloud==0.23.0
google-cloud-bigquery==0.23.0
google-cloud-bigtable==0.23.1
google-cloud-core==0.23.1
google-cloud-datastore==0.23.0
google-cloud-dns==0.23.0
google-cloud-error-reporting==0.23.2
google-cloud-language==0.23.1
google-cloud-logging==0.23.1
google-cloud-monitoring==0.23.0
google-cloud-pubsub==0.23.0
google-cloud-resource-manager==0.23.0
google-cloud-runtimeconfig==0.23.0
google-cloud-spanner==0.23.1
google-cloud-speech==0.23.0
google-cloud-storage==0.23.1
google-cloud-translate==0.23.0
google-cloud-vision==0.23.3
google-gax==0.15.8
googleapis-common-protos==1.5.2
grpc-google-iam-v1==0.11.1
grpcio==1.2.1
httplib2==0.10.3
ipython==5.3.0
ipython-genutils==0.2.0
oauth2client==3.0.0
olefile==0.44
packaging==16.8
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.0.0
ply==3.8
prompt-toolkit==1.0.14
proto-google-cloud-datastore-v1==0.90.3
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3
proto-google-cloud-pubsub-v1==0.15.3
proto-google-cloud-spanner-admin-database-v1==0.15.3
proto-google-cloud-spanner-admin-instance-v1==0.15.3
proto-google-cloud-spanner-v1==0.15.3
proto-google-cloud-speech-v1beta1==0.15.3
proto-google-cloud-vision-v1==0.90.3
protobuf==3.2.0
ptyprocess==0.5.1
pyasn1==0.2.3
pyasn1-modules==0.0.8
Pygments==2.2.0
pyparsing==2.2.0
rsa==3.4.2
simplegeneric==0.8.1
six==1.10.0
traitlets==4.3.2
wcwidth==0.1.7

**Comment by lukesneeringer** [comment]
Thanks!

**Comment by benjamin-fenker-tessella** [comment]
This issue is unchanged after installing `google-cloud-core==0.24.0` and `google-cloud-vision==0.24.0`.

**Comment by jonparrott** [comment]
@benjamin-fenker-tessella is this still occurring with grpcio 1.3.0?

**Comment by pradeepsharma2004** [comment]
The error is still not resolved..same error is encountered when i run the code!!

**Comment by alexiskattan** [comment]
any update on this? Same problem.  It hangs with `vision.Client()`

**Comment by dhermes** [comment]
@alexiskattan Which version of `grpcio` are you using? Are you using `gunicorn`?

**Comment by alexiskattan** [comment]
grpcio==1.4.0

**Comment by lukesneeringer** [comment]
Note that there is now a _completely different_ `google-cloud-vision`. Is anyone getting this error while using `ImageAnnotatorClient`?

**Comment by lukesneeringer** [comment]
Actually, closing this, since it seems unlikely the issue will persist into the new client. Feel free to reopen if I am wrong. :-)
