### ISSUE TITLE
AttributeError: '_JWTAccessCredentials' object has no attribute 'before_request' trying to use google.auth.iam.Signer

### ISSUE THREAD

**Issue by cva** [GoogleCloudPlatform/google-cloud-python#3281]
Trying to figure out how to use `google.auth.iam.Signer` to make signed URLs for cloud storage but stuck on what kind of credentials it wants. My understanding was I could use the app's default credentials for the call to iam.

1. OS type and version

Linux (appengine flexible python runtime) 

2. Python version and virtual environment information `python --version`

Python 3.5.2

3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`

```
# pip freeze | grep google-cloud
gapic-google-cloud-datastore-v1==0.15.3
gapic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3
gapic-google-cloud-speech-v1beta1==0.15.3
google-cloud-core==0.23.1
google-cloud-datastore==0.23.0
google-cloud-error-reporting==0.23.2
google-cloud-logging==0.23.1
google-cloud-speech==0.23.0
google-cloud-storage==0.23.1
proto-google-cloud-datastore-v1==0.90.3
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3
proto-google-cloud-speech-v1beta1==0.15.3
```

4. Stacktrace if available

```
Traceback (most recent call last):
  File "/env/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/env/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/env/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/env/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/env/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vmagent/app/fbcolors/api.py", line 332, in sign_test
    return get_signed_url('/recordings/test.wav', 100000000)
  File "/home/vmagent/app/fbcolors/api.py", line 381, in get_signed_url
    signature = signer.sign(to_sign)
  File "/env/lib/python3.5/site-packages/google/auth/iam.py", line 101, in sign
    response = self._make_signing_request(message)
  File "/env/lib/python3.5/site-packages/google/auth/iam.py", line 78, in _make_signing_request
    self._credentials.before_request(self._request, method, url, headers)
AttributeError: '_JWTAccessCredentials' object has no attribute 'before_request'
```

5. Steps to reproduce

(see code example)

6. Code example

```python
    google_access_storage_id = 'name@project-id.iam.gserviceaccount.com'

    from oauth2client.client import GoogleCredentials
    credentials = GoogleCredentials.get_application_default()

    import google.auth.transport.requests
    session = google.auth.transport.requests.AuthorizedSession(credentials)

    request = google.auth.transport.requests.Request(session)
    credentials.refresh(request)

    import google.auth.iam
    signer = google.auth.iam.Signer(
        request,
        credentials,
        google_access_storage_id)
    signature = signer.sign(to_sign)

```

Using GitHub flavored markdown can help make your request clearer.
See: https://guides.github.com/features/mastering-markdown/

**Comment by jonparrott** [comment]
oauth2client is soon to be deprecated, please use credentials from google-auth itself:

```python
    import google.auth
    credentials, project_id = google.auth.default()

    if not isinstance(credentials, google.auth.credentials.Signing):
        raise ValueError('Given credentials can not sign bytes')

    signer = credentials.signer
    signature = signer.sign(...)
   
    # Alternatively:
 
    signature = credentials.sign_bytes(...)
```

Also, the Cloud Storage client in this repository has a helper for generated signed urls: https://google-cloud-python.readthedocs.io/en/latest/storage-blobs.html#google.cloud.storage.blob.Blob.generate_signed_url

**Comment by cva** [comment]
Thanks, that worked.

**Comment by cva** [comment]
In case anyone runs across this later and also trying to use iam signBlob, here's a snippet of what ended up working:

```python
    import google.auth
    credentials, project_id = google.auth.default(
        scopes=['https://www.googleapis.com/auth/iam'])

    import google.auth.transport.requests
    request = google.auth.transport.requests.Request()
    credentials.refresh(request)

    import google.auth.iam
    signer = google.auth.iam.Signer(
        request,
        credentials,
        credentials.service_account_email)

    signature = signer.sign(to_sign)
```

**Comment by brentshermana** [comment]
Google should get with it and update their documentation. oauth failed for me as well, but this works like a charm! Thanks.
