### ISSUE TITLE
Calling run_in_transaction twice causes the second call to fail

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-python#3434]
It seems that the `_transaction` object in Session is not being reset once the transaction commits. This leads to a "Transaction is already committed" error. Here is a simple code to demonstrate this:

```python
def run_txn():
    from google.cloud import spanner
    spanner_client = spanner.Client()
    instance_id = 'your-instance'
    instance = spanner_client.instance(instance_id)
    database_id = 'example-db'
    database = instance.database(database_id)
    def f(t):
      t.insert_or_update(
          table="Singers",
          columns=('SingerId', 'FirstName'),
          values = [(6, "A"),])
    database.run_in_transaction(f)
    database.run_in_transaction(f)

if __name__ == '__main__':
    run_txn()

```

The error that is raised is:

```python
Traceback (most recent call last):
  File "txn.py", line 17, in <module>
    run_txn()
  File "txn.py", line 14, in run_txn
    database.run_in_transaction(f)
  File "/usr/local/google/home/vikask/venvs/pythonq/local/lib/python2.7/site-packages/google/cloud/spanner/database.py", line 379, in run_in_transaction
    return session.run_in_transaction(func, *args, **kw)
  File "/usr/local/google/home/vikask/venvs/pythonq/local/lib/python2.7/site-packages/google/cloud/spanner/session.py", line 309, in run_in_transaction
    txn.commit()
  File "/usr/local/google/home/vikask/venvs/pythonq/local/lib/python2.7/site-packages/google/cloud/spanner/transaction.py", line 104, in commit
    self._check_state()
  File "/usr/local/google/home/vikask/venvs/pythonq/local/lib/python2.7/site-packages/google/cloud/spanner/transaction.py", line 46, in _check_state
    raise ValueError("Transaction is already committed")
ValueError: Transaction is already committed
```

**Comment by vkedia** [comment]
The version of google-cloud-spanner I used was 0.24.1

**Comment by tseaver** [comment]
Fix released:

- https://github.com/GoogleCloudPlatform/google-cloud-python/releases/tag/spanner-0.24.2
- https://pypi.python.org/pypi/google-cloud-spanner/0.24.2
