### ISSUE TITLE
AttributeError: can't set attribute during EVERY put(), get() and fetch() operation

### ISSUE THREAD

**Issue by jzzfs** [GoogleCloudPlatform/google-cloud-python#3575]
## Problem
Both on localhost and in production, essentially every `ext.db` operation fails.

## Local Environment Specs
OS X El Capital 10.11.3
Platform:
- [Mac OS X, x86_64]
- 'Darwin'
- 'XYZ-MacBook-Pro.local'
- '15.3.0',
- 'Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64', 'x86_64', 'i386'
Python Verdion:
- [2.7.13 (default, Dec 17 2016, 23:03:43)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]]

Selected gcloud components:
- core: [2017.06.02]
- app-engine-python: [1.9.54]
- gcloud sdk 159.0.0

## Example Trivial Put Request
```
class RealEstateProperty(db.Model):
    owner = db.ReferenceProperty(User, required=True, collection_name='props')
    can_be_indexed = db.BooleanProperty()
    ... # no other `required` properties

garage = RealEstateProperty(owner=self.user, can_be_indexed=False)
garage.put()
```

## Error Log
```
ERROR    2017-07-01 17:06:27,192 wsgi.py:279]
Traceback (most recent call last):
  File "/Users/jay/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/Users/jay/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "/Users/jay/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/jay/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/jay/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/jay/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/Users/jay/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Users/jay/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/Users/jay/Desktop/mng/mng.py", line 3401, in get
    garage = RealEstateProperty(owner=self.user)
  File "/Users/jay/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/ext/db/__init__.py", line 973, in __init__
    prop.__set__(self, value)
  File "/Users/jay/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/ext/db/__init__.py", line 618, in __set__
    setattr(model_instance, self._attr_name(), value)
AttributeError: can't set attribute
```

What's worse, in the live environment, not only do new entities **FAIL** to be created, but also **NO** existing datastore entity can be fetched without the setter messing up my day.

## Production get() Request Log
```
AttributeError: can't set attribute
at __set__ (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py:618)
at __init__ (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py:973)
at from_entity (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py:1445)
at extra_hook (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py:1510)
at local_extra_hook (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py:643)
at __get_hook (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py:1729)
at get_result (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py:613)
at get (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py:1540)

at get (/base/data/home/apps/e~APP_ID/17.402363937185965808/mng.py:4179)

at dispatch (/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py:545)
at dispatch (/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py:547)
at __call__ (/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py:1077)
at default_dispatcher (/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py:1253)
at __call__ (/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py:1505)
at __call__ (/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py:1511)
at __call__ (/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py:1519)
at Handle (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py:267)
```

No issue of this scope has happened since 1 year of my usage of DB. It appears to be linked to upgrading my cloud SDK to `160.0.0` earlier today, but after rollback to `159.0.0`, not much has changed.

I'd be happy to provide more context, if needed.

A product launch depends on this so please let me know if there is an immediate fix.
Thank you!

**Comment by jzzfs** [comment]
# FIXED ✔

Nevermind! The cause of the problem was my addition of a `@property` whose name started with an underscore, thereby messing up the setter.

**Comment by tseaver** [comment]
I'm glad you found your bug.  Note for future reference that this repository is for the `google-cloud-python` libraries, not for the [gcloud sdk](https://cloud.google.com/sdk) / GAE.
