### ISSUE TITLE
pip install failing

### ISSUE THREAD

**Issue by VikramTiwari** [GoogleCloudPlatform/google-cloud-python#3581]
1. OS type and version: macOS Sierra v10.12.5
2. Python version and virtual environment information `python --version`: 3.6.1
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`: Nothing
4. Stacktrace if available: added
5. Steps to reproduce: Try installing it with Python 3.
6. Code example: None

Logs:
``` bash
Collecting gapic-google-cloud-datastore-v1<0.16dev,>=0.15.0 (from google-cloud-datastore<2.0dev,>=1.1.0->google-cloud)
  Using cached gapic-google-cloud-datastore-v1-0.15.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/Vikram/pyenv/py3/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
      File "/Users/Vikram/pyenv/py3/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/Users/Vikram/pyenv/py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
        @_call_aside
      File "/Users/Vikram/pyenv/py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "/Users/Vikram/pyenv/py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3045, in _initialize_master_working_set
        dist.activate(replace=False)
      File "/Users/Vikram/pyenv/py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2577, in activate
        declare_namespace(pkg)
      File "/Users/Vikram/pyenv/py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2151, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/Users/Vikram/pyenv/py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2091, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/Users/Vikram/pyenv/py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_f/95xpdnrx4yncxz91dt53mvfh0000gn/T/pip-build-vct6bb1z/gapic-google-cloud-datastore-v1/

```

**Comment by dhermes** [comment]
@VikramTiwari Thanks for taking the time to file this issue!

This is a common issue with out of date versions of `pip` / `setuptools`. You should update those tools.

**Comment by VikramTiwari** [comment]
That was easy. Thanks. 👍

**Comment by dhermes** [comment]
Cheers!

**Comment by dhermes** [comment]
For anyone who comes here, see #2990.
