### ISSUE TITLE
'ReadOptions' object is not iterable when trying a get a entity Google Cloud Datastore

### ISSUE THREAD

**Issue by RoneyThomas** [GoogleCloudPlatform/google-cloud-python#3589]
1. OS type and version
macOS Sierra 10.12.5
2. Python version and virtual environment information `python --version`
Python 3.6.1
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
google-cloud-datastore==1.1.0
4) Code sample 

```python
ds = datastore.Client(project='project-name')
# First, create a fake email for our fake user
email = "me@fake.com"
# Now, create a 'key' for that user using the email
user_key = ds.key('User', email)
print(user_key)
<Key('User', 'me@fake.com'), project = church - tools>
new_user = datastore.Entity(key=user_key)
print(new_user)
<Entity('User', 'me@fake.com') {}>
new_user["name"] = "Roney Thomas"
new_user["email"] = "roneythomas6@gmail.com"
print(new_user)
<Entity('User', 'me@fake.com') {'name': 'Roney Thomas', 'email': 'roneythomas6@gmail.com'}>
ds.put(new_user)
#This where things fall apart
print(ds.get(user_key))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/roneythomas/code/foo.github.io/admin/venv/lib/python3.6/site-packages/google/cloud/datastore/client.py", line 309, in get
    deferred=deferred, transaction=transaction)
  File "/Users/roneythomas/code/foo.github.io/admin/venv/lib/python3.6/site-packages/google/cloud/datastore/client.py", line 356, in get_multi
    transaction_id=transaction and transaction.id,
  File "/Users/roneythomas/code/foo.github.io/admin/venv/lib/python3.6/site-packages/google/cloud/datastore/client.py", line 138, in _extended_lookup
    project, read_options, key_pbs)
  File "/Users/roneythomas/code/foo.github.io/admin/venv/lib/python3.6/site-packages/google/cloud/datastore/_gax.py", line 115, in lookup
    return super(GAPICDatastoreAPI, self).lookup(*args, **kwargs)
  File "/Users/roneythomas/code/foo.github.io/admin/venv/lib/python3.6/site-packages/google/cloud/gapic/datastore/v1/datastore_client.py", line 199, in lookup
    project_id=project_id, keys=keys, read_options=read_options)
  File "/Users/roneythomas/code/foo.github.io/admin/venv/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 500, in init
    for val in field_value:
TypeError: 'ReadOptions' object is not iterable
```

**Comment by tseaver** [comment]
Thanks for the report!  Unfortunately, I cannot reproduce it:

```bash
$ pip freeze | grep google-cloud
gapic-google-cloud-datastore-v1==0.15.3
google-cloud-core==0.25.0
google-cloud-datastore==1.1.0
google-cloud-testutils==0.24.0
proto-google-cloud-datastore-v1==0.90.4
$ python
```

```python
>>> from google.cloud import datastore
>>> client = datastore.Client()
>>> key = client.key('User', 'user@example.com')
>>> entity = datastore.Entity(key=key)
>>> entity['name'] = 'Fake User'
>>> entity['email'] = 'user@example.com'
>>> entity
<Entity('User', 'user@example.com') {'name': 'Fake User', 'email': 'user@example.com'}>
>>> client.put(entity)
>>> client.get(key)
<Entity(u'User', u'user@example.com') {u'email': 'user@example.com', u'name': 'Fake User'}>
```

**Comment by RoneyThomas** [comment]
Reinstalling dependencies fixed my issue. Please close this.

**Comment by tseaver** [comment]
@RoneyThomas thank you for following up!
