### ISSUE TITLE
google-cloud-datastore: Import fails with latest setuptools 36.2.1

### ISSUE THREAD

**Issue by evanj** [GoogleCloudPlatform/google-cloud-python#3656]
Creating a new virtualenv that uses the latest version of setuptools fails to correctly install google-cloud-datastore. Using it will fail with `ImportError: No module named proto.datastore.v1`. The reason seems to be that the package `gapic-google-cloud-datastore-v1` depends on `proto-google-cloud-datastore-v1[grpc]<0.91dev,>=0.90.3`. I believe the `[grpc]` part causes the new versions of setuptools to consider this an "extra" dependency and not include it.

The workaround is to explicitly install this package in `requirements.txt`, but either `google-cloud-datastore` or `gapic-google-cloud-datastore-v1` should have its dependencies fixed so this works

# Reproducing the issue

On a clean Debian machine, create a new virtualenv. This will have an old version of pip and setuptools, so then install the latest versions. Then install google-cloud-datastore, and try and use it. The output looks as follows:

```
evan_jones@ejones-disposable-testing:~$ virtualenv bug
Running virtualenv with interpreter /usr/bin/python2
New python executable in bug/bin/python2
Also creating executable in bug/bin/python
Installing setuptools, pip...done.
evan_jones@ejones-disposable-testing:~$ bug/bin/pip install --upgrade pip setuptools
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Downloading/unpacking setuptools from https://pypi.python.org/packages/54/78/55b06e9c83fe661bd7554ce8b2620c253cba25df36ae402ba184df980ec0/setuptools-36.2.1-py2.py3-none-any.whl#md5=bba068517e5baeb86d3b78a03d928589
  Downloading setuptools-36.2.1-py2.py3-none-any.whl (477kB): 477kB downloaded
Installing collected packages: pip, setuptools
  Found existing installation: pip 1.5.6
    Uninstalling pip:
      Successfully uninstalled pip
  Found existing installation: setuptools 5.5.1
    Uninstalling setuptools:
      Successfully uninstalled setuptools
Successfully installed pip setuptools
Cleaning up...
evan_jones@ejones-disposable-testing:~$ bug/bin/pip install google-cloud-datastore
Collecting google-cloud-datastore
  Using cached google_cloud_datastore-1.1.0-py2.py3-none-any.whl
Collecting google-cloud-core<0.26dev,>=0.25.0 (from google-cloud-datastore)
  Using cached google_cloud_core-0.25.0-py2.py3-none-any.whl
Collecting gapic-google-cloud-datastore-v1<0.16dev,>=0.15.0 (from google-cloud-datastore)
  Using cached gapic-google-cloud-datastore-v1-0.15.3.tar.gz
Collecting google-gax<0.16dev,>=0.15.7 (from google-cloud-datastore)
  Using cached google-gax-0.15.13.tar.gz
Collecting google-auth<2.0.0dev,>=0.4.0 (from google-cloud-core<0.26dev,>=0.25.0->google-cloud-datastore)
  Using cached google_auth-1.0.1-py2.py3-none-any.whl
Collecting httplib2>=0.9.1 (from google-cloud-core<0.26dev,>=0.25.0->google-cloud-datastore)
  Using cached httplib2-0.10.3.tar.gz
Collecting protobuf>=3.0.0 (from google-cloud-core<0.26dev,>=0.25.0->google-cloud-datastore)
  Using cached protobuf-3.3.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting googleapis-common-protos>=1.3.4 (from google-cloud-core<0.26dev,>=0.25.0->google-cloud-datastore)
  Using cached googleapis-common-protos-1.5.2.tar.gz
Collecting six (from google-cloud-core<0.26dev,>=0.25.0->google-cloud-datastore)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting google-auth-httplib2 (from google-cloud-core<0.26dev,>=0.25.0->google-cloud-datastore)
  Using cached google_auth_httplib2-0.0.2-py2.py3-none-any.whl
Collecting oauth2client<4.0dev,>=2.0.0 (from gapic-google-cloud-datastore-v1<0.16dev,>=0.15.0->google-cloud-datastore)
  Using cached oauth2client-3.0.0.tar.gz
Collecting dill<0.3dev,>=0.2.5 (from google-gax<0.16dev,>=0.15.7->google-cloud-datastore)
  Using cached dill-0.2.7.1.tar.gz
Collecting future<0.17dev,>=0.16.0 (from google-gax<0.16dev,>=0.15.7->google-cloud-datastore)
  Using cached future-0.16.0.tar.gz
Collecting grpcio<2.0dev,>=1.0.2 (from google-gax<0.16dev,>=0.15.7->google-cloud-datastore)
  Using cached grpcio-1.4.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting ply==3.8 (from google-gax<0.16dev,>=0.15.7->google-cloud-datastore)
  Using cached ply-3.8.tar.gz
Collecting requests<3.0dev,>=2.13.0 (from google-gax<0.16dev,>=0.15.7->google-cloud-datastore)
  Using cached requests-2.18.1-py2.py3-none-any.whl
Collecting cachetools>=2.0.0 (from google-auth<2.0.0dev,>=0.4.0->google-cloud-core<0.26dev,>=0.25.0->google-cloud-datastore)
  Using cached cachetools-2.0.0-py2.py3-none-any.whl
Collecting pyasn1>=0.1.7 (from google-auth<2.0.0dev,>=0.4.0->google-cloud-core<0.26dev,>=0.25.0->google-cloud-datastore)
  Using cached pyasn1-0.2.3-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from google-auth<2.0.0dev,>=0.4.0->google-cloud-core<0.26dev,>=0.25.0->google-cloud-datastore)
  Using cached pyasn1_modules-0.0.9-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from google-auth<2.0.0dev,>=0.4.0->google-cloud-core<0.26dev,>=0.25.0->google-cloud-datastore)
  Using cached rsa-3.4.2-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./bug/lib/python2.7/site-packages (from protobuf>=3.0.0->google-cloud-core<0.26dev,>=0.25.0->google-cloud-datastore)
Collecting enum34>=1.0.4 (from grpcio<2.0dev,>=1.0.2->google-gax<0.16dev,>=0.15.7->google-cloud-datastore)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting futures>=2.2.0 (from grpcio<2.0dev,>=1.0.2->google-gax<0.16dev,>=0.15.7->google-cloud-datastore)
  Using cached futures-3.1.1-py2-none-any.whl
Collecting urllib3<1.22,>=1.21.1 (from requests<3.0dev,>=2.13.0->google-gax<0.16dev,>=0.15.7->google-cloud-datastore)
  Using cached urllib3-1.21.1-py2.py3-none-any.whl
Collecting idna<2.6,>=2.5 (from requests<3.0dev,>=2.13.0->google-gax<0.16dev,>=0.15.7->google-cloud-datastore)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3.0dev,>=2.13.0->google-gax<0.16dev,>=0.15.7->google-cloud-datastore)
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0dev,>=2.13.0->google-gax<0.16dev,>=0.15.7->google-cloud-datastore)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Installing collected packages: cachetools, pyasn1, pyasn1-modules, rsa, six, google-auth, httplib2, protobuf, googleapis-common-protos, google-auth-httplib2, google-cloud-core, dill, future, enum34, futures, grpcio, ply, urllib3, idna, certifi, chardet, requests, google-gax, oauth2client, gapic-google-cloud-datastore-v1, google-cloud-datastore
  Running setup.py install for httplib2 ... done
  Running setup.py install for googleapis-common-protos ... done
  Running setup.py install for dill ... done
  Running setup.py install for future ... done
  Running setup.py install for ply ... done
  Running setup.py install for google-gax ... done
  Running setup.py install for oauth2client ... done
  Running setup.py install for gapic-google-cloud-datastore-v1 ... done
Successfully installed cachetools-2.0.0 certifi-2017.4.17 chardet-3.0.4 dill-0.2.7.1 enum34-1.1.6 future-0.16.0 futures-3.1.1 gapic-google-cloud-datastore-v1-0.15.3 google-auth-1.0.1 google-auth-httplib2-0.0.2 google-cloud-core-0.25.0 google-cloud-datastore-1.1.0 google-gax-0.15.13 googleapis-common-protos-1.5.2 grpcio-1.4.0 httplib2-0.10.3 idna-2.5 oauth2client-3.0.0 ply-3.8 protobuf-3.3.0 pyasn1-0.2.3 pyasn1-modules-0.0.9 requests-2.18.1 rsa-3.4.2 six-1.10.0 urllib3-1.21.1
evan_jones@ejones-disposable-testing:~$ bug/bin/pip freeze
cachetools==2.0.0
certifi==2017.4.17
chardet==3.0.4
dill==0.2.7.1
enum34==1.1.6
future==0.16.0
futures==3.1.1
gapic-google-cloud-datastore-v1==0.15.3
google-auth==1.0.1
google-auth-httplib2==0.0.2
google-cloud-core==0.25.0
google-cloud-datastore==1.1.0
google-gax==0.15.13
googleapis-common-protos==1.5.2
grpcio==1.4.0
httplib2==0.10.3
idna==2.5
oauth2client==3.0.0
ply==3.8
protobuf==3.3.0
pyasn1==0.2.3
pyasn1-modules==0.0.9
requests==2.18.1
rsa==3.4.2
six==1.10.0
urllib3==1.21.1
evan_jones@ejones-disposable-testing:~$ bug/bin/python -c 'import google.cloud.datastore'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/evan_jones/bug/local/lib/python2.7/site-packages/google/cloud/datastore/__init__.py", line 60, in <module>
    from google.cloud.datastore.batch import Batch
  File "/home/evan_jones/bug/local/lib/python2.7/site-packages/google/cloud/datastore/batch.py", line 24, in <module>
    from google.cloud.datastore import helpers
  File "/home/evan_jones/bug/local/lib/python2.7/site-packages/google/cloud/datastore/helpers.py", line 29, in <module>
    from google.cloud.proto.datastore.v1 import entity_pb2 as _entity_pb2
ImportError: No module named proto.datastore.v1
```

**Comment by evanj** [comment]
I just noticed: this may actually be a setuptools bug with the latest release. See https://github.com/pypa/setuptools/issues/1099 and https://github.com/pypa/setuptools/pull/1100

**Comment by evanj** [comment]
I'm going to close this since after looking at those issues, this appears to be a known bug, and it seems like another setuptools release is happening to fix it, so hopefully this will stop occurring.
