### ISSUE TITLE
Vision "manual" system tests are broken

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#3681]
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2591

```
nox > Session system_tests(python_version='3.6') successful. :)
nox > Running session system_tests_manual_layer(python_version='2.7')
nox > virtualenv /var/code/gcp/.nox/system_tests_manual_layer-python_version-2-7 -p python2.7
nox > chdir /var/code/gcp/vision
nox > pip install --upgrade pytest ../core/ ../storage/
nox > pip install --upgrade ../test_utils/
nox > pip install --upgrade -e .
nox > py.test --quiet tests/system_old.py
............FFF................
=================================== FAILURES ===================================
_______________ TestVisionClientLabel.test_detect_labels_content _______________
Traceback (most recent call last):
  File "/var/code/gcp/vision/tests/system_old.py", line 368, in test_detect_labels_content
    self._assert_label(label)
  File "/var/code/gcp/vision/tests/system_old.py", line 357, in _assert_label
    self.assertIn(label.description, self.DESCRIPTIONS)
  File "/usr/local/lib/python2.7/unittest/case.py", line 803, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: u'motor vehicle' not found in ('car', 'vehicle', 'land vehicle', 'automotive design', 'wheel', 'automobile make', 'luxury vehicle', 'sports car', 'performance car', 'automotive exterior')
...
```

**Comment by lukesneeringer** [comment]
This actually looks like the _output_ changed.

**Comment by dhermes** [comment]
As of https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2688 / #3720, this is keeping is red.

**Comment by dhermes** [comment]
This is bothering me, so I'm fixing it right now (if I can in under 15m).

**Comment by dhermes** [comment]
Boom, 10 minutes!
