### ISSUE TITLE
bigquery: 0.26.0 does not work on App Engine Standard

### ISSUE THREAD

**Issue by evanj** [GoogleCloudPlatform/google-cloud-python#3755]
Vendoring `google-cloud-bigquery==0.26.0` using the App Engine Standard instructions does not work, since the `google.cloud.future.polling` module depends on `tenacity` which depends on `monotonic` which depends on `ctypes`. It results in the following import error with dev_appserver.py. Issue #1893 may be for this same issue, except in that Issue, @jonparrott said on February 12th: "Storage and BigQuery should work on app engine". Using `google-cloud-bigquery==0.25.0` works.

```
Traceback (most recent call last):
  File "/src/devenv/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/src/devenv/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/src/devenv/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/src/trigger_mail/cstools/cstools/handlers.py", line 1, in <module>
    import google.cloud.bigquery
  File "/src/trigger_mail/cstools/service_lib/installed/google/cloud/bigquery/__init__.py", line 32, in <module>
    from google.cloud.bigquery.client import Client
  File "/src/trigger_mail/cstools/service_lib/installed/google/cloud/bigquery/client.py", line 21, in <module>
    from google.cloud.bigquery.job import CopyJob
  File "/src/trigger_mail/cstools/service_lib/installed/google/cloud/bigquery/job.py", line 34, in <module>
    import google.cloud.future.polling
  File "/src/trigger_mail/cstools/service_lib/installed/google/cloud/future/polling.py", line 23, in <module>
    import tenacity
  File "/src/trigger_mail/cstools/service_lib/installed/tenacity/__init__.py", line 28, in <module>
    from monotonic import monotonic as now
  File "/src/trigger_mail/cstools/service_lib/installed/monotonic.py", line 41, in <module>
    import ctypes
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
  File "/src/devenv/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/sandbox.py", line 1039, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named _ctypes
```

**Comment by jonparrott** [comment]
@evanj unfortunately we can't commit that any libraries will work on standard right now. If a previous version of bigquery worked, I would stick with that until we can more formally support standard.

**Comment by evanj** [comment]
Sounds good to me, thanks. Yet more reason for us to move off of App Engine. :(  Hopefully this will be useful for others searching for this problem.

**Comment by dhermes** [comment]
1. I love App Engine / PAAS
1. You're right, GAE is not a hammer for all nails
1. You **could** fake the "bad" modules by either patching `sys.modules` / shadowing them higher up your `PYTHONPATH` / replacing your vendored in source files (all of these are not-so-nice hacks, but make it possible)

**Comment by jonparrott** [comment]
FWIW, we are working really hard to make this happen, it's just a lot of engineering work.

**Comment by evanj** [comment]
I totally understand that this is hard, thanks for communicating it and for responding so quickly to this issue.

(This is not the right place for an App Engine discussion; I have a love/hate relationship with it, but given the current state, we are moving more stuff to Container Engine http://www.evanjones.ca/serverless-paas.html )
