### ISSUE TITLE
BigQuery: Parsing fails if timestamps or datetimes include microsecond part

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-python#3870]
In investigating some timestamp handling, I encountered an issue that the timestamp parsing ignores microseconds if present in the timestamp. Per https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#timestamp-type the microsecond portion is optional, but it could be present.

I've updated the system tests to reflect this issue:

https://github.com/tswast/google-cloud-python/blob/5a40bf02eba937097e90bc260da2d72e16d51213/bigquery/tests/system.py#L649

This test fails with

```
$ pytest tests/system.py::TestBigQuery::test_sync_query_w_standard_sql_types
============================================================================================== test session starts ==============================================================================================
platform darwin -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /Users/swast/src/google-cloud-python, inifile: setup.cfg
plugins: timeout-1.2.0
collected 1 item

tests/system.py F

=================================================================================================== FAILURES ====================================================================================================
_______________________________________________________________________________ TestBigQuery.test_sync_query_w_standard_sql_types _______________________________________________________________________________
Traceback (most recent call last):
  File "/Users/swast/src/google-cloud-python/bigquery/tests/system.py", line 747, in test_sync_query_w_standard_sql_types
    self.assertEqual(query.rows[0][0], example['expected'])
  File "/Users/swast/.pyenv/versions/3.6.2/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/swast/.pyenv/versions/3.6.2/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: datetime.datetime(2016, 12, 5, 12, 41, 9, tzinfo=<UTC>) != datetime.datetime(2016, 12, 5, 12, 41, 9, 250000, tzinfo=<UTC>)
=========================================================================================== 1 failed in 5.47 seconds ============================================================================================
```

**Comment by dhermes** [comment]
Thanks @tswast!

**Comment by tswast** [comment]
Oops, my test was incorrect. I've updated it at https://github.com/tswast/google-cloud-python/blob/bq-datetime/bigquery/tests/system.py#L680

The actual failure is

```
$ pytest tests/system.py::TestBigQuery::test_sync_query_w_standard_sql_types
============================================================= test session starts =============================================================
platform darwin -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /Users/swast/src/google-cloud-python, inifile: setup.cfg
plugins: timeout-1.2.0
collected 1 item

tests/system.py F

================================================================== FAILURES ===================================================================
______________________________________________ TestBigQuery.test_sync_query_w_standard_sql_types ______________________________________________
Traceback (most recent call last):
  File "/Users/swast/src/google-cloud-python/bigquery/tests/system.py", line 746, in test_sync_query_w_standard_sql_types
    self.assertEqual(len(query.rows), 1)
  File "/Users/swast/src/google-cloud-python/bigquery/google/cloud/bigquery/query.py", line 262, in rows
    return _rows_from_json(self._properties.get('rows', ()), self.schema)
  File "/Users/swast/src/google-cloud-python/bigquery/google/cloud/bigquery/_helpers.py", line 155, in _rows_from_json
    return [_row_from_json(row, schema) for row in rows]
  File "/Users/swast/src/google-cloud-python/bigquery/google/cloud/bigquery/_helpers.py", line 155, in <listcomp>
    return [_row_from_json(row, schema) for row in rows]
  File "/Users/swast/src/google-cloud-python/bigquery/google/cloud/bigquery/_helpers.py", line 148, in _row_from_json
    row_data.append(converter(cell['v'], field))
  File "/Users/swast/src/google-cloud-python/bigquery/google/cloud/bigquery/_helpers.py", line 77, in _datetime_from_json
    return datetime.datetime.strptime(value, _RFC3339_NO_FRACTION)
  File "/Users/swast/.pyenv/versions/3.6.2/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/Users/swast/.pyenv/versions/3.6.2/lib/python3.6/_strptime.py", line 365, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: .250000
========================================================== 1 failed in 8.73 seconds ===========================================================
```

**Comment by tswast** [comment]
Some more investigation:

The query results definitely have the partial timestamp portion.

```
#standardSql
SELECT TIMESTAMP "2016-12-05 12:41:09.250000"
```

Listing the table data of the destination table:

```
{
  "kind": "bigquery#tableDataList",
  "etag": "TVBcK6XsvZ+iE1wQtbr5LA==",
  "totalRows": "1",
  "rows": [
    {
      "f": [
        {
          "v": "1480941669.25"
        }
      ]
    }
  ]
}
```

Running getQueryResults

```
 "totalRows": "1",
 "rows": [
  {
   "f": [
    {
     "v": "1.48094166925E9"
    }
   ]
  }
 ],
```

It's a bit funny that they come back as floats inside strings, but it is what it is, I guess.

**Comment by dhermes** [comment]
"floats inside strings", how do you mean? i.e. `'1.25'` vs. `1.25`?

**Comment by tswast** [comment]
Yep, that's what I mean.

**Comment by lukesneeringer** [comment]
I believe that is an intentional API decision to get around the lack of integers in JavaScript.

**Comment by dhermes** [comment]
@lukesneeringer That'd be true if were an integer, but it's a float.

FWIW @tswast `number` in JS is IEEE-754 double precision (i.e. `double`), which can only hold integers with 53 bits of precision rather than 64 (for a `long`) so the Google approach is to send all `int64`-s as strings.

**Comment by lukesneeringer** [comment]
> That'd be true if were an integer, but it's a float.

Sure, but consistency is a thing. I am pretty sure that to get around that problem, BigQuery sends down _all_ numbers as strings.

It would be bizarre and confusing if floats came down as floats and ints came down as strings. As in, _even more_ bizarre and confusing than the current behavior.

**Comment by tseaver** [comment]
@lukesneeringer BigQuery is JSON only, and has to live within its stupidities.;  Spanner is (for us) gRCP only, and sends floats (in protos) as floats (except for `inf`, `+nan`, and `-nan`, which are sent as strings even though IEEE has a perfectly valid way to send them as proto-compatible binary).

**Comment by tseaver** [comment]
@tswast I'm not sure how your change in #3926 (which only adds system tests) fixes the failure here.

**Comment by dhermes** [comment]
@tseaver That was the last nail. #3901 and #3915 also contributed
