### ISSUE TITLE
Pub / Sub doesn't work with multiprocessing

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#3890]
This code fails with a pickle error:

```python
def multiprocessing_callback(message):
    print('Received message: {}'.format(message))
    message.ack()


def receive_messages_with_multiprocessing(
        project, topic_name, subscription_name):
    """Receives messages from a pull subscription using multiprocessing."""
    import concurrent.futures
    import functools
    import multiprocessing

    import google.cloud.pubsub_v1.subscriber.policy.thread

    # Create a process pool and a queue for sending messages. This will
    # be used by the subscriber policy to execute callbacks.
    executor = concurrent.futures.ProcessPoolExecutor()
    manager = multiprocessing.Manager()
    queue = manager.Queue()

    policy_factory = functools.partial(
        google.cloud.pubsub_v1.subscriber.policy.thread.Policy,
        executor=executor,
        queue=queue)
    subscriber = pubsub_v1.SubscriberClient(policy_class=policy_factory)
    subscription_path = subscriber.subscription_path(
        project, subscription_name)

    subscriber.subscribe(subscription_path, callback=multiprocessing_callback)

    # The subscriber is non-blocking, so we must keep the main thread from
    # exiting to allow it to process messages in the background.
    print('Listening for messages on {}'.format(subscription_path))
    while True:
        time.sleep(60)
```

**Comment by lukesneeringer** [comment]
Can you provide the traceback, too? ;-)

**Comment by jonparrott** [comment]
It's pretty unhelpful:

```
Traceback (most recent call last):
  File "/Users/jonwayne/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/queues.py", line 241, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/Users/jonwayne/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects
```

**Comment by danoscarmike** [comment]
Hi @lukesneeringer what's the next step here?

**Comment by michaelplaing** [comment]
This occurs when using the "spawn" context of multiprocessing.
However the "fork" context will also fail (but silently) when using grpcio==0.1.6.
A workaround for "fork" is to specify grpcio==0.1.4.

**Comment by dhermes** [comment]
So I can't reproduce the pickling error with `google-cloud-pubsub==0.30.0`, but it still fails (eventually) with a

```
E1219 12:19:30.755077995   16917 ssl_transport_security.cc:436] Corruption detected.
E1219 12:19:30.755141409   16917 ssl_transport_security.cc:412] error:100003fc:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_RECORD_MAC
E1219 12:19:30.755162457   16917 secure_endpoint.cc:185]     Decryption error: TSI_DATA_CORRUPTED
```

**Comment by dhermes** [comment]
I think I need to use OS X to see what @jonparrott was seeing. Or just an older version of `google-cloud-pubsub`.

**Comment by dhermes** [comment]
Some work towards making it feasible for an "alternate" implementation:

- #4628 (Making publisher `Batch` define a `make_lock()` rather than using a `threading.Lock` in a `PublisherClient`)
- #4634 (Use a UUID rather than a sentinel object on Pub / Sub `Future`)
- #4643 (allow `Future`-s to have a custom `Event` rather than using `threading.Event`)

**Comment by danoscarmike** [comment]
@dhermes reassigning this one to you.  Please update when you have something.  Thanks.

**Comment by danoscarmike** [comment]
Ping.  Next steps here?

**Comment by jonparrott** [comment]
I'm going to close this.

Multiprocessing in general is a dead-end with grpc clients because grpc does not work at all in multiprocessing environments. Even if we made the pubsub subscriber be able to execute callbacks in using multiprocessing, they wouldn't be able to do any useful work that involves any other client libraries calls.

@dhermes's work has made it feasible for us to support it in the future if grpcio does.

**Comment by jrmlhermitte** [comment]
I think this feature would be useful. Does this still work? Or is it unsupported?

Is this feature in particular still supported?
```py3
policy_factory = functools.partial(
        google.cloud.pubsub_v1.subscriber.policy.thread.Policy,
        executor=executor,
        queue=queue)
    subscriber = pubsub_v1.SubscriberClient(policy_class=policy_factory)
```

seems to not exist in the latest version of pubsub.
thanks!

**Comment by tseaver** [comment]
A more complete / up-to-date example, which still fails with the pickling error:

```python
import concurrent.futures
import functools
import multiprocessing
import os
import time


PROJECT = os.getenv('GOOGLE_CLOUD_PROJECT')
SUBSCRIPTION_NAME = 'repro-gcp-3980-sub'


def multiprocessing_callback(message):
    print('Received message: {}'.format(message))
    message.ack()


def create_client(executor, queue):
    # Defer import of gRPC-related modules until after multiprocessing forks.
    from google.cloud.pubsub_v1 import SubscriberClient
    from google.cloud.pubsub_v1.subscriber.scheduler import Scheduler

    class MultiprocessingScheduler(Scheduler):

        def __init__(self, executor, queue):
            self._executor = executor
            self._queue = queue

        @property
        def queue(self):
            return self._queue

        def schedule(self, callback, *args, **kwargs):
            self._executor.submit(callback, *args, **kwargs)

        def shutdown(self):
            try:
                while True:
                    self._executor._work_queue.get(block=False)
            except queue.Empty:
                pass
            self._executor.shutdown()

    scheduler = MultiprocessingScheduler(executor, queue)
    subscriber = SubscriberClient()

    return subscriber, scheduler


def receive_messages_with_multiprocessing():
    """Receives messages from a pull subscription using multiprocessing."""

    # Create a process pool and a queue for sending messages. This will
    # be used by the subscriber policy to execute callbacks.
    executor = concurrent.futures.ProcessPoolExecutor()
    manager = multiprocessing.Manager()
    queue = manager.Queue()

    subscriber, scheduler = create_client(executor, queue)

    subscription_path = subscriber.subscription_path(
        PROJECT, SUBSCRIPTION_NAME)

    subscriber.subscribe(
        subscription_path,
        callback=multiprocessing_callback,
        scheduler=scheduler,
    )

    # The subscriber is non-blocking, so we must keep the main thread from
    # exiting to allow it to process messages in the background.
    print('Listening for messages on {}'.format(subscription_path))
    while True:
        time.sleep(60)


if __name__ == '__main__':
    receive_messages_with_multiprocessing()
```
