### ISSUE TITLE
Pubsub messages documentation is empty

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-python#3896]
https://google-cloud-python.readthedocs.io/en/latest/pubsub/subscriber/api/message.html

**Comment by lukesneeringer** [comment]
This builds properly on my machine. Any troubleshooting advice?

**Comment by dhermes** [comment]
Run the same commands from a RTD build. You can see the exact commands in every build: https://readthedocs.org/projects/google-cloud-python/builds/ (e.g. our `nox -s docs` session uses Python 3.6 but RTD uses 3.5)

I also just realized the RTD build has been failing for 10+ days and for some reason I stopped getting email notifications about this.

**Comment by dhermes** [comment]
I just wiped the cache and started a fresh [build][1] and am seeing the fame failure:

```python
    Traceback (most recent call last):
      File "/home/docs/checkouts/readthedocs.org/user_builds/google-cloud-python/envs/latest/lib/python2.7/site.py", line 703, in <module>
        main()
      File "/home/docs/checkouts/readthedocs.org/user_builds/google-cloud-python/envs/latest/lib/python2.7/site.py", line 683, in main
        paths_in_sys = addsitepackages(paths_in_sys)
      File "/home/docs/checkouts/readthedocs.org/user_builds/google-cloud-python/envs/latest/lib/python2.7/site.py", line 282, in addsitepackages
        addsitedir(sitedir, known_paths)
      File "/home/docs/checkouts/readthedocs.org/user_builds/google-cloud-python/envs/latest/lib/python2.7/site.py", line 204, in addsitedir
        addpackage(sitedir, name, known_paths)
      File "/home/docs/checkouts/readthedocs.org/user_builds/google-cloud-python/envs/latest/lib/python2.7/site.py", line 173, in addpackage
        exec(line)
      File "<string>", line 1, in <module>
    KeyError: 'google.cloud.gapic'
```

[1]: https://readthedocs.org/projects/google-cloud-python/builds/5933040/

**Comment by lukesneeringer** [comment]
Fixed.
