### ISSUE TITLE
Spanner Documentation not current: read and executeSql

### ISSUE THREAD

**Issue by danoscarmike** [GoogleCloudPlatform/google-cloud-python#3932]
Submitting for @mkmg

The documentation for the [Database module](https://googlecloudplatform.github.io/google-cloud-python/latest/spanner/database-api.html) still lists the methods read and executeSql, but these were [recently removed](https://github.com/GoogleCloudPlatform/google-cloud-python/commit/ebecc7d0da7a6f9e02ea1c81cd85e80276b58e3b#diff-085044bc09561ccdd560aaca37a07f02). 

cc/ @lukesneeringer

**Comment by dhermes** [comment]
To clarify, the build is broken, the docs session works just fine, but it never runs because the Spanner system tests have been broken for weeks.

**Comment by tseaver** [comment]
Hmm, I'm not sure what the breakage is.  Emulating CircleCI locally:

```bash
$ git fetch upstream && git merge upstream/master 
Already up-to-date.
$ cd spanner
$ CIRCLECI=true nox -e "system_tests(python_version='3.6')"
nox > Running session system_tests(python_version='3.6')
nox > virtualenv .../google-cloud-python/spanner/.nox/sys-3-6 -p python3.6
nox > chdir .../google-cloud-python/spanner
nox > pip install --upgrade mock pytest ../core/
nox > pip install --upgrade ../test_utils/
nox > pip install --upgrade .
nox > py.test --quiet tests/system
......................................
38 passed in 120.88 seconds
nox > Session system_tests(python_version='3.6') successful. :)
```

**Comment by dhermes** [comment]
@tseaver Run it with the same account and project?

**Comment by tseaver** [comment]
@dhermes Yes, I was running with those creds.

**Comment by tseaver** [comment]
@dhermes do we have docs for building / pushing manually?  I just tried with:

```bash
$ CIRCLE_BRANCH=master PATH=".nox/docs/bin:$PATH" test_utils/scripts/update_docs.sh 
```

and had it fail:

```bash
GH_OWNER='GoogleCloudPlatform'
GH_PROJECT_NAME='google-cloud-python'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd 
 dirname "${BASH_SOURCE[0]}" 

# Function to build the docs.
function build_docs {
    rm -rf docs/_build/
    sphinx-build -W -b html -d docs/_build/doctrees docs/ docs/_build/html/
    return $?
}

# Only update docs if we are on CircleCI.
if [[ "${CIRCLE_BRANCH}" == "master" ]] && [[ -z "${CIRCLE_PR_NUMBER}" ]]; then
    echo "Building new docs on a merged commit."
elif [[ -n "${CIRCLE_TAG}" ]]; then
    echo "Building new docs on a tag (but will not deploy)."
    build_docs
    exit $?
else
    echo "Not on master nor a release tag."
    echo "Building new docs for testing purposes, but not deploying."
    build_docs
    exit $?
fi
Building new docs on a merged commit.

# Adding GitHub pages branch. `git submodule add` checks it
# out at HEAD.
GH_PAGES_DIR='ghpages'
git submodule add -q -b gh-pages \
    "git@github.com:${GH_OWNER}/${GH_PROJECT_NAME}" ${GH_PAGES_DIR}

# Determine if we are building a new tag or are building docs
# for master. Then build new docs in docs/_build from master.
if [[ -n "${CIRCLE_TAG}" ]]; then
    # Sphinx will use the package version by default.
    build_docs
else
    SPHINX_RELEASE=$(git log -1 --pretty=%h) build_docs
fi
git log -1 --pretty=%h
Running Sphinx v1.6.3
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from https://google-auth.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://gax-python.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from http://www.grpc.io/grpc/python/objects.inv...
intersphinx inventory has moved: http://www.grpc.io/grpc/python/objects.inv -> https://grpc.io/grpc/python/objects.inv
loading intersphinx inventory from http://docs.python-requests.org/en/master/objects.inv...
loading intersphinx inventory from http://pandas.pydata.org/pandas-docs/stable/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 117 source files that are out of date
updating environment: 117 added, 0 changed, 0 removed
reading sources... [100%] vision/index                                          
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] vision/index                                           
generating indices... genindex py-modindex
highlighting module code... [ 34%] google.cloud.gapic.language.v1.language_servihighlighting module code... [ 36%] google.cloud.proto.language.v1.language_servihighlighting module code... [ 37%] google.cloud.gapic.language.v1beta2.language_highlighting module code... [ 39%] google.cloud.proto.language.v1beta2.language_highlighting module code... [ 44%] google.cloud.logging.handlers.container_enginhighlighting module code... [ 50%] google.cloud.logging.handlers.transports.backhighlighting module code... [ 63%] google.cloud.gapic.pubsub.v1.subscriber_clienhighlighting module code... [ 65%] google.cloud.pubsub_v1.subscriber.policy.threhighlighting module code... [ 95%] google.cloud.gapic.vision.v1.image_annotator_highlighting module code... [ 98%] google.cloud.proto.vision.v1.image_annotator_highlighting module code... [ 99%] google.cloud.proto.vision.v1.text_annotation_highlighting module code... [100%] google.cloud.proto.vision.v1.web_detection_pb2
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

# Get the current version.
# This is only likely to work from within nox, because the google-cloud
# package must be installed.
CURRENT_VERSION=$(python ${DIR}/get_version.py)
python ${DIR}/get_version.py
Traceback (most recent call last):
  File "/home/tseaver/projects/agendaless/Google/src/gcp-docs/test_utils/scripts/get_version.py", line 21, in <module>
    print(get_distribution('google-cloud').version)
  File "/home/tseaver/projects/agendaless/Google/src/gcp-docs/.nox/docs/lib/python3.6/site-packages/pkg_resources/__init__.py", line 562, in get_distribution
    dist = get_provider(dist)
  File "/home/tseaver/projects/agendaless/Google/src/gcp-docs/.nox/docs/lib/python3.6/site-packages/pkg_resources/__init__.py", line 436, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/tseaver/projects/agendaless/Google/src/gcp-docs/.nox/docs/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/tseaver/projects/agendaless/Google/src/gcp-docs/.nox/docs/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'google-cloud' distribution was not found and is required by the application
```

**Comment by dhermes** [comment]
@tseaver I just do some like this:

```
$ git fetch official  # you call it `upstream` I believe
$ git branch gh-pages-pr-XYZ official/gh-pages
$ nox -s docs  # no special env. vars
$ mv docs/_build/html somewhere/out/of/repo
$ git checkout gh-pages-pr-XYZ
$ rm -fr latest/
$ mv somewhere/out/of/repo latest
$ git add latest/
$ git commit -m '...'
$ git push official gh-pages-pr-XYZ
```

Then I make a PR onto `gh-pages` and ask for a token LGTM.

Note that I avoid pushing to my own remote because I don't have any of the `gh-pages` history there, which would make the push take much longer / use much more data.
