### ISSUE TITLE
KeyError: "Couldn't find field google.protobuf.DescriptorProto.ExtensionRange.options" when  import datastore

### ISSUE THREAD

**Issue by tianqig** [GoogleCloudPlatform/google-cloud-python#3948]
Just installed google-cloud (0.27.0) on my Mac OS X EI Capitan
Python 2.7
Anaconda 

under a root env. when running: testLog.py 
```
#Retrieve Datastore Entities
from google.cloud import datastore
client = datastore.Client()
product_key = client.key('Product', 123)
print(client.get(product_key))
```

Got following messages:

```
Traceback (most recent call last):
  File "testLog.py", line 3, in <module>
    from google.cloud import datastore
  File "/Users/David/anaconda/lib/python2.7/site-packages/google/cloud/datastore/__init__.py", line 60, in <module>
    from google.cloud.datastore.batch import Batch
  File "/Users/David/anaconda/lib/python2.7/site-packages/google/cloud/datastore/batch.py", line 24, in <module>
    from google.cloud.datastore import helpers
  File "/Users/David/anaconda/lib/python2.7/site-packages/google/cloud/datastore/helpers.py", line 23, in <module>
    from google.protobuf import struct_pb2
  File "/Users/David/anaconda/lib/python2.7/site-packages/google/protobuf/struct_pb2.py", line 11, in <module>
    from google.protobuf import descriptor_pb2
  File "/Users/David/anaconda/lib/python2.7/site-packages/google/protobuf/descriptor_pb2.py", line 409, in <module>
    options=None),
  File "/Users/David/anaconda/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 501, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.DescriptorProto.ExtensionRange.options"

```

Please help, thanks

**Comment by lukesneeringer** [comment]
Hi @tianqig,
Thanks for reporting.

Could you try creating a virtualenv and installing _only_ `protobuf`, and see if `from google.protobuf import descriptor_pb2` passes?

Also, this seems like it is probably an issue with protobuf itself, so I am going to move this issue over there.

**Comment by lukesneeringer** [comment]
This issue was moved to google/protobuf#3631
