### ISSUE TITLE
spanner library doesn't work with credentials whose scope can't be modified.

### ISSUE THREAD

**Issue by jlewi** [GoogleCloudPlatform/google-cloud-python#4008]
I'm using application default credentials to create credentials for use with the spanner client library. These credentials are obtained by running 

```
gcloud auth application-default login
```

My code fails with the following stack trace.

```
Traceback (most recent call last):
  File "/bazel_cache/_bazel_jlewi/1c9ff9fd5966eae5ae66af2948992bce/bazel-sandbox/3357018790234970416/execroot/org_tensorflow_tensorboard/bazel-out/local-fastbuild/bin/tensorboard/platforms/gcp/spanner_e2e_test.runfiles/org_tensorflow_tensorboard/tensorboard/platforms/gcp/spanner_e2e_test.py", line 57, in testInsertSql
    (rowid, customer_number, run_id, event_log_id, path, offset))
  File "/bazel_cache/_bazel_jlewi/1c9ff9fd5966eae5ae66af2948992bce/bazel-sandbox/3357018790234970416/execroot/org_tensorflow_tensorboard/bazel-out/local-fastbuild/bin/tensorboard/platforms/gcp/spanner_e2e_test.runfiles/org_tensorflow_tensorboard/tensorboard/db.py", line 390, in execute
    self._delegate.execute(sql, parameters)
  File "/bazel_cache/_bazel_jlewi/1c9ff9fd5966eae5ae66af2948992bce/bazel-sandbox/3357018790234970416/execroot/org_tensorflow_tensorboard/bazel-out/local-fastbuild/bin/tensorboard/platforms/gcp/spanner_e2e_test.runfiles/org_tensorflow_tensorboard/tensorboard/platforms/gcp/spanner.py", line 221, in execute
    with self.database.batch() as batch:
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/spanner/database.py", line 401, in __enter__
    session = self._session = self._database._pool.get()
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/spanner/pool.py", line 228, in get
    session.create()
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/spanner/session.py", line 98, in create
    api = self._database.spanner_api
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/spanner/database.py", line 165, in spanner_api
    credentials = credentials.with_scopes((SPANNER_DATA_SCOPE,))
  File "/usr/local/lib/python2.7/dist-packages/google/oauth2/credentials.py", line 119, in with_scopes
    'OAuth 2.0 Credentials can not modify their scopes.')
NotImplementedError: OAuth 2.0 Credentials can not modify their scopes.
```

The problem appears to be the following code from [database.py](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/spanner/google/cloud/spanner/database.py#L164)

```
    @property
    def spanner_api(self):
        """Helper for session-related API calls."""
        if self._spanner_api is None:
            credentials = self._instance._client.credentials
            if isinstance(credentials, google.auth.credentials.Scoped):
                credentials = credentials.with_scopes((SPANNER_DATA_SCOPE,))
            self._spanner_api = SpannerClient(
                lib_name='gccl',
                lib_version=__version__,
                credentials=credentials,
            )
        return self._spanner_api
```
My credential is of type [google.oauth2.credentials.Credentials](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/master/google/oauth2/credentials.py#L118) which doesn't implement with_scopes.

The docs don't indicate a preferred pattern for distinguishing between credentials whose scope can be modified and those that can't. A simple solution would be to catch the NotImplementedError and ignore it.

**Comment by jlewi** [comment]
It looks like there might a helper method [google.auth.with_scopes_if_required](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/master/google/auth/credentials.py#L224) that will do the right thing. So I think something like the following will work

```
@property
    def spanner_api(self):
        """Helper for session-related API calls."""
        if self._spanner_api is None:
            credentials = self._instance._client.credentials
            credentials = google.auth.credentials.with_scopes_if_required(credentials, (SPANNER_DATA_SCOPE,))
            self._spanner_api = SpannerClient(
                lib_name='gccl',
                lib_version=__version__,
                credentials=credentials,
            )
        return self._spanner_api
```

**Comment by jonparrott** [comment]
This issue aside, you really shouldn't use `gcloud auth application-default login`. It's highly recommend to use service accounts directly. See this documentation: cloud.google.com/docs/authentication/getting-started

**Comment by lukesneeringer** [comment]
I think @tseaver just did something for a different API that addresses this?

**Comment by tseaver** [comment]
This is similar to #3933.  The fix there is to update `google.auth >= 1.1.0`, so that GCE credentials no longer derive from `Scoped` (since they cannot implement the `with_scopes` method correctly).

It looks like there is a similar [fix already committed](https://github.com/GoogleCloudPlatform/google-auth-library-python/commit/cb7b3c4f543bc8458863723d47c16ed685440700#diff-8856a6307e1657edfbf1f120069e479a) for the `google.oauth2.credentials.Credentials` class, merged by @jonparrott

**Comment by lukesneeringer** [comment]
Hello @jlewi,
Based on the above, I am going to close this issue, and you just need to update to `google auth >= 1.1.0`. If that does not solve your problem, feel free to open a new issue.

**Comment by tseaver** [comment]
@lukesneeringer FWIW the fix for `google.oauth2.credentials.Credentials` is not part of the `google.auth 1.1.0` release:  @jlewi needs to upgrade to `google.auth 1.1.1` to get the fix.

**Comment by jlewi** [comment]
Thanks
