### ISSUE TITLE
Hi, I'm trying to deploy my application to GAE, but I have the errors below. can you help me?

### ISSUE THREAD

**Issue by jacksonlima91** [GoogleCloudPlatform/google-cloud-python#4042]
# Thank you for reporting an issue to google-cloud-python!

If you are reporting an issue or requesting a feature, please search the
existing open and closed issues to see if there is already work being done.

- https://github.com/GoogleCloudPlatform/google-cloud-python/issues
- http://stackoverflow.com/questions/tagged/google-cloud-python

If you can provide us with as much of the following information as possible it
will help us identify the cause of your issue more quickly.

1. OS type and version 

Linux (appengine flexible python runtime)

2. Python version and virtual environment information `python --version`

Python 3.5.2
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`

alembic==0.9.4
blinker==1.4
click==6.7
google-cloud==0.27.0
Flask==0.12.2
Flask-Mail==0.9.1
Flask-Migrate==2.1.0
Flask-Restless==0.17.0
Flask-Script==2.0.5
Flask-SQLAlchemy==2.2
Flask-WTF==0.14.2
gunicorn==19.7.1
itsdangerous==0.24
Jinja2==2.9.6
Mako==1.0.7
MarkupSafe==1.0
mimerender==0.6.0
psycopg2==2.7.3
pycpfcnpj==1.1
PyMySQL==0.7.11
python-dateutil==2.6.1
python-editor==1.0.3
python-mimeparse==1.6.0
PyMongo==3.5.1
oauth2client==4.1.2
six==1.10.0
SQLAlchemy==1.1.13
Werkzeug==0.12.2
WTForms==2.1

4. Stacktrace if available

Traceback (most recent call last): File "/env/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app response = self.full_dispatch_request() File "/env/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request rv = self.handle_user_exception(e) File "/env/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception reraise(exc_type, exc_value, tb) File "/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise raise value File "/env/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request rv = self.dispatch_request() File "/env/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/home/vmagent/app/main.py", line 76, in empresa sg =[(seg.nome, seg.nome) for seg in Seguimento.query.all()] File "/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 498, in __get__ return type.query_class(mapper, session=self.sa.session()) File "/env/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__ return self.registry() File "/env/lib/python3.5/site-packages/sqlalchemy/util/_collections.py", line 990, in __call__ return self.registry.setdefault(key, self.createfunc()) File "/env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2861, in __call__ return self.class_(**local_kw) File "/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 144, in __init__ track_modifications = app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] KeyError: 'SQLALCHEMY_TRACK_MODIFICATIONS'

5. Steps to reproduce

Acess the page https://mrfind-dev.appspot.com/empresa

Yoo see error 500
6. Code example

Using GitHub flavored markdown can help make your request clearer.
See: https://guides.github.com/features/mastering-markdown/

**Comment by lukesneeringer** [comment]
Hi @jacksonlima91,
This repository is for the Python client libraries for Google APIs, not for GAE. Sorry. :-(
