### ISSUE TITLE
table fetch_data sometimes breaks 

### ISSUE THREAD

**Issue by david-gang** [GoogleCloudPlatform/google-cloud-python#4139]
Sometimes when i run table fetch_data it works and some seconds when running afterwards it crashes. I added all info i know below. Please advise which additional info is needed.

# Thank you for reporting an issue to google-cloud-python!

If you are reporting an issue or requesting a feature, please search the
existing open and closed issues to see if there is already work being done.

- https://github.com/GoogleCloudPlatform/google-cloud-python/issues
- http://stackoverflow.com/questions/tagged/google-cloud-python

If you can provide us with as much of the following information as possible it
will help us identify the cause of your issue more quickly.

1. OS type and version
Ubuntu 16.04
2. Python version and virtual environment information `python --version`
/bin/python --version
Python 3.6.2 :: Anaconda, Inc.

3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
google-cloud==0.27.0
  - google-cloud-bigquery==0.26.0
  - google-cloud-bigtable==0.26.0
  - google-cloud-core==0.26.0
  - google-cloud-datastore==1.2.0
  - google-cloud-dns==0.26.0
  - google-cloud-error-reporting==0.26.0
  - google-cloud-language==0.27.0
  - google-cloud-logging==1.2.0
  - google-cloud-monitoring==0.26.0
  - google-cloud-pubsub==0.27.0
  - google-cloud-resource-manager==0.26.0
  - google-cloud-runtimeconfig==0.26.0
  - google-cloud-spanner==0.26.0
  - google-cloud-speech==0.28.0
  - google-cloud-storage==1.3.2
  - google-cloud-translate==1.1.0
  - google-cloud-videointelligence==0.25.0
  - google-cloud-vision==0.26.0

4. Stacktrace if available
```bash
/bin/python /home/david/IdeaProjects/data_analysis_scripts/predictor.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
^C%➜  data_analysis_scripts git:(master) ✗ /home/david/anaconda3/envs/microservice/bin/python /home/david/IdeaProjects/data_analysis_scripts/predictor.py
Traceback (most recent call last):
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/socket.py", line743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fe2ce0d6be0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /bigquery/v2/projects/cloud-eng-dev/datasets/STATS/tables/MY_DATA/data (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe2ce0d6be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/IdeaProjects/data_analysis_scripts/predictor.py", line 24, in <module>
    ports_data = parse_ports()
  File "/home/david/IdeaProjects/data_analysis_scripts/predictor.py", line 15, in parse_ports
    for arr in res:
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/google/cloud/iterator.py", line 218, in _items_iter
    for page in self._page_iter(increment=False):
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/google/cloud/iterator.py", line 248, in _page_iter
    page = self._next_page()
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/google/cloud/iterator.py", line 348, in _next_page
    response = self._get_next_page_response()
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/google/cloud/iterator.py", line 399, in _get_next_page_response
    query_params=params)
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/google/cloud/_http.py", line 290, in api_request
    headers=headers, target_object=_target_object)
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/google/cloud/_http.py", line 183, in _make_request
    return self._do_request(method, url, headers, data, target_object)
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/google/cloud/_http.py", line 212, in _do_request
    url=url, method=method, headers=headers, data=data)
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/google/auth/transport/requests.py", line 179, in request
    method, url, data=data, headers=request_headers, **kwargs)
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/david/anaconda3/envs/microservice/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.googleapis.com', port=443):Max retries exceeded with url: /bigquery/v2/projects/cloud-eng-dev/datasets/STATS/tables/MY_DATA/data (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe2ce0d6be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```
5. Steps to reproduce

6. Code example
table = dataset.table(TABLE_NAME, SCHEMA)
for row in table.fetch_data():
  make_something()

Using GitHub flavored markdown can help make your request clearer.
See: https://guides.github.com/features/mastering-markdown/

**Comment by lukesneeringer** [comment]
Hi @david-gang,
This honestly looks like an issue with your machine or network connection. As far as I am aware, www.googleapis.com has not had any outages in the last few days, and the error message quite literally indicates inability to establish a new connection.

I am afraid there is nothing I can do about this, so I am going to close this issue. Feel free to follow up or reopen if I got it wrong.

Thanks!

**Comment by david-gang** [comment]
Thanks for the clarification. I am sure this ticket will serve for documentation to others.
