### ISSUE TITLE
Spanner: instance.execute_sql() with index search works on Python 2 but not Python 3

### ISSUE THREAD

**Issue by malusdei** [GoogleCloudPlatform/google-cloud-python#4217]
I noticed the banking example and the snippets file (which we use as documented examples) run well enough in a Python 2.7 environment.

However, when I set up a Python 3.6 environment and try to run the same thing, I get the following stack trace:

```
Traceback (most recent call last):
  File "bank_example.py", line 421, in <module>
    main()
  File "bank_example.py", line 395, in main
    account_balance(database, ACCOUNTS[1])
  File "bank_example.py", line 192, in account_balance
    for row in results:
  File "/Users/changsolomon/pyscripts/env/lib/python3.6/site-packages/google/cloud/spanner_v1/streamed.py", line 157, in __iter__
    self.consume_next()  # raises StopIteration
  File "/Users/changsolomon/pyscripts/env/lib/python3.6/site-packages/google/cloud/spanner_v1/streamed.py", line 123, in consume_next
    response = six.next(self._response_iterator)
  File "/Users/changsolomon/pyscripts/env/lib/python3.6/site-packages/google/cloud/spanner_v1/snapshot.py", line 40, in _restart_on_unavailable
    iterator = restart()
  File "/Users/changsolomon/pyscripts/env/lib/python3.6/site-packages/google/cloud/spanner_v1/gapic/spanner_client.py", line 566, in execute_streaming_sql
    query_mode=query_mode)
  File "/Users/changsolomon/pyscripts/env/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 497, in init
    copy[key].MergeFrom(field_value[key])
  File "/Users/changsolomon/pyscripts/env/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 1215, in MergeFrom
    'expected %s got %s.' % (cls.__name__, msg.__class__.__name__))
TypeError: Parameter to MergeFrom() must be instance of same class: expected Type got Type.
```

In this particular case, I was trying to use the .execute_sql method of a snapshot object, but I get a similar message when I execute the query_data_with_index function of snippets.py.
The problem goes away if I leave out the params and param_types arguments of .execute_sql.

I am using:
OSX 10.12.6
Python 3.6.3 and Python 2.7
Google Cloud 0.27

To reproduce:
Set up a Python 3.6 virtual environment.
Retrieve https://github.com/GoogleCloudPlatform/python-docs-samples
Run the snippets.py file with arguments to execute query_data_with_index().  E.g.:
`$ python snippets.py --database-id my_database my_instance query_data_with_index`
The stack trace above will be generated.

**Comment by tseaver** [comment]
My first guess is that this is a bytes-vs-text issue, masked by the protobuf marshalling.  Can you try the snippet with explicit text as the argument defaults?  E.g.:

```python
def query_data_with_index(
    instance_id, database_id, start_title=u'Aardvark', end_title=u'Goo'):
```

My guess is that both 2.7 and 3.6 will fail.

**Comment by malusdei** [comment]
I have just tested this against Python 2.7 and Python 3.4.  It looks like the types are working now.
