### ISSUE TITLE
Can't Install Sound Device Due To egg_info error code 1

### ISSUE THREAD

**Issue by DevoDon** [GoogleCloudPlatform/google-cloud-python#4311]
I know this is an occuring problem as i'm finding issues everywhere
but can someone help me resolve please?
```
C:\WINDOWS\system32>pip install sounddevice
Collecting sounddevice
  Using cached sounddevice-0.3.9-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33.pp34.pp35.pp36-none-win_amd64.whl
Collecting CFFI>=1.0 (from sounddevice)
  Using cached cffi-1.11.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Dale\AppData\Local\Temp\pip-build-189e4pud\CFFI\setup.py", line 116, in <module>
        if sys.platform == 'win32' and uses_msvc():
      File "C:\Users\Dale\AppData\Local\Temp\pip-build-189e4pud\CFFI\setup.py", line 94, in uses_msvc
        return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
      File "c:\program files\python37\lib\distutils\command\config.py", line 227, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "c:\program files\python37\lib\distutils\command\config.py", line 133, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "c:\program files\python37\lib\distutils\_msvccompiler.py", line 345, in compile
        self.initialize()
      File "c:\program files\python37\lib\distutils\_msvccompiler.py", line 238, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\program files\python37\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\program files\python37\lib\site-packages\setuptools\msvc.py", line 1228, in return_env
        [self.VCIncludes,
      File "c:\program files\python37\lib\site-packages\setuptools\msvc.py", line 877, in VCIncludes
        return [os.path.join(self.si.VCInstallDir, 'Include'),
      File "c:\program files\python37\lib\site-packages\setuptools\msvc.py", line 556, in VCInstallDir
        raise distutils.errors.DistutilsPlatformError(msg)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Dale\AppData\Local\Temp\pip-build-189e4pud\CFFI\
```

**Comment by dhermes** [comment]
@DevoDon It seems you've ended up in the wrong place? This repository is for `google-cloud-python`.

Here is the repository you're looking for: https://github.com/spatialaudio/python-sounddevice

Let us know if there is anything else we can help with.

PS Bravo using Python 3.7!
