### ISSUE TITLE
Speech: Incomplete protobuf

### ISSUE THREAD

**Issue by anilshanbhag** [GoogleCloudPlatform/google-cloud-python#4342]
When using google-cloud-speech in http mode, the response to a long running recognize contains totalBilledTime. This field is however not present in the protobuf causing the error below.

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/anil/Dev/repos/dictanote/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/anil/Dev/repos/dictanote/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/anil/Dev/repos/dictanote/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/anil/Dev/repos/dictanote/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/anil/Dev/repos/dictanote/dictanote/management/commands/pull_results.py", line 29, in handle
    if op.poll():
  File "/Users/anil/Dev/repos/dictanote/lib/python2.7/site-packages/google/cloud/operation.py", line 267, in poll
    operation_pb = self._get_operation()
  File "/Users/anil/Dev/repos/dictanote/lib/python2.7/site-packages/google/cloud/operation.py", line 235, in _get_operation
    return self._get_operation_http()
  File "/Users/anil/Dev/repos/dictanote/lib/python2.7/site-packages/google/cloud/operation.py", line 224, in _get_operation_http
    api_response, operations_pb2.Operation())
  File "/Users/anil/Dev/repos/dictanote/lib/python2.7/site-packages/google/protobuf/json_format.py", line 402, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/Users/anil/Dev/repos/dictanote/lib/python2.7/site-packages/google/protobuf/json_format.py", line 433, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/Users/anil/Dev/repos/dictanote/lib/python2.7/site-packages/google/protobuf/json_format.py", line 535, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Message type "google.cloud.speech.v1.LongRunningRecognizeResponse" has no field named "totalBilledTime".
 Available Fields(except extensions): [<google.protobuf.descriptor.FieldDescriptor object at 0x10f1bac10>]
```

**Comment by tseaver** [comment]
@anilshanbhag Thanks for the report!  Can you tell us what versions of the google.cloud-related packages you have installed?  E.g.:

```bash
$ pip freeze | grep google
```

**Comment by lukesneeringer** [comment]
Also, what do you mean by "in HTTP mode"? I do not think the Speech module supports anything other than gRPC anymore.

**Comment by anilshanbhag** [comment]
I am using `google-cloud-speech==0.30.0`.

Cloud speech does have a HTTP endpoint. To use in client, I did:
```
from google.cloud import speech
speech_client = speech.Client(_use_grpc=False)
```
The reason I use HTTP client is I have a bunch of long running recognize requests. I want to be able to check later (say after an hour) and get the answer. To do this, I can get the request id after making the request to cloud-speech. Then at the later point, I can use the id to fetch the results. 

To make it work, I ended up doing two hacks in _get_operation_http method of google/cloud/operation.py:

1) Delete the totalBillableTime attribute 
2) Change `client.speech_api._connection` to `client.speech_api._connection`

Final code:

```
    def _get_operation_http(self):
        """Checks the status of the current operation.

        Uses HTTP request to check.

        :rtype: :class:`~google.longrunning.operations_pb2.Operation`
        :returns: The latest status of the current operation.
        """
        path = 'operations/%s' % (self.name,)
        api_response = self.client.speech_api._connection.api_request(
            method='GET', path=path)
        if 'response' in api_response:
            if 'totalBilledTime' in api_response['response']:
                del api_response['response']['totalBilledTime']
        return json_format.ParseDict(
            api_response, operations_pb2.Operation())
```

**Comment by tseaver** [comment]
@anilshanbhag The current release (0.32.0) no longer supports the HTTP endpoint.

Please reopen if you can reproduce against that version.
