### ISSUE TITLE
Flaky error-reporting system test

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/google-cloud-python#4377]
See: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/4182

```python
Traceback (most recent call last):
  File "/var/code/gcp/error_reporting/tests/system.py", line 123, in test_report_exception
    error_count = wrapped_get_count(class_name, Config.CLIENT)
  File "/var/code/gcp/.nox/sys-2-7/lib/python2.7/site-packages/test_utils/retry.py", line 155, in wrapped_function
    raise BackoffFailed()
BackoffFailed
```

**Comment by tseaver** [comment]
Preemptively closing because we have no repeats in eight months.
