### ISSUE TITLE
PubSub: `add_methods()` doesn't handle `@classmethod`-s as expected

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#4441]
Using the public interface, the [`@classmethod`][1] only works on instances:

```python
>>> from google.cloud import pubsub_v1
>>> publisher = pubsub_v1.PublisherClient()
>>> publisher.topic_path('a', 'b')
'projects/a/topics/b'
>>> pubsub_v1.PublisherClient.topic_path('a', 'b')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../google/cloud/pubsub_v1/_gapic.py", line 44, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(*a, **kw)
TypeError: topic_path() missing 1 required positional argument: 'topic'
```

note that there is no issue with the base:

```python
>>> from google.cloud.pubsub_v1.gapic import publisher_client
>>> publisher_gapic = publisher_client.PublisherClient()
>>> publisher_gapic.topic_path('a', 'b')
'projects/a/topics/b'
>>> publisher_client.PublisherClient.topic_path('a', 'b')
'projects/a/topics/b'
```

----

```
$ git log -1 --pretty=%H
4b107613b0fcf139569504e9d44fa4a0793b4fd0
```

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/4b107613b0fcf139569504e9d44fa4a0793b4fd0/pubsub/google/cloud/pubsub_v1/gapic/publisher_client.py#L72-L73

**Comment by jonparrott** [comment]
I'm going to close this, these resource paths aren't useful without a client, and at any rate, we'd need to update the generator to do this.
