### ISSUE TITLE
AttributeError: 'str' object has no attribute 'authorize'

### ISSUE THREAD

**Issue by AziziShekoofeh** [GoogleCloudPlatform/google-cloud-python#4448]
Hi there,

I am trying to deploy a model stored on my google-cloud project by using google-cloud-python package. I basically want to make a call, and receive/read the output of the call on my local machine and not by using the console. So, there's a deal, I do have the problem in the very first step, with obtaining the credentials! 
I generate the .json file which is containing my credentials as it was explained and store them in my local machine and as it was explained in tutorial I passed the location using credential keyword. 

```
credentials = 'My First Project-Cred.json'
ml = discovery.build('ml', 'v1',  credentials=credentials)
```

I am using Python 2.7 on PyCharm and Linux. My gcloud version is  0.30.0 and you can see the traceback attached. 

```
Traceback (most recent call last):
  File "/home/minerva/Downloads/pycharm-community-2017.2.4/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/minerva/Downloads/pycharm-community-2017.2.4/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/AI/testAPI.py", line 25, in <module>
    ml = discovery.build('ml', 'v1',  credentials=credentials)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 232, in build
    credentials=credentials)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 375, in build_from_document
    http = _auth.authorized_http(credentials)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/_auth.py", line 104, in authorized_http
    return credentials.authorize(build_http())
AttributeError: 'str' object has no attribute 'authorize'

```
To be honest, I am very upset with the tutorials about gcloud, I expect more organized and complete one from Google. I even couldn't find any complete example to show the procedure completely. All of them are for calls from Console and not any local machine without using the console. Anyway, thanks :)

**Comment by dhermes** [comment]
@AziziShekoofeh 

`credentials` needs to be a credentials object. You've passed a path to the JSON file. The easiest way to accomplish what you want be to use application default credentials:

```python
import os
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'My First Project-Cred.json'
ml = discovery.build('ml', 'v1')
```

See https://googlecloudplatform.github.io/google-cloud-python/latest/core/auth.html for a longer description.

---

Also, it looks like you're using the [`google-api-python-client`][1] library, not this one.

----

Let us know if there is anything else needed. Cheers.

[1]: https://github.com/google/google-api-python-client

**Comment by AziziShekoofeh** [comment]
@dhermes Thanks. It was really helpful. :)
