### ISSUE TITLE
RPC that terminated with (StatusCode.UNKNOWN, Exception iterating requests!)

### ISSUE THREAD

**Issue by ravijo2** [GoogleCloudPlatform/google-cloud-python#4475]
I 'm getting follow error message on the client side. 
On the server side I do received the message, but getting error when trying to iterate on the server side as well.

Proto definition:
============

```
service chatServer {
  rpc msgExchange(stream chatMsg) returns (stream chatMsg) { }                                                 
}               
message chatMsg {
  int32 id = 1;
  string msg = 2;
}
```

Server snippet:
=============

```python
 def msgExchange(self, request_iterator, context):                                                           
        for from_agt in request_iterator:
            print("Collector received from Agent Id {}, message: {}".format(from_agt.id, from_agt.msg))
        i = 0
        for i in range(0, 3):
            yield collBuildChatMsg(i)
            i = i + 1
```

Client snippet:
===========

```python
            from_coll =chatStub.msgExchange(buildChatMsg())
            for coll_msg in from_coll:
                print("Collector response: Coll-Id={} Msg={}".format(coll_msg.id, coll_msg.msg))
```

Error on the Client side:
==================

```python
ERROR:root:Exception iterating requests!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/grpc/_channel.py", line 185, in consume_request_iterator
    request = next(request_iterator)
TypeError: chatMsg object is not an iterator
Requested RPC Failed
Traceback (most recent call last):
  File "client.py", line 97, in <module>
    client.agtRun()
  File "client.py", line 56, in agtRun
    for coll_msg in from_coll:
  File "/usr/local/lib/python2.7/site-packages/grpc/_channel.py", line 351, in next
    return self._next()
  File "/usr/local/lib/python2.7/site-packages/grpc/_channel.py", line 331, in _next
    raise self
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, Exception iterating requests!)>
```

**Comment by dhermes** [comment]
@ravijo2 Thanks for stopping by, but it looks like you have an issue with a gRPC API that you've defined yourself. This issue tracker is for `google-cloud-python` libraries (e.g. https://pypi.org/project/google-cloud-datastore/), so this isn't the right place for questions like this. Sorry.

I recommend filing this on the gRPC project (https://github.com/grpc/grpc/) of even better would be to ask on StackOverflow.
