### ISSUE TITLE
Firestore: INVALID_ARGUMENT error when updating with field name starting with number.

### ISSUE THREAD

**Issue by adamcjohnson** [GoogleCloudPlatform/google-cloud-python#4680]
2. Mac OS Sierra: 10.12.6
3. Python 3.6.3
5.
```python
Traceback (most recent call last):
  File "/Users/adamjohnson/Documents/Development/coinroll-scripts/env/lib/python3.6/site-packages/google/gax/api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)
  File "/Users/adamjohnson/Documents/Development/coinroll-scripts/env/lib/python3.6/site-packages/google/gax/retry.py", line 68, in inner
    return a_func(*updated_args, **kwargs)
  File "/Users/adamjohnson/Documents/Development/coinroll-scripts/env/lib/python3.6/site-packages/grpc/_channel.py", line 485, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/Users/adamjohnson/Documents/Development/coinroll-scripts/env/lib/python3.6/site-packages/grpc/_channel.py", line 435, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Invalid property path "24_hours".)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sandbox.py", line 41, in <module>
    'total_supply': '45887218.0'}, firestore.CreateIfMissingOption(True))
  File "/Users/adamjohnson/Documents/Development/coinroll-scripts/env/lib/python3.6/site-packages/google/cloud/firestore_v1beta1/document.py", line 371, in update
    write_results = batch.commit()
  File "/Users/adamjohnson/Documents/Development/coinroll-scripts/env/lib/python3.6/site-packages/google/cloud/firestore_v1beta1/batch.py", line 135, in commit
    transaction=None, options=self._client._call_options)
  File "/Users/adamjohnson/Documents/Development/coinroll-scripts/env/lib/python3.6/site-packages/google/cloud/firestore_v1beta1/gapic/firestore_client.py", line 851, in commit
    return self._commit(request, options)
  File "/Users/adamjohnson/Documents/Development/coinroll-scripts/env/lib/python3.6/site-packages/google/gax/api_callable.py", line 452, in inner
    return api_caller(api_call, this_settings, request)
  File "/Users/adamjohnson/Documents/Development/coinroll-scripts/env/lib/python3.6/site-packages/google/gax/api_callable.py", line 438, in base_caller
    return api_call(*args)
  File "/Users/adamjohnson/Documents/Development/coinroll-scripts/env/lib/python3.6/site-packages/google/gax/api_callable.py", line 380, in inner
    gax.errors.create_error('RPC failed', cause=exception))
  File "/Users/adamjohnson/Documents/Development/coinroll-scripts/env/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/Users/adamjohnson/Documents/Development/coinroll-scripts/env/lib/python3.6/site-packages/google/gax/api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)
  File "/Users/adamjohnson/Documents/Development/coinroll-scripts/env/lib/python3.6/site-packages/google/gax/retry.py", line 68, in inner
    return a_func(*updated_args, **kwargs)
  File "/Users/adamjohnson/Documents/Development/coinroll-scripts/env/lib/python3.6/site-packages/grpc/_channel.py", line 485, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/Users/adamjohnson/Documents/Development/coinroll-scripts/env/lib/python3.6/site-packages/grpc/_channel.py", line 435, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
google.gax.errors.InvalidArgumentError: InvalidArgumentError(RPC failed, caused by <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Invalid property path "24_hours".)>)
```

6. Attempt to perform an update to a document, using a field name that starts with a number.
7. `db.collection("Collection").document("document").update({"24_hours": "test"})`

**Comment by dhermes** [comment]
The error message explains the issue:

> "Invalid property path "24_hours"

I'm fairly certain [this][1] describes the rules for property names:

> A simple field name contains only characters `a` to `z`, `A` to `Z`, `0` to `9`, or `_`, and must not start with `0` to `9` or `_`. For example, `foo_bar_17`.

@samtstern Can you confirm / point to actual docs rather than a protobuf?

[1]: https://github.com/googleapis/googleapis/blob/79f9041f4ad4984bf57d9ac5f9cec2ac506c3b48/google/firestore/v1beta1/document.proto#L45-L47
