### ISSUE TITLE
Logging: sink reload throws exception if the sink has no filter

### ISSUE THREAD

**Issue by jceresini** [GoogleCloudPlatform/google-cloud-python#4696]
A KeyError exception for 'filter' is thrown when calling [sink].reload() if there is no filter. The API doesn't return a 'filter' key when retrieving the sink if its null.

```
Python 3.5.2
google-cloud-core (0.28.0)
google-cloud-logging (1.4.0)
```

## Simplified code example
```
logging_client = logging.Client(project_id)
sink = logging_client.sink(sink_name)
sink.reload()
```

## Raw API response for sink request (via gcloud)
```
 $ gcloud logging sinks list --project xxxx --log-http 
 =======================
 ==== request start ====
 uri: https://logging.googleapis.com/v2/projects/xxxx/sinks?alt=json
 method: GET
 [...]
 -- body start --
 {
   "sinks": [
     {
       "name": "xxxx",
       "destination": "storage.googleapis.com/xxxx",
       "outputVersionFormat": "V2",
       "writerIdentity": "serviceAccount:xxxx"
     }
   ]
 }
 
 -- body end --
 
 [...]
 NAME       DESTINATION                  FILTER
 xxxx       storage.googleapis.com/xxxx  (empty filter)
```
## Problematic code
/google/cloud/logging/sink.py Line 157
`self.filter_ = data['filter']`

## Traceback
```
Traceback (most recent call last):
  File "/[...]/python3.5/site-packages/xxxx", line 50, in _get_sink
    sink.reload()
  File "[...]/python3.5/site-packages/google/cloud/logging/sink.py", line 157, in reload
    self.filter_ = data['filter']
KeyError: 'filter'
```

**Comment by tseaver** [comment]
@jceresini Thanks for the report!  I think maybe the `filter` argument used to be required on the back-end, and so we never saw this case.
