### ISSUE TITLE
TypeError: setproxy() takes at most 7 arguments (8 given)

### ISSUE THREAD

**Issue by mas-dse-greina** [GoogleCloudPlatform/google-cloud-python#4783]
I'm trying to install Google Cloud Platform on a Mac. I am getting this error during the install:

ganthony-mac01:~ ganthony$ google-cloud-sdk/install.sh
Welcome to the Google Cloud SDK!

To help improve the quality of this product, we collect anonymized usage data
and anonymized stacktraces when crashes are encountered; additional information
is available at <https://cloud.google.com/sdk/usage-statistics>. You may choose
to opt out of this collection now (by choosing 'N' at the below prompt), or at
any time in the future by running the following command:

    gcloud config set disable_usage_reporting true

Do you want to help improve the Google Cloud SDK (Y/n)?  Y

Traceback (most recent call last):
  File "/Users/ganthony/google-cloud-sdk/bin/bootstrapping/install.py", line 214, in <module>
    main()
  File "/Users/ganthony/google-cloud-sdk/bin/bootstrapping/install.py", line 192, in main
    Install(pargs.override_components, pargs.additional_components)
  File "/Users/ganthony/google-cloud-sdk/bin/bootstrapping/install.py", line 138, in Install
    _CLI.Execute(['--quiet', 'components', 'list'])
  File "/Users/ganthony/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 823, in Execute
    self._HandleAllErrors(exc, command_path_string, specified_arg_names)
  File "/Users/ganthony/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 861, in _HandleAllErrors
    exceptions.HandleError(exc, command_path_string, self.__known_error_handler)
  File "/Users/ganthony/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 797, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/ganthony/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 757, in Run
    resources = command_instance.Run(args)
  File "/Users/ganthony/google-cloud-sdk/lib/surface/components/list.py", line 95, in Run
    only_local_state=args.only_local_state)
  File "/Users/ganthony/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 669, in List
    to_print, current_version, latest_version = self._GetPrintListWithDiff()
  File "/Users/ganthony/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 699, in _GetPrintListWithDiff
    _, diff = self._GetStateAndDiff(command_path='components.list')
  File "/Users/ganthony/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 595, in _GetStateAndDiff
    command_path=command_path)
  File "/Users/ganthony/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 578, in _GetLatestSnapshot
    *effective_url.split(','), command_path=command_path)
  File "/Users/ganthony/google-cloud-sdk/lib/googlecloudsdk/core/updater/snapshots.py", line 171, in FromURLs
    for url in urls]
  File "/Users/ganthony/google-cloud-sdk/lib/googlecloudsdk/core/updater/snapshots.py", line 192, in _DictFromURL
    response = installers.ComponentInstaller.MakeRequest(url, command_path)
  File "/Users/ganthony/google-cloud-sdk/lib/googlecloudsdk/core/updater/installers.py", line 285, in MakeRequest
    return ComponentInstaller._RawRequest(req, timeout=timeout)
  File "/Users/ganthony/google-cloud-sdk/lib/googlecloudsdk/core/updater/installers.py", line 329, in _RawRequest
    should_retry_if=RetryIf, sleep_ms=500)
  File "/Users/ganthony/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 155, in TryFunc
    return func(*args, **kwargs), None
  File "/Users/ganthony/google-cloud-sdk/lib/googlecloudsdk/core/url_opener.py", line 73, in urlopen
    return opener.open(req, data, timeout)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Users/ganthony/google-cloud-sdk/lib/googlecloudsdk/core/url_opener.py", line 58, in https_open
    return self.do_open(build, req)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/Users/ganthony/google-cloud-sdk/lib/third_party/httplib2/python2/httplib2/__init__.py", line 1051, in connect
    sock.setproxy(proxy_type, proxy_host, proxy_port, proxy_rdns, proxy_user, proxy_pass, proxy_headers)
TypeError: setproxy() takes at most 7 arguments (8 given)

**Comment by mas-dse-greina** [comment]
I just noticed that my MacOS python is 3.6.3. Maybe it is that?

**Comment by tseaver** [comment]
@mas-dse-greina I'm sorry to say you've reached the wrong site for Google Cloud SDK support:  this repository is where we manage Python wrapper libraries for Google Cloud APIs, which is a (subtly) different thing.

Please see the resources on its [support page](https://cloud.google.com/sdk/docs/community-support).
