### ISSUE TITLE
Version 188 installation succeeds on EC2, but fails on GCE

### ISSUE THREAD

**Issue by BanzaiMan** [GoogleCloudPlatform/google-cloud-python#4855]
1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types

N/A

2. OS type and version

  Ubuntu 14.04 

3. Python version and virtual environment information `python --version`

2.7.6

4. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`

188

5. Stacktrace if available

```
Traceback (most recent call last):
  File "/home/travis/google-cloud-sdk/bin/bootstrapping/install.py", line 214, in <module>
    main()
  File "/home/travis/google-cloud-sdk/bin/bootstrapping/install.py", line 192, in main
    Install(pargs.override_components, pargs.additional_components)
  File "/home/travis/google-cloud-sdk/bin/bootstrapping/install.py", line 134, in Install
    InstallOrUpdateComponents(to_install, update=update)
  File "/home/travis/google-cloud-sdk/bin/bootstrapping/install.py", line 177, in InstallOrUpdateComponents
    ['--quiet', 'components', verb, '--allow-no-backup'] + component_ids)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 823, in Execute
    self._HandleAllErrors(exc, command_path_string, specified_arg_names)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 861, in _HandleAllErrors
    exceptions.HandleError(exc, command_path_string, self.__known_error_handler)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 797, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 757, in Run
    resources = command_instance.Run(args)
  File "/home/travis/google-cloud-sdk/lib/surface/components/update.py", line 106, in Run
    version=args.version)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 987, in Update
    self._PostProcess(snapshot=diff.latest)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 1473, in _PostProcess
    err_func=log.file_only_logger.debug)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/execution_utils.py", line 286, in Exec
    env = _GetToolEnv(env=env)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/execution_utils.py", line 145, in _GetToolEnv
    env, p.EnvironmentName(), p.Get(required=False, validate=False))
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1557, in Get
    required)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1856, in _GetProperty
    value = _GetPropertyWithoutDefault(prop, properties_file)
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1894, in _GetPropertyWithoutDefault
    value = callback()
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 217, in GetAccount
    return c_gce.Metadata().DefaultAccount()
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py", line 85, in DefaultAccount
    http_errors_to_ignore=(404,))
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 289, in DecoratedFunction
    six.reraise(to_reraise[0], to_reraise[1], to_reraise[2])
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 159, in TryFunc
    return func(*args, **kwargs), None
  File "/home/travis/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py", line 45, in _ReadNoProxyWithCleanFailures
    except urllib.request.HTTPError as e:
AttributeError: 'Module_six_moves_urllib_request' object has no attribute 'HTTPError'
```

6. Steps to reproduce

https://travis-ci.org/BanzaiMan/travis_production_test/jobs/339011601#L462

Here, I am running the install script from https://sdk.cloud.google.com. The installation appears to go well, but in the post processing steps the `install.py` fails with the error above.

A curious thing is that the same process works if we do it in a container running on AWS EC2: https://travis-ci.org/BanzaiMan/travis_production_test/jobs/339011598#L452

I am so far unable to explain this apparent discrepancy.

In https://github.com/travis-ci/travis-ci/issues/9200, it is reported that this was working yesterday (which I believe was installing version 187).

7. Code example

Using GitHub flavored markdown can help make your request clearer.
See: https://guides.github.com/features/mastering-markdown/

**Comment by jonparrott** [comment]
HI @BanzaiMan, unfortunately this issue tracker is for the Python client libraries, not for the Google Cloud SDK. You'll need to file this bug over at https://issuetracker.google.com/savedsearches/559662.

**Comment by BanzaiMan** [comment]
My apologies.
