### ISSUE TITLE
Datastore: TypeError: request() takes at least 2 arguments (3 given)

### ISSUE THREAD

**Issue by Djabx** [GoogleCloudPlatform/google-cloud-python#4876]
Hi,

I've got an application on GAE (standard) that use a DAO of mine witch purpose is to also work on Kubernetes.

```
import logging
import cloudstorage as gcs
from google.cloud import datastore

datastore_client = datastore.Client()

def get_task(image_id):
    k = datastore_client.key('ImageTask', image_id)
    tsk = datastore.Entity(
        key=k,
        exclude_from_indexes=['image_geom', 'mask'])

    if 'created_at' not in tsk:
        logging.info('creating task for image: %s', image_id)
        tsk['image_id'] = image_id
        tsk['created_at'] = datetime.datetime.utcnow()

    return tsk

[...]

def save_tsk(tsk):
    datastore_client.put(tsk)
```

But when I save something, I've got:
```
Traceback (most recent call last):

File "/base/data/home/apps/<myapp>/<a date>/lib/flask/app.py", line 1982, in wsgi_app
 response = self.full_dispatch_request() 
File "/base/data/home/apps/<myapp>/<a date>/lib/flask/app.py", line 1614, in full_dispatch_request
 rv = self.handle_user_exception(e) 
File "/base/data/home/apps/<myapp>/<a date>/lib/flask/app.py", line 1517, in handle_user_exception
 reraise(exc_type, exc_value, tb) 
File "/base/data/home/apps/<myapp>/<a date>/lib/flask/app.py", line 1612, in full_dispatch_request
 rv = self.dispatch_request() 
File "/base/data/home/apps/<myapp>/<a date>/lib/flask/app.py", line 1598, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args) 
File "/base/data/home/apps/<myapp>/<a date>/main.py", line 77, in metadata
 controller.download_metadata(tsk) 
File "/base/data/home/apps/<myapp>/<a date>/controller.py", line 90, in download_metadata
 save_tsk(tsk) 
File "/base/data/home/apps/<myapp>/<a date>/controller.py", line 47, in save_tsk
 dao_cont.save_tsk(tsk) 
File "/base/data/home/apps/<myapp>/<a date>/lib/dao_cont.py", line 181, in save_tsk
 datastore_client.put(tsk) 
File "/base/data/home/apps/<myapp>/<a date>/lib/google/cloud/datastore/client.py", line 384, in put
 self.put_multi(entities=[entity]) 
File "/base/data/home/apps/<myapp>/<a date>/lib/google/cloud/datastore/client.py", line 411, in put_multi
 current.commit() 
File "/base/data/home/apps/<myapp>/<a date>/lib/google/cloud/datastore/batch.py", line 273, in commit
 self._commit() 
File "/base/data/home/apps/<myapp>/<a date>/lib/google/cloud/datastore/batch.py", line 249, in _commit
 self.project, mode, self._mutations, transaction=self._id) 
File "/base/data/home/apps/<myapp>/<a date>/lib/google/cloud/datastore/_http.py", line 264, in commit
 request_pb, _datastore_pb2.CommitResponse) 
File "/base/data/home/apps/<myapp>/<a date>/lib/google/cloud/datastore/_http.py", line 111, in _rpc
 http, project, method, req_data, base_url) 
File "/base/data/home/apps/<myapp>/<a date>/lib/google/cloud/datastore/_http.py", line 72, in _request
 url=api_url, method='POST', headers=headers, data=data) TypeError: request() takes at least 2 arguments (3 given)
```

My `lib` folder is like this:

```
$ ls ./lib | grep dist-info
cachetools-2.0.1.dist-info
certifi-2018.1.18.dist-info
chardet-3.0.4.dist-info
click-6.7.dist-info
dill-0.2.7.1.dist-info
enum34-1.1.6.dist-info
Flask-0.12.2.dist-info
future-0.16.0.dist-info
futures-3.2.0.dist-info
gapic_google_cloud_datastore_v1-0.15.3.dist-info
gapic_google_cloud_pubsub_v1-0.15.4.dist-info
geojson-2.3.0.dist-info
google_api_core-0.1.4.dist-info
google_api_python_client-1.6.5.dist-info
googleapis_common_protos-1.5.3.dist-info
GoogleAppEngineCloudStorageClient-1.9.22.1.dist-info
google_auth-1.4.1.dist-info
google_auth_httplib2-0.0.3.dist-info
google_cloud_core-0.25.0.dist-info
google_cloud_datastore-1.4.0.dist-info
google_cloud_pubsub-0.26.0.dist-info
google_gax-0.15.16.dist-info
grpc_google_iam_v1-0.11.4.dist-info
grpcio-1.9.1.dist-info
httplib2-0.10.3.dist-info
idna-2.6.dist-info
itsdangerous-0.24.dist-info
Jinja2-2.10.dist-info
MarkupSafe-1.0.dist-info
oauth2client-4.1.2.dist-info
ply-3.8.dist-info
protobuf-3.5.1.dist-info
proto_google_cloud_datastore_v1-0.90.4.dist-info
proto_google_cloud_pubsub_v1-0.15.4.dist-info
pyasn1-0.4.2.dist-info
pyasn1_modules-0.2.1.dist-info
pytz-2018.3.dist-info
requests-2.18.4.dist-info
rsa-3.4.2.dist-info
setuptools-38.5.1.dist-info
six-1.11.0.dist-info
uritemplate-3.0.0.dist-info
urllib3-1.22.dist-info
Werkzeug-0.12.2.dist-info
```

What did I do wrong ?

**Comment by tseaver** [comment]
It looks like the `http` attribute of the client is not the default type:  can you get a breakpoint set at the point of the error and check the following?

```python
(pdb) pp type(http)
```

**Comment by Djabx** [comment]
Dumb question: how do you debug a gae application ?

**Comment by jonparrott** [comment]
i there, unfortunately the cloud client libraries are not yet supported on App Engine standard. We're working on it and you can follow progress at GoogleCloudPlatform/google-cloud-python#1893.

For GAE standard and datastore, I recommend you use the built-in `ndb` library.

If you want to continue debugging on this, I'm happy to help.
