### ISSUE TITLE
Google Storage: Intermittent New Connection Errors

### ISSUE THREAD

**Issue by kierkegaard13** [GoogleCloudPlatform/google-cloud-python#4933]
OS: Ubuntu 17.10
Python version: 3.6 (Miniconda 4.3.14)
google-storage version: 1.6.0
other info: running inside of a dockerized container on a gcloud instance in GCP
stacktrace:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/conda/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0d22a00c88>: Failed to establish a new connection: [Errno 111] Connection refused
```

Connection code:
```
def __init__(self, bucket_name=settings.GCLOUD_BUCKET, project=settings.GCLOUD_PROJECT):                                                                                                             
          self.project = project                                                                                                                                                                           
          self.bucket_name = bucket_name                                                                                                                                                                   
          self.client = storage.Client(self.project)
```

I'm able to use google cloud storage and connect, download, and upload object, but every now and then, I get the above connection errors. The only thing I can think of is that I re-create the client every so often (which I can easily avoid), but I'm wondering if there's something else going on here.

**Comment by jonparrott** [comment]
Unfortunately there isn't a lot we can do for you here. Networking inside Docker has lots of options and lots of ways things can go wrong. 

We have helpers in [api_core](https://google-cloud-python.readthedocs.io/en/latest/core/retry.html) for retrying things, but low-level network errors like this are generally a sign of lack of network connectivity (however intermittent) and are generally "fatal".

**Comment by kierkegaard13** [comment]
Ah, well I guess I'll see if I can play with docker network settings. Thanks for the help.

**Comment by jeetpatel9** [comment]
@kierkegaard13  were you able to figure out anything for this? I am facing the same issue with `django storages`
