### ISSUE TITLE
[google-cloud-storage] SSLError when calling blob.make_public()

### ISSUE THREAD

**Issue by chaitanyanettem** [GoogleCloudPlatform/google-cloud-python#4941]
# Thank you for reporting an issue to google-cloud-python!
OS: Ubuntu 16.04
Python: 3.5.2
google-cloud-storage: 1.6.0

I'm calling `blob.make_public()` inside a function which is running in a celery thread and occasionally it fails with a -

```
requests.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac
```

Reading a previous thread about a similar issue (https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3501) makes me believe that the cloud storage client should be thread safe. So let me know if this is not a thread safety issue.

Stacktrace:
```
Traceback (most recent call last):
  File "/home/chaitanya/project/asset-tasks/venv/lib/python3.5/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/chaitanya/project/asset-tasks/venv/lib/python3.5/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/chaitanya/project/asset-tasks/ingestion.py", line 268, in process_task
    asset_service.make_blob_public(blob_name)
  File "/home/chaitanya/project/libasset/libasset/services/asset.py", line 113, in make_blob_public
    blob.make_public()
  File "/home/chaitanya/project/asset-tasks/venv/lib/python3.5/site-packages/google/cloud/storage/blob.py", line 1233, in make_public
    self.acl.all().grant_read()
  File "/home/chaitanya/project/asset-tasks/venv/lib/python3.5/site-packages/google/cloud/storage/acl.py", line 360, in all
    return self.entity('allUsers')
  File "/home/chaitanya/project/asset-tasks/venv/lib/python3.5/site-packages/google/cloud/storage/acl.py", line 315, in entity
    if self.has_entity(entity):
  File "/home/chaitanya/project/asset-tasks/venv/lib/python3.5/site-packages/google/cloud/storage/acl.py", line 266, in has_entity
    self._ensure_loaded()
  File "/home/chaitanya/project/asset-tasks/venv/lib/python3.5/site-packages/google/cloud/storage/acl.py", line 209, in _ensure_loaded
    self.reload()
  File "/home/chaitanya/project/asset-tasks/venv/lib/python3.5/site-packages/google/cloud/storage/acl.py", line 421, in reload
    query_params=query_params,
  File "/home/chaitanya/project/asset-tasks/venv/lib/python3.5/site-packages/google/cloud/_http.py", line 290, in api_request
    headers=headers, target_object=_target_object)
  File "/home/chaitanya/project/asset-tasks/venv/lib/python3.5/site-packages/google/cloud/_http.py", line 183, in _make_request
    return self._do_request(method, url, headers, data, target_object)
  File "/home/chaitanya/project/asset-tasks/venv/lib/python3.5/site-packages/google/cloud/_http.py", line 212, in _do_request
    url=url, method=method, headers=headers, data=data)
  File "/home/chaitanya/project/asset-tasks/venv/lib/python3.5/site-packages/google/auth/transport/requests.py", line 186, in request
    method, url, data=data, headers=request_headers, **kwargs)
  File "/home/chaitanya/project/asset-tasks/venv/lib/python3.5/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/chaitanya/project/asset-tasks/venv/lib/python3.5/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/chaitanya/project/asset-tasks/venv/lib/python3.5/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1977)
```

**Comment by tseaver** [comment]
`google-cloud-storage` is now using the `requests` library, which means that the clients are shareable between threads.

What version of the `google-auth` library are you using?

@jonparrott Does this ring any bells for you?

**Comment by chaitanyanettem** [comment]
`google-auth` is version 1.2.1.

**Comment by jonparrott** [comment]
I'm a bit at a loss - this is highly unusual. Our clients should be threadsafe but if they weren't then this wouldn't be the error they would get. This indicates an issue with the threadsafety of requests/urllib3/openssl.

@chaitanyanettem can you let us know your openssl version?

@Lukasa - I found [this old thing](), is this the same weirdness or something else?

**Comment by tseaver** [comment]
@jonparrott The link in your last comment is pointing to this issue.

**Comment by jonparrott** [comment]
Should be pointing to https://github.com/requests/requests/issues/1906

**Comment by chaitanyanettem** [comment]
`openssl version` gives me -

OpenSSL 1.0.2g  1 Mar 2016

**Comment by jonparrott** [comment]
That's pretty dated, I'm curious if it's an issue with older openssls. Can you try updating it?

**Comment by chaitanyanettem** [comment]
Sure, I'll try that.

**Comment by chaitanyanettem** [comment]
So, I'm running all of this on a GCP compute instance with the Ubuntu 16.04 image that Google provides. I tried to upgrade by -

```
sudo apt-get update
sudo apt-get upgrade openssl
```

I just got this message - `openssl is already the newest version (1.0.2g-1ubuntu4.10).`

**Comment by jonparrott** [comment]
It seems like you will need to build openssl & python from source to confirm that that is the source of the problem, or try using a newer ubuntu or backports.

**Comment by tseaver** [comment]
@chemelnucfin I've recategorized this as a question (the problem appears to be in the OP's environment, not our library) and removed it from the "P2 Bugs" project.

**Comment by SwapnilSoni1999** [comment]
its 2019 end and still facing same issue
