### ISSUE TITLE
PubSub client isn't thread-safe

### ISSUE THREAD

**Issue by raybotha** [GoogleCloudPlatform/google-cloud-python#5013]
Using Python 3.6 and green threads with eventlet, the client for PubSub gives SSL errors like below when called from another thread.
```
AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fc4c824f0b8>" raised exception!
Traceback (most recent call last):
  File "/home/ray/.virtualenvs/exchange-streaming/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/home/ray/.virtualenvs/exchange-streaming/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1806, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/ray/.virtualenvs/exchange-streaming/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1539, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')
```

**Comment by jonparrott** [comment]
I don't *think* this is an issue with this library, but rather that gRPC doesn't support gevent/greenlet and that I'm unsure of requests/urllib3's support.

Closing this in favor of https://github.com/grpc/grpc/issues/4629
