### ISSUE TITLE
storage: blob.rewrite() does not work with batches

### ISSUE THREAD

**Issue by bits01** [GoogleCloudPlatform/google-cloud-python#5068]
google-cloud-storage v1.8.0

Not sure whether rewrites are supposed to work when batched, but it would be nice and useful if they did, otherwise there's no efficient way to copy lots of blobs across buckets in different locations or with different encryption keys.

Example:
```
with gcs_client.batch():
    dest_blob.rewrite(src_blob)
```
Traceback:
```
Traceback (most recent call last):
  File "batch_test.py", line 10, in <module>
    dest_blob.rewrite(src_blob)
  File ".../pyvirtenv/python-common/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 1359, in rewrite
    rewritten = int(api_response['totalBytesRewritten'])
  File ".../pyvirtenv/python-common/lib/python2.7/site-packages/google/cloud/storage/batch.py", line 105, in __getitem__
    raise KeyError('Cannot get item %r from a future' % (key,))
KeyError: "Cannot get item 'totalBytesRewritten' from a future"
```

**Comment by tseaver** [comment]
I'm afraid that the current batch implementation does not deal well with *any* methods whose return values depend on the response payload (as opposed to just being able to update the relevant blobs / buckets from those responses when the batch completes).

Adding support for such methods would be a *large* undertaking.

**Comment by bits01** [comment]
Could the issue be left open and marked as a future enhancement request?

**Comment by chemelnucfin** [comment]
@bits01 I have added this issue to our [feature request project](https://github.com/GoogleCloudPlatform/google-cloud-python/projects/5#card-8278375)

**Comment by bits01** [comment]
Thank you. Should the issue be re-opened then? It's currently marked `closed`.

**Comment by IlyaFaer** [comment]
I think, it can be done in fashion of: https://github.com/googleapis/google-cloud-python/pull/8618. But first it's better to deal with 8616

**Comment by tseaver** [comment]
@IlyaFaer, what is the issue that needs to be dealt with first?  #8616 doesn't seem related.

**Comment by IlyaFaer** [comment]
@tseaver, sorry, mistake, 8618. I'm waiting for review in it, and if changes will be accepted, we could use something alike in this issue

**Comment by verasativa** [comment]
Just to be clear: at this moment **the most reliable way**  to copy a lots of files from one bucket to another (retry strategy, batch requests and object rewrite) in python is `subprocess.run(["gsutil", "cp",...])` ?

I was comparing contributors here to gsutil repo, and looks like are totally different and isolated teams, why?
