### ISSUE TITLE
BigQuery: Error in get_table for federated BigTable table when no columns defined

### ISSUE THREAD

**Issue by jasper-smith** [GoogleCloudPlatform/google-cloud-python#5144]
Call to get_table when referencing a federated BigTable table where no columns were defined upon creation results in error "KeyError: 'columns'" (not unexpected as there aren't any in the api response - see attached file). Since this is a valid federated table definition the call should not error when no columns are present within a columnFamily. Creating the same federated BigTable table and defining at least 1 column explicitly in the table definition results in no error from the same code.

OS X 10.11.6
Python 3.6.1
google-cloud-bigquery 0.31.0

```python
from google.cloud import bigquery

projectID = 'x'
datasetID = 'x'
tableID   = 'x'

client = bigquery.Client(project=projectID)
dataset_ref = client.dataset(datasetID)
table_ref = dataset_ref.table(tableID)

t = client.get_table(table_ref)
```

Error details :
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    t = client.get_table(table_ref)
  File "/Users/jaspersmith/Documents/Gitlab/bq-tools/venv/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 317, in get_table
    return Table.from_api_repr(api_response)
  File "/Users/jaspersmith/Documents/Gitlab/bq-tools/venv/lib/python3.6/site-packages/google/cloud/bigquery/table.py", line 732, in from_api_repr
    table._set_properties(resource)
  File "/Users/jaspersmith/Documents/Gitlab/bq-tools/venv/lib/python3.6/site-packages/google/cloud/bigquery/table.py", line 748, in _set_properties
    self.external_data_configuration = ExternalConfig.from_api_repr(ec)
  File "/Users/jaspersmith/Documents/Gitlab/bq-tools/venv/lib/python3.6/site-packages/google/cloud/bigquery/external_config.py", line 488, in from_api_repr
    config._options = optcls.from_api_repr(opts)
  File "/Users/jaspersmith/Documents/Gitlab/bq-tools/venv/lib/python3.6/site-packages/google/cloud/bigquery/external_config.py", line 249, in from_api_repr
    for cf in resource['columnFamilies']]
  File "/Users/jaspersmith/Documents/Gitlab/bq-tools/venv/lib/python3.6/site-packages/google/cloud/bigquery/external_config.py", line 249, in <listcomp>
    for cf in resource['columnFamilies']]
  File "/Users/jaspersmith/Documents/Gitlab/bq-tools/venv/lib/python3.6/site-packages/google/cloud/bigquery/external_config.py", line 186, in from_api_repr
    for c in resource['columns']]
KeyError: 'columns'
```

[BQ Tables get API response.txt](https://github.com/GoogleCloudPlatform/google-cloud-python/files/1876317/BQ.Tables.get.API.response.txt)

**Comment by tseaver** [comment]
@jasper-smith Thanks for the report!  This bug was fixed in PR #5107, which was part of the `bigquery-1.0.0` release (2018-04-11).
