### ISSUE TITLE
Speech - RecognitionConfig has no enableAutomaticPunctuation field

### ISSUE THREAD

**Issue by albertlai** [GoogleCloudPlatform/google-cloud-python#5175]
Trying to use the Python google speech client lib using the new enableAutomaticPunctuation field but it throws an error. The use_enhanced, model, and metadata fields all work correctly.

So this works:
```
        config = types.RecognitionConfig(
            encoding=enums.RecognitionConfig.AudioEncoding.FLAC,
            language_code='en-US',
            use_enhanced=True,
            model='phone_call',
            metadata=metadata,
        )
```
this gives an error:
```
        config = types.RecognitionConfig(
            encoding=enums.RecognitionConfig.AudioEncoding.FLAC,
            language_code='en-US',
            use_enhanced=True,
            model='phone_call',
            metadata=metadata,
            enableAutomaticPunctuation=True,
        )
```

```
  File "/Users/albertlai/venv/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 484, in init
    field = _GetFieldByName(message_descriptor, field_name)
  File "/Users/albertlai/venv/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 548, in _GetFieldByName
    (message_descriptor.name, field_name))
ValueError: Protocol message RecognitionConfig has no "enableAutomaticPunctuation" field.
```

Python v3.5.1
google-cloud-speech version v0.33.0
googleapis-common-protos v1.5.3

**Comment by albertlai** [comment]
Oops saw my own error, should have used enable_automatic_punctuation=True

**Comment by nick-jonas** [comment]
I'm getting a similar issue for both ```model``` and ```use_enhanced```:

```
Traceback (most recent call last):
  File "transcribe_streaming_mic.py", line 201, in <module>
    record_utterance()
  File "transcribe_streaming_mic.py", line 177, in record_utterance
    language_code=language_code)
  File "/home/pi/.local/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 484, in init
    field = _GetFieldByName(message_descriptor, field_name)
  File "/home/pi/.local/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 548, in _GetFieldByName
    (message_descriptor.name, field_name))
ValueError: Protocol message RecognitionConfig has no "use_enhanced" field.
```

Python v3.5.3
google-cloud-speech==0.34.0
googleapis-common-protos==1.5.3

Data logging is enabled on the project, and my ~/.profile has exported my service account creds:

```export GOOGLE_APPLICATION_CREDENTIALS="/home/pi/dev/xxxxxxxxxxxxxxxxxxxxx.json"```

**Comment by nick-jonas** [comment]
Ah it works when importing ```google.cloud.speech_v1p1beta1``` instead of ```google.cloud.speech```

**Comment by The-Gupta** [comment]
@nick-jonas , even with importing `google.cloud.speech_v1p1beta1 ` I get 

> ValueError: Protocol message RecognitionConfig has no "model" field.

Same as using `google.cloud.speech`.

**Comment by The-Gupta** [comment]
@nick-jonas, It worked after enabling **data logging**.
