### ISSUE TITLE
Bigquery: KeyError: 'configuration'

### ISSUE THREAD

**Issue by krelst** [GoogleCloudPlatform/google-cloud-python#5220]
We are using `google-cloud-bigquery==0.32.0`, and have an hourly script that monitors the status of async queries. The code basically looks like this:
```
from google.cloud import bigquery

bq_client = bigquery.Client(project=GCLOUD_PROJECT_ID_BIGQUERY)
all_jobs = bq_client.list_jobs(all_users=True)
for job in all_jobs:
	analyse_job(job)
```
Excerpt of installed google cloud packages:
```
google-api-core==1.1.1
google-api-python-client==1.6.6
google-auth==1.4.1
google-auth-httplib2==0.0.3
google-cloud-bigquery==0.32.0
google-cloud-core==0.28.1
google-cloud-monitoring==0.28.1
google-cloud-storage==1.8.0
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3
```
Starting from 20/04/2018 08:00 AM UTC the script started to fail with the following stacktrace:
```
Traceback (most recent call last):
14:26:19			  File "/home/script_repos/bigquery/monitor_jobs.py", line 214, in <module>
14:26:19			    main()
14:26:19			  File "/home/script_repos/bigquery/monitor_jobs.py", line 175, in main
14:26:19			    for idx, job in enumerate(all_jobs):
14:26:19			  File "/home/script_repos/bigquery/lib/python2.7/site-packages/google/api_core/page_iterator.py", line 200, in _items_iter
14:26:19			    for item in page:
14:26:19			  File "/home/script_repos/bigquery/lib/python2.7/site-packages/google/api_core/page_iterator.py", line 125, in next
14:26:19			    result = self._item_to_value(self._parent, item)
14:26:19			  File "/home/script_repos/bigquery/lib/python2.7/site-packages/google/cloud/bigquery/client.py", line 1396, in _item_to_job
14:26:19			    return iterator.client.job_from_resource(resource)
14:26:19			  File "/home/script_repos/bigquery/lib/python2.7/site-packages/google/cloud/bigquery/client.py", line 554, in job_from_resource
14:26:19			    config = resource['configuration']
14:26:19			KeyError: 'configuration'
```
Strange thing is that with the exact same virtual environment on my local computer, I don't get this error. My local dev computer is a macOS High Sierra 10.13.3, while the server is running CentOS Linux 7. Both use Python 2.7.12. Do you guys have any idea what can possibly cause the error and why I am not seeing it locally?

**Comment by tseaver** [comment]
When the failure occurs, what is the `resource` which it is trying to parse?  Can you dump the JSON and redact any sensitive values?

**Comment by krelst** [comment]
On the server the following resource causes the issue:
```
{
  "status": {
    "state": "DONE",
    "errors": [
      {
        "reason": "notFound",
        "message": "Not found: Table <project_id>:<dataset_name>.<table_name>. Please verify that the table exists and the correct location was used for the job."
      }
    ],
    "errorResult": {
      "reason": "notFound"
    }
  },
  "kind": "bigquery#job",
  "statistics": {
    "endTime": "1524553216119",
    "creationTime": "1524553216088",
    "startTime": "1524553216119"
  },
  "jobReference": {
    "projectId": "<project_id>",
    "jobId": "<REDACTED>"
  },
  "state": "DONE",
  "id": "<project_id>:<REDACTED>",
  "errorResult": {
    "reason": "notFound"
  }
}
```
Locally I receive for the same query the following resource:
```
{
  "status": {
    "state": "DONE",
    "errors": [
      {
        "reason": "notFound",
        "message": "Not found: Table <project_id>:<dataset_name>.<table_name>. Please verify that the table exists and the correct location was used for the job."
      }
    ],
    "errorResult": {
      "reason": "notFound",
      "message": "Not found: Table <project_id>:<dataset_name>.<table_name>. Please verify that the table exists and the correct location was used for the job."
    }
  },
  "kind": "bigquery#job",
  "statistics": {
    "endTime": "1524553216119",
    "creationTime": "1524553216088",
    "startTime": "1524553216119"
  },
  "jobReference": {
    "projectId": "<project_id>",
    "jobId": "<job_id>"
  },
  "state": "DONE",
  "user_email": "<service_account>",
  "configuration": {
    "query": {
      "query": "<query>",
      "useQueryCache": false
    }
  },
  "id": "<project_id>:<job_id>",
  "errorResult": {
    "reason": "notFound",
    "message": "Not found: Table <project_id>:<dataset_name>.<table_name>. Please verify that the table exists and the correct location was used for the job."
  }
}
```
Is it a difference in service account rights that is causing the difference between the two resources?

**Comment by tseaver** [comment]
@tswast Can you suggest a reason why the first example resource would be missing the `configuration` key?

**Comment by tswast** [comment]
I have no idea how a job could be missing a configuration.

@shollyman do you have any ideas?

**Comment by hokumski** [comment]
Have same issue, but as I remember my json contains some debug information like execution plan.
I'll post it tomorrow.

**Comment by shollyman** [comment]
This is a case where the user/principal issuing the jobs.list request lacks the `bigquery.jobs.listAll `permission, a new permission that clarifies when metadata for other users can be inspected.
Because the identity lacks this information, job information is redacted (you can see the jobID is redacted above, as well as the configuration submessage.

Adding the permission, either via a custom role or by using a curated role (`bigquery.admin`) to the user at the project level should correct this.

The project owner(s) should have received an email about this change, and how the behavior would be changing after April 18.  More details about the permissions and access control can be found https://cloud.google.com/bigquery/docs/access-control

**Comment by hokumski** [comment]
@shollyman 
This is not my case. 
I have cron job for listing and saving job results, both BQ job start and list_jobs are made under one service account. 
It looks like something was wrong during job execution, and then this job couldn't be listed

**Comment by shollyman** [comment]
@hokumski Feel free to send me the details out of band, we may undupe 5238 if its something different.

**Comment by krelst** [comment]
Adding `bigquery.admin` rights indeed solved the issue. However I don't think it's desirable behaviour to let the client crash with a `KeyError` when it hasn't got the correct permissions.

**Comment by hokumski** [comment]
@shollyman 

This is from me:

`
{
  "status": {
    "state": "DONE"
  },
  "kind": "bigquery#job",
  "statistics": {
    "query": {
      "totalSlotMs": "732",
      "queryPlan": [
        {
          "readMsMax": "27",
          "computeMsMax": "6",
          "waitMsAvg": "11",
          "id": "0",
          "endMs": "1524217492753",
          "waitMsMax": "22",
          "startMs": "1524217492054",
          "waitRatioMax": 0.033950617283950615,
          "readRatioAvg": 0.038580246913580245,
          "parallelInputs": "2",
          "recordsRead": "59",
          "computeRatioAvg": 0.0092592592592592587,
          "writeMsAvg": "574",
          "status": "COMPLETE",
          "writeMsMax": "648",
          "computeMsAvg": "6",
          "shuffleOutputBytesSpilled": "0",
          "writeRatioMax": 1.0,
          "readMsAvg": "25",
          "waitRatioAvg": 0.016975308641975308,
          "completedParallelInputs": "2",
          "computeRatioMax": 0.0092592592592592587,
          "name": "S00: Input",
          "shuffleOutputBytes": "2779",
          "recordsWritten": "59",
          "readRatioMax": 0.041666666666666664,
          "steps": [
            {
              "kind": "READ",
              "substeps": [
                "_PARTITIONTIME, column1, column2, column3, column4",
                "FROM project:dataset.table1 AS project:dataset.table1",
                "WHERE LOGICAL_AND(GREATER_OR_EQUAL(_PARTITIONTIME, 1524182400000000), LESS(_PARTITIONTIME, 1524268800000000))"
              ]
            },
            {
              "kind": "LIMIT",
              "substeps": [
                "1000"
              ]
            },
            {
              "kind": "WRITE",
              "substeps": [
                "column1, column2, column3, column4",
                "TO __stage00_output"
              ]
            }
          ],
          "writeRatioAvg": 0.88580246913580252
        },
        {
          "readMsMax": "0",
          "computeMsMax": "5",
          "inputStages": [
            "0"
          ],
          "waitMsAvg": "152",
          "id": "1",
          "endMs": "1524217492771",
          "waitMsMax": "152",
          "startMs": "1524217492206",
          "waitRatioMax": 0.23456790123456789,
          "readRatioAvg": 0.0,
          "parallelInputs": "1",
          "recordsRead": "59",
          "computeRatioAvg": 0.007716049382716049,
          "writeMsAvg": "7",
          "status": "COMPLETE",
          "writeMsMax": "7",
          "computeMsAvg": "5",
          "shuffleOutputBytesSpilled": "0",
          "writeRatioMax": 0.010802469135802469,
          "readMsAvg": "0",
          "waitRatioAvg": 0.23456790123456789,
          "completedParallelInputs": "1",
          "computeRatioMax": 0.007716049382716049,
          "name": "S01: Output",
          "shuffleOutputBytes": "2779",
          "recordsWritten": "59",
          "readRatioMax": 0.0,
          "steps": [
            {
              "kind": "READ",
              "substeps": [
                "column1, column2, column3, column4",
                "FROM __stage00_output AS project:dataset.table1"
              ]
            },
            {
              "kind": "LIMIT",
              "substeps": [
                "1000"
              ]
            },
            {
              "kind": "WRITE",
              "substeps": [
                "column1, column2, column3, column4",
                "TO __stage01_output"
              ]
            }
          ],
          "writeRatioAvg": 0.010802469135802469
        }
      ],
      "estimatedBytesProcessed": "2307",
      "timeline": [
        {
          "totalSlotMs": "0",
          "activeUnits": "3",
          "completedUnits": "0",
          "elapsedMs": "691",
          "pendingUnits": "3"
        },
        {
          "totalSlotMs": "1772",
          "activeUnits": "3",
          "completedUnits": "3",
          "elapsedMs": "958",
          "pendingUnits": "0"
        }
      ],
      "totalBytesBilled": "10485760",
      "totalBytesProcessed": "2307"
    },
    "endTime": "1524217492855",
    "creationTime": "1524217491787",
    "totalBytesProcessed": "2307",
    "startTime": "1524217491959"
  },
  "jobReference": {
    "projectId": "project",
    "location": "US",
    "jobId": "<REDACTED>"
  },
  "state": "DONE",
  "id": "project:US.<REDACTED>"
}
`

**Comment by Maerig** [comment]
I'm having the same problem with jobs which result  in a `resourcesExceeded` error.
Likewise the job id is `<REDACTED>`, so this might be related to the job configuration missing.

**Comment by tseaver** [comment]
@shollyman ISTM that the back-end could reasonably just omit listing jobs for which the requester doesn't have access.

**Comment by Maerig** [comment]
Yes, it happens when calling `list_jobs` with `all_users=True` while not having the `bigquery.jobs.listAll` permission.
