### ISSUE TITLE
vision : Parse Error

### ISSUE THREAD

**Issue by asshatter** [GoogleCloudPlatform/google-cloud-python#5332]
I am getting this exception while uploading one specific file.

```
ParseError: Failed to parse responses field: Failed to parse fullTextAnnotation field: Failed to parse pages field: Failed to parse blocks field: Message type "google.cloud.vision.v1.Block" has no field named "confidence".

 Available Fields(except extensions): [<google.protobuf.descriptor.FieldDescriptor object at 0x11c029bd0>, <google.protobuf.descriptor.FieldDescriptor object at 0x11c029c10>, <google.protobuf.descriptor.FieldDescriptor object at 0x11c029c50>, <google.protobuf.descriptor.FieldDescriptor object at 0x11c029c90>]
```

**Comment by tseaver** [comment]
@asshatter Can you please provide a snippet of the code which provokes this error, and the full traceback?

**Comment by asshatter** [comment]
Sure, Here's the full traceback

```
Traceback (most recent call last):
  File "/Users/ankushbhatia/clik/cer/app/imageprocessing/__init__.py", line 55, in getTextWords
    json_format.Parse(r.text, pr)
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/json_format.py", line 389, in Parse
    return ParseDict(js, message, ignore_unknown_fields)
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/json_format.py", line 404, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/json_format.py", line 435, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/json_format.py", line 535, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
ParseError: Failed to parse responses field: Failed to parse fullTextAnnotation field: Failed to parse pages field: Failed to parse blocks field: Message type "google.cloud.vision.v1.Block" has no field named "confidence".
 Available Fields(except extensions): [<google.protobuf.descriptor.FieldDescriptor object at 0x11bc3fc90>, <google.protobuf.descriptor.FieldDescriptor object at 0x11bc3fcd0>, <google.protobuf.descriptor.FieldDescriptor object at 0x11bc3fd10>, <google.protobuf.descriptor.FieldDescriptor object at 0x11bc3fd50>]
```

**Comment by asshatter** [comment]
I'm using this URL to make a post request and formatting it to dictionary for a faster response : 
https://vision.googleapis.com/v1p1beta1/images:annotate?key=<API KEY>

**Comment by asshatter** [comment]
I'm sorry it was my issue. Apparently I was using BatchAnnotateImagesResponse object from v1 module instead of v1p1beta1. Closing this issue.

**Comment by tseaver** [comment]
@asshatter Any reason why you are doing a manual HTTP POST to the endpoint, rather than using the `google.cloud.vision_*.ImageAnnotatorClient`?

**Comment by tseaver** [comment]
E.g., from the [docs](https://google-cloud-python.readthedocs.io/en/latest/vision/index.html):

```python
>>> from google.cloud import vision
>>> client = vision.ImageAnnotatorClient()
>>> response = client.annotate_image({
...   'image': {'source': {'image_uri': 'gs://my-test-bucket/image.jpg'}},
...   'features': [{'type': vision.enums.Feature.Type.FACE_DETECTION}],
... })
>>> len(response.annotations)
2
>>> for face in response.annotations[0].faces:
...     print(face.joy)
Likelihood.VERY_LIKELY
Likelihood.VERY_LIKELY
Likelihood.VERY_LIKELY
>>> for logo in response.annotations[0].logos:
...     print(logo.description)
'google'
'github'
```
Based on your call path above, you might want the [`document_text_detection` method](https://google-cloud-python.readthedocs.io/en/latest/vision/gapic/v1/api.html#google.cloud.vision_v1.ImageAnnotatorClient.document_text_detection)


```python
>>> from google.cloud import vision
>>> client = vision.ImageAnnotatorClient()
>>> response = client.document_text_detection(
...     image={'source': {'image_uri': 'gs://my-test-bucket/image.jpg'}})
