### ISSUE TITLE
google.api_core.exceptions.ServiceUnavailable: 503 Getting metadata from plugin failed with error: 'str' object has no attribute 'before_request'

### ISSUE THREAD

**Issue by stefano9-4** [GoogleCloudPlatform/google-cloud-python#5349]
I'm trying to iterate through images in a directory and get their labels through goodle_api_vision. This is my code:

    def run_quickstart():
    import io
    import os
    import cv2
    import numpy as np
    from google.cloud import vision
    from google.cloud.vision import types

    client = vision.ImageAnnotatorClient(credentials = 'service_acc_key.json')

    path = 'E:\wrand\\'
    for image_path in os.listdir(path):

        file_name = path + image_path
        content = cv2.imread(file_name)
        content = content.tobytes()
        print(type(content))

        image = types.Image(content=content)
        print(type(image))
        response = client.label_detection(image=image)
        labels = response.label_annotations
        print('Labels:')
        for label in labels:
            print(label.description)
        
    if __name__ == '__main__':
        run_quickstart()
the error that I get is at this part of code `image = types.Image(content=content)`. The full error being

    <class 'bytes'>
    <class 'google.cloud.vision_v1.types.Image'>
    ERROR:root:AuthMetadataPluginCallback " 
    <google.auth.transport.grpc.AuthMetadataPlugin object at 
    0x0000028520DCA2E8>" raised exception!
    Traceback (most recent call last):
      File "C:\Users\hi_pe\AppData\Local\Programs\Python\Python36\lib\site- 
    packages\grpc\_plugin_wrapping.py", line 77, in __call__
        callback_state, callback))
      File "C:\Users\hi_pe\AppData\Local\Programs\Python\Python36\lib\site- 
    packages\google\auth\transport\grpc.py", line 77, in __call__
        callback(self._get_authorization_headers(context), None)
      File "C:\Users\hi_pe\AppData\Local\Programs\Python\Python36\lib\site
    packages\google\auth\transport\grpc.py", line 61, in 
    _get_authorization_headers
        self._credentials.before_request(
    AttributeError: 'str' object has no attribute 'before_request'
    Traceback (most recent call last):
      File "C:\Users\hi_pe\AppData\Local\Programs\Python\Python36\lib\site- 
    packages\google\api_core\grpc_helpers.py", line 54, in error_remapped_callable
    return callable_(*args, **kwargs)
    File "C:\Users\hi_pe\AppData\Local\Programs\Python\Python36\lib\site-packages\grpc\_channel.py", line 487, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
    File "C:\Users\hi_pe\AppData\Local\Programs\Python\Python36\lib\site-packages\grpc\_channel.py", line 437, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
    grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Getting metadata from plugin failed with error: 'str' object has no attribute 'before_request')>

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "Tutorial.py", line 32, in <module>
    run_quickstart()
      File "Tutorial.py", line 24, in run_quickstart
    response = client.label_detection(image=image)
      File "C:\Users\hi_pe\AppData\Local\Programs\Python\Python36\lib\site-packages\google\cloud\vision_helpers\decorators.py", line 117, in inner
    response = self.annotate_image(request, retry=retry, timeout=timeout)
      File "C:\Users\hi_pe\AppData\Local\Programs\Python\Python36\lib\site-packages\google\cloud\vision_helpers\__init__.py", line 67, in annotate_image
    r = self.batch_annotate_images([request], retry=retry, timeout=timeout)
      File "C:\Users\hi_pe\AppData\Local\Programs\Python\Python36\lib\site-packages\google\cloud\vision_v1\gapic\image_annotator_client.py", line 165, in batch_annotate_images
    request, retry=retry, timeout=timeout, metadata=metadata)
      File "C:\Users\hi_pe\AppData\Local\Programs\Python\Python36\lib\site-packages\google\api_core\gapic_v1\method.py", line 139, in __call__
    return wrapped_func(*args, **kwargs)
      File "C:\Users\hi_pe\AppData\Local\Programs\Python\Python36\lib\site-packages\google\api_core\grpc_helpers.py", line 56, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
      File "<string>", line 3, in raise_from
    google.api_core.exceptions.ServiceUnavailable: 503 Getting metadata from plugin failed with error: 'str' object has no attribute 'before_request'

I put the line `content = content.tobytes()` because otherwise I get this error `has type <class 'numpy.ndarray'>, but expected one of: ((<class 'bytes'>,),)` (always at this method call ` image = types.Image(content=content)`)

**Comment by theacodes** [comment]
@stefano9-4 unfortunately you can't just pass a string directly as the `credentials` argument (although perhaps we should make it where you can), you should do this instead:

```
from google.oauth2 import service_account

credentials = service_account.Credentials. from_service_account_file('service_acc_key.json')

client = vision.ImageAnnotatorClient(credentials=credentials)
```

**Comment by thyatt67** [comment]
I am using Google Vision's safe search function to check images for appropriate content and getting the below error: (Can anyone help?) . It craps out around the 140th. image.

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/grpc/_channel.py", line 547, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/anaconda3/lib/python3.6/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Getting metadata from plugin failed with error: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10e2856a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))"
	debug_error_string = "{"created":"@1550678163.188729000","description":"Getting metadata from plugin failed with error: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10e2856a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))","file":"src/core/lib/security/credentials/plugin/plugin_credentials.cc","file_line":82,"grpc_status":14}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "imageIntake.py", line 242, in <module>
    if inappropriateImage('gs://'+args.bucket+'/'+i.name):
  File "imageIntake.py", line 130, in inappropriateImage
    response = client.safe_search_detection(image=image)
  File "/anaconda3/lib/python3.6/site-packages/google/cloud/vision_helpers/decorators.py", line 101, in inner
    response = self.annotate_image(request, retry=retry, timeout=timeout)
  File "/anaconda3/lib/python3.6/site-packages/google/cloud/vision_helpers/__init__.py", line 72, in annotate_image
    r = self.batch_annotate_images([request], retry=retry, timeout=timeout)
  File "/anaconda3/lib/python3.6/site-packages/google/cloud/vision_v1/gapic/image_annotator_client.py", line 234, in batch_annotate_images
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/anaconda3/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 Getting metadata from plugin failed with error: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10e2856a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))



The script is:

def detect_safe_search_uri(uri):
    """Detects unsafe features in the file located in Google Cloud Storage or
    on the Web."""
    from google.cloud import vision
    client = vision.ImageAnnotatorClient()
    image = vision.types.Image()
    image.source.image_uri = uri

    response = client.safe_search_detection(image=image)
    safe = response.safe_search_annotation

    # Names of likelihood from google.cloud.vision.enums
    likelihood_name = ('UNKNOWN', 'VERY_UNLIKELY', 'UNLIKELY', 'POSSIBLE',
                       'LIKELY', 'VERY_LIKELY')
    print('Safe search:')

    print('adult: {}'.format(likelihood_name[safe.adult]))
    print('medical: {}'.format(likelihood_name[safe.medical]))
    print('spoofed: {}'.format(likelihood_name[safe.spoof]))
    print('violence: {}'.format(likelihood_name[safe.violence]))
    print('racy: {}'.format(likelihood_name[safe.racy]))

**Comment by tseaver** [comment]
@thyatt67 Your issue is different than this one:  it is really the same as #7381:  you are creating once client instance per image, which is causing you to be rate-limited on the authentication service.  As I suggested on that issue, create a single `Client` instance at the top-level of your script, and pass it through to your `detect_safe_search_uri` function.

**Comment by thyatt67** [comment]
@tseaver That fixed it!!  Thank you for your help!!!

**Comment by ib2loud** [comment]
@tseaver  This was the perfect fix for my similar situation. I didn't even realize I was calling the Client instance repeatedly. Thank you for the help.

**Comment by Mathufnn** [comment]
@tseaver I had the same issue with the Natural Language API, and thought I was getting capped by number of requests to the API, which was bizarre since I couldn't get even 10 requests. But the problem was that I was calling instances of Client repeatedly.
Thank you!

**Comment by MaazBinMusa** [comment]
How long does it take for the error to go away? I am using Label detection and faced this error. I moved the client globally but still getting error and hour later.
