### ISSUE TITLE
pip install google-cloud fails on OS X

### ISSUE THREAD

**Issue by nkhumphreys** [GoogleCloudPlatform/google-cloud-python#5361]
Installing the latest google-cloud on OS X (10.13.3 High Sierra) fails:

```
$ pip install google-cloud
Collecting google-cloud
  Using cached https://files.pythonhosted.org/packages/49/9a/943f0e217990c37e119101bbb739d86201ec1fdf59152ecc2dba93c5a8ad/google-cloud-0.33.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2n/8l7tpgyx3xgf4p0wmvd2hqk40000gn/T/pip-install-EkUged/google-cloud/setup.py", line 22, in <module>
        with open(os.path.join(PACKAGE_ROOT, 'setup-README.rst')) as file_obj:
    IOError: [Errno 2] No such file or directory: '/private/var/folders/2n/8l7tpgyx3xgf4p0wmvd2hqk40000gn/T/pip-install-EkUged/google-cloud/setup-README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/2n/8l7tpgyx3xgf4p0wmvd2hqk40000gn/T/pip-install-EkUged/google-cloud/
```

pip version:

```
$  pip --version
pip 10.0.1 from /Users/nathan/.virtualenvs/ops/lib/python2.7/site-packages/pip (python 2.7)
```

NOTE: Installing 0.32.0 installs successfully.

**Comment by nkhumphreys** [comment]
My apologies, I missed #5353

Closing this as a duplicate
