### ISSUE TITLE
Storage: app_identity_service.GetAccessToken NOT_ALLOWED

### ISSUE THREAD

**Issue by zyzniewski** [GoogleCloudPlatform/google-cloud-python#5399]
- GAE standard env
- google-cloud-storage==1.9.0

steps to reproduce:

- create a long-lived Bucket object
- do some file operations, under the hood it will get an access_token from IdentityService for you
- keep your Bucket instance live for at least 1h (so that access token can expire)
- next time when you'll try to get a fresh token from IdentityService it will raise `NotAllowed` exception

code example: https://github.com/zyzniewski/app_identity_service_bug/blob/master/main.py

**Comment by zyzniewski** [comment]
```(/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py:1552)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/g~rental-app-prod/buggy:1.410034148485624860/main.py", line 31, in get
    content_type='image/jpeg',
  File "/base/data/home/apps/g~rental-app-prod/buggy:1.410034148485624860/lib/google/cloud/storage/blob.py", line 1103, in upload_from_string
    predefined_acl=predefined_acl)
  File "/base/data/home/apps/g~rental-app-prod/buggy:1.410034148485624860/lib/google/cloud/storage/blob.py", line 1012, in upload_from_file
    size, num_retries, predefined_acl)
  File "/base/data/home/apps/g~rental-app-prod/buggy:1.410034148485624860/lib/google/cloud/storage/blob.py", line 925, in _do_upload
    size, num_retries, predefined_acl)
  File "/base/data/home/apps/g~rental-app-prod/buggy:1.410034148485624860/lib/google/cloud/storage/blob.py", line 741, in _do_multipart_upload
    transport, data, object_metadata, content_type)
  File "/base/data/home/apps/g~rental-app-prod/buggy:1.410034148485624860/lib/google/resumable_media/requests/upload.py", line 97, in transmit
    retry_strategy=self._retry_strategy)
  File "/base/data/home/apps/g~rental-app-prod/buggy:1.410034148485624860/lib/google/resumable_media/requests/_helpers.py", line 101, in http_request
    func, RequestsMixin._get_status_code, retry_strategy)
  File "/base/data/home/apps/g~rental-app-prod/buggy:1.410034148485624860/lib/google/resumable_media/_helpers.py", line 146, in wait_and_retry
    response = func()
  File "/base/data/home/apps/g~rental-app-prod/buggy:1.410034148485624860/lib/google/auth/transport/requests.py", line 198, in request
    self._auth_request, method, url, request_headers)
  File "/base/data/home/apps/g~rental-app-prod/buggy:1.410034148485624860/lib/google/auth/credentials.py", line 121, in before_request
    self.refresh(request)
  File "/base/data/home/apps/g~rental-app-prod/buggy:1.410034148485624860/lib/google/auth/app_engine.py", line 116, in refresh
    self._scopes, self._service_account_id)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/1/google/appengine/api/app_identity/app_identity.py", line 605, in get_access_token
    scopes, service_account_id=service_account_id)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/1/google/appengine/api/app_identity/app_identity.py", line 558, in get_access_token_uncached
    return rpc.get_result()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/1/google/appengine/api/app_identity/app_identity.py", line 529, in get_access_token_result
    raise _to_app_identity_error(err)
NotAllowed```

**Comment by zyzniewski** [comment]
@tseaver thanks for a reply

> how / when are you creating that? In particular, are you passing in a custom `_http` argument?

really simple: https://github.com/zyzniewski/app_identity_service_bug/blob/master/main.py#L8-L13

> The bit which *does* have state is the `Client` instance

shorthand, basically I've moved them all together so probably you're right: https://github.com/zyzniewski/app_identity_service_bug/commit/dcf59c6cfcf284ac8a332713103aa146adfda258

**Comment by jacobg** [comment]
I'm also running into this issue with the Firebase Admin SDK on GAE Python 2.7. I call `firebase_admin.initialize_app()` when the app starts up. I thought maybe that happens under `/_ah/warmup` request. And it works fine, but then after an hour, when it needs to renew during another request, it fails. But how is that out of "request context"? Or do you mean that a request can't renew a token that a different request originally generated?

If I call `firebase_admin.initialize_app()` on every request where I need it, will that add latency? Are there any other throttles on # of access tokens generated?
