### ISSUE TITLE
No able to deploy to gcloud App Engine with Pyhton and gunicorn

### ISSUE THREAD

**Issue by vascoV** [GoogleCloudPlatform/google-cloud-python#5443]
Hello,

I have been trying last day to deploy my script to Google Cloud console but without success!
Gcloud Version: 
```
Google Cloud SDK 204.0.0
beta 2017.09.15
bq 2.0.34
core 2018.06.04
gsutil 4.31
```

yaml file:
```
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
```
requirements.txt file:
```
Flask==0.12.2
gunicorn==19.8.1
```

I tried deploying with `gcloud beta app deploy` and I am getting the following error:
```
ERROR: (gcloud.app.deploy) Error Response: [9]
Application startup error:
[2018-06-06 09:28:47 +0000] [1] [INFO] Starting gunicorn 19.8.1
[2018-06-06 09:28:47 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2018-06-06 09:28:47 +0000] [1] [INFO] Using worker: sync
[2018-06-06 09:28:47 +0000] [7] [INFO] Booting worker with pid: 7
[2018-06-06 09:28:47 +0000] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/env/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/env/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/env/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/env/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/env/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/env/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/vmagent/app/main.py", line 5, in <module>
    import firebase_admin
ModuleNotFoundError: No module named 'firebase_admin'
[2018-06-06 09:28:47 +0000] [7] [INFO] Worker exiting (pid: 7)
[2018-06-06 09:28:47 +0000] [1] [INFO] Shutting down: Master
[2018-06-06 09:28:47 +0000] [1] [INFO] Reason: Worker failed to boot.
```
I also have all my modules installed into a virtual env... 

However, I also tried deploying with `gcloud app deploy` and I am getting a different error -> `ERROR: (gcloud.beta.app.deploy) Error Response: [13] Error while processing files.` Referring to a similar issue which is closed now (https://github.com/GoogleCloudPlatform/getting-started-java/issues/281) I did this command `gcloud config set app/use_deprecated_preparation True`, as the majority of people are saying that is working but for me is NOT!

**Comment by tseaver** [comment]
@vascoV I'm sorry you are having this problem.  Unfortunately, this repository is not where the `Cloud SDK` application is maintained:  Please see the [support page for Cloud SDK](https://cloud.google.com/sdk/docs/getting-support).

**Comment by thezoug** [comment]
> @vascoV I'm sorry you are having this problem. Unfortunately, this repository is not where the `Cloud SDK` application is maintained: Please see the [support page for Cloud SDK](https://cloud.google.com/sdk/docs/getting-support).

This is really not a helpful response.
