### ISSUE TITLE
EOFError error starting in dev_appserver.py for Google App Engine in python

### ISSUE THREAD

**Issue by Arispg** [GoogleCloudPlatform/google-cloud-python#5508]
I run this in a clean virtual enviroment with no module installed on lib on my local machine. I have my app ready to run but I cannot start dev_appserver.py, I obtain this error

```
dev_appserver.py app.yaml

INFO 2018-06-20 11:24:01,578 devappserver2.py:120] Skipping SDK update check.
Traceback (most recent call last):
File "C:\Users\aris\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\dev_appserver.py", line 96, in <module>
_run_file(__file__, globals())
File "C:\Users\aris\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\dev_appserver.py", line 90, in _run_file
execfile(_PATHS.script_file(script_name), globals_)
File "C:\Users\aris\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 454, in <module>
main()
File "C:\Users\aris\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 442, in main
dev_server.start(options)
File "C:\Users\aris\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 197, in start
configuration.modules[0].application_root)
File "C:\Users\aris\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\api_server.py", line 640, in create_api_server
if options.support_datastore_emulator else None)
File "C:\Users\aris\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\stub_util.py", line 255, in setup_stubs
simple_search_stub.SearchServiceStub(index_file=search_index_path))
File "C:\Users\aris\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\search\simple_search_stub.py", line 700, in __init__
self.Read()
File "C:\Users\aris\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\search\simple_search_stub.py", line 1214, in Read
read_indexes = self._ReadFromFile()
File "C:\Users\aris\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\search\simple_search_stub.py", line 1188, in _ReadFromFile
version, indexes = pickle.load(open(self.__index_file, 'rb'))
EOFError
```
These are the versions of google cloud, that is updated to last version.I try to update like is here specified https://cloud.google.com/appengine/docs/standard/python/download but it didn't work

```
gcloud --version

Google Cloud SDK 206.0.0
app-engine-python 1.9.70
app-engine-python-extras 1.9.69
beta 2018.06.12
bq 2.0.34
core 2018.06.18
gsutil 4.32
```
This is the version of python

```
python --version

Python 2.7.14

```
Please, any help with this?

**Comment by tseaver** [comment]
@Arispg I'm sorry you are having trouble with the Gcloud SDK.  Unfortunately, this repository, which manages Python client libraries for Google Cloud APIs, is not related to that product.  Please report the issue using one of the [SDK Support resources](https://cloud.google.com/sdk/docs/getting-support).
