### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'syntax' in http_pb2.py

### ISSUE THREAD

**Issue by mcdonc** [GoogleCloudPlatform/google-cloud-python#5548]
_From @alexandermichels on May 22, 2018 21:34_

Hello, I'm trying to use Google Cloud's Text-To-Speech and I am getting this traceback when I try importing texttospeech from google.cloud. I installed the SDK using [Google's Quickstart for Debian/Ubuntu and Python](https://cloud.google.com/sdk/docs/) and the Python libraries using pip. I've tried upgrading using pip and still get this error, I've used the import in different Python scripts and get the same error, and I Googled around saw the problem might be protobuf so I uninstalled/reinstalled/upgraded and still getting the error. Any ideas?

>>> runfile('/home/alex/Documents/GitHubRepositories/TitanRadio/WeatherWaves/WeatherReporter.py', wdir='/home/alex/Documents/GitHubRepositories/TitanRadio/WeatherWaves')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)
  File "/home/alex/Documents/GitHubRepositories/TitanRadio/WeatherWaves/WeatherReporter.py", line 5, in <module>
    from google.cloud import texttospeech
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/texttospeech.py", line 17, in <module>
    from google.cloud.texttospeech_v1beta1 import TextToSpeechClient
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/texttospeech_v1beta1/__init__.py", line 17, in <module>
    from google.cloud.texttospeech_v1beta1 import types
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/texttospeech_v1beta1/types.py", line 20, in <module>
    from google.api import http_pb2
  File "/usr/local/lib/python2.7/dist-packages/google/api/http_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x15google/api/http.proto\x12\ngoogle.api\"+\n\x04Http\x12#\n\x05rules\x18\x01 \x03(\x0b\x32\x14.google.api.HttpRule\"\xea\x01\n\x08HttpRule\x12\x10\n\x08selector\x18\x01 \x01(\t\x12\r\n\x03get\x18\x02 \x01(\tH\x00\x12\r\n\x03put\x18\x03 \x01(\tH\x00\x12\x0e\n\x04post\x18\x04 \x01(\tH\x00\x12\x10\n\x06\x64\x65lete\x18\x05 \x01(\tH\x00\x12\x0f\n\x05patch\x18\x06 \x01(\tH\x00\x12/\n\x06\x63ustom\x18\x08 \x01(\x0b\x32\x1d.google.api.CustomHttpPatternH\x00\x12\x0c\n\x04\x62ody\x18\x07 \x01(\t\x12\x31\n\x13\x61\x64\x64itional_bindings\x18\x0b \x03(\x0b\x32\x14.google.api.HttpRuleB\t\n\x07pattern\"/\n\x11\x43ustomHttpPattern\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\tB\'\n\x0e\x63om.google.apiB\tHttpProtoP\x01\xf8\x01\x01\xa2\x02\x04GAPIb\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'

_Copied from original issue: google/google-api-python-client#508_

**Comment by mcdonc** [comment]
This doesn't appear to happen in a fresh install using a virtualenv from a checkout of the cloud api Python libraries:

```
$ virtualenv -p python2.7 env27
Running virtualenv with interpreter /home/chrism/bin/python2.7
Using real prefix '/home/chrism/opt/buildout.python/parts/opt'
New python executable in /home/chrism/projects/gcloud/google-cloud-python/texttospeech/env27/bin/python2.7
Also creating executable in /home/chrism/projects/gcloud/google-cloud-python/texttospeech/env27/bin/python
Installing setuptools, pip, wheel...done.
$ env27/bin/pip install .
Processing /home/chrism/projects/gcloud/google-cloud-python/texttospeech
Collecting google-api-core[grpc]<2.0.0dev,>=0.1.0 (from google-cloud-texttospeech==0.2.0)
  Downloading https://files.pythonhosted.org/packages/d2/03/a83c6d0efa63a13d085b81927fdc9e12ffb98aa0f67798a7573fc6b231e2/google_api_core-1.2.1-py2.py3-none-any.whl (50kB)
    100% |████████████████████████████████| 51kB 1.7MB/s 
Collecting google-auth<2.0.0dev,>=0.4.0 (from google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Using cached https://files.pythonhosted.org/packages/53/06/6e6d5bfa4d23ee40efd772d6b681a7afecd859a9176e564b8c329382370f/google_auth-1.5.0-py2.py3-none-any.whl
Collecting requests<3.0.0dev,>=2.18.0 (from google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting pytz (from google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Using cached https://files.pythonhosted.org/packages/dc/83/15f7833b70d3e067ca91467ca245bae0f6fe56ddc7451aa0dc5606b120f2/pytz-2018.4-py2.py3-none-any.whl
Collecting googleapis-common-protos<2.0dev,>=1.5.3 (from google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
Collecting protobuf>=3.0.0 (from google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Using cached https://files.pythonhosted.org/packages/85/f8/d09e4bf21c4de65405ce053e90542e728c5b7cf296b9df36b0bf0488f534/protobuf-3.6.0-py2.py3-none-any.whl
Collecting futures>=3.2.0; python_version < "3.2" (from google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Using cached https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Collecting six>=1.10.0 (from google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=34.0.0 in ./env27/lib/python2.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0) (39.2.0)
Collecting grpcio>=1.8.2; extra == "grpc" (from google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Using cached https://files.pythonhosted.org/packages/30/24/8e247548321e52c266a639b51a838ec19b41fb6bfd27e3bbef018496752e/grpcio-1.12.1-cp27-cp27m-manylinux1_x86_64.whl
Collecting cachetools>=2.0.0 (from google-auth<2.0.0dev,>=0.4.0->google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Using cached https://files.pythonhosted.org/packages/0a/58/cbee863250b31d80f47401d04f34038db6766f95dea1cc909ea099c7e571/cachetools-2.1.0-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from google-auth<2.0.0dev,>=0.4.0->google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Using cached https://files.pythonhosted.org/packages/e1/ae/baedc9cb175552e95f3395c43055a6a5e125ae4d48a1d7a924baca83e92e/rsa-3.4.2-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth<2.0.0dev,>=0.4.0->google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Downloading https://files.pythonhosted.org/packages/19/02/fa63f7ba30a0d7b925ca29d034510fc1ffde53264b71b4155022ddf3ab5d/pyasn1_modules-0.2.2-py2.py3-none-any.whl (62kB)
    100% |████████████████████████████████| 71kB 4.9MB/s 
Collecting idna<2.8,>=2.5 (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting enum34>=1.0.4 (from grpcio>=1.8.2; extra == "grpc"->google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting pyasn1>=0.1.3 (from rsa>=3.1.4->google-auth<2.0.0dev,>=0.4.0->google-api-core[grpc]<2.0.0dev,>=0.1.0->google-cloud-texttospeech==0.2.0)
  Using cached https://files.pythonhosted.org/packages/a0/70/2c27740f08e477499ce19eefe05dbcae6f19fdc49e9e82ce4768be0643b9/pyasn1-0.4.3-py2.py3-none-any.whl
Building wheels for collected packages: google-cloud-texttospeech
  Running setup.py bdist_wheel for google-cloud-texttospeech ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-e9R5co/wheels/83/8b/02/4d6581e531f8bc67cab81d2156564ba5158567d5da6da9e641
Successfully built google-cloud-texttospeech
Installing collected packages: cachetools, pyasn1, rsa, pyasn1-modules, six, google-auth, idna, certifi, chardet, urllib3, requests, pytz, protobuf, googleapis-common-protos, futures, enum34, grpcio, google-api-core, google-cloud-texttospeech
Successfully installed cachetools-2.1.0 certifi-2018.4.16 chardet-3.0.4 enum34-1.1.6 futures-3.2.0 google-api-core-1.2.1 google-auth-1.5.0 google-cloud-texttospeech-0.2.0 googleapis-common-protos-1.5.3 grpcio-1.12.1 idna-2.7 protobuf-3.6.0 pyasn1-0.4.3 pyasn1-modules-0.2.2 pytz-2018.4 requests-2.19.1 rsa-3.4.2 six-1.11.0 urllib3-1.23
$ env27/bin/python
Python 2.7.14 (default, Apr 17 2018, 14:00:59) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import texttospeech
>>> 
```

This issue is slightly misfiled; I'm going to use the issue mover to move it to the google cloud platform repository issue tracker.

**Comment by d2sys** [comment]
I had the same problem, the reason was the old version of protobuf lib. I uninstalled (via pip) and installed again to the latest version and it worked. Hope it will help.
