### ISSUE TITLE
BigQuery: insert into table example doesn't work

### ISSUE THREAD

**Issue by leeparayno** [GoogleCloudPlatform/google-cloud-python#5549]
The example code from https://google-cloud-python.readthedocs.io/en/latest/bigquery/usage.html#table-operations doesn't work.

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version

Ubuntu 16.04

3. Python version and virtual environment information `python --version`

Python 2.7.12

4. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`

$ pip show google-cloud-bigquery
Name: google-cloud-bigquery
Version: 0.28.0
Summary: Python Client for Google BigQuery
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: googleapis-publisher@google.com
License: Apache 2.0
Location: /home/paral006/virtualenv/bigquery/lib/python2.7/site-packages
Requires: google-auth, google-cloud-core, requests, google-resumable-media, google-api-core
Required-by:

5. Stacktrace if available

Traceback (most recent call last):
  File "./bqcreatetable.py", line 70, in <module>
    main(args)
  File "./bqcreatetable.py", line 59, in main
    insert_data(dataset_ref)
  File "./bqcreatetable.py", line 32, in insert_data
    errors = table.insert_data(table, rows_to_insert)  # API request
AttributeError: 'Table' object has no attribute 'insert_data'

6. Steps to reproduce
7. Code example

#!/usr/bin/env python

import argparse

# Imports the Google Cloud client library
from google.cloud import bigquery

SERVICE_ACCOUNT_CREDENTIALS_FILE = 'creds.json'
PROJECT_ID = None
DATASET_ID = None
bigquery_client = None

def get_client():
    # Explicitly use service account credentials by specifying the private key
    # file.
    bigquery_client = bigquery.Client.from_service_account_json(SERVICE_ACCOUNT_CREDENTIALS_FILE, project=PROJECT_ID)
    #bigquery_client = bigquery.Client(project=PROJECT_ID)

    return bigquery_client

def insert_data(dataset_ref):
	bigquery_client = get_client()

	table_ref = dataset_ref.table('my_table')
        table = bigquery.Table(table_ref)

	rows_to_insert = [
    		(u'Phred Phlyntstone', 32),
    		(u'Wylma Phlyntstone', 29),
	]

	errors = table.insert_data(table, rows_to_insert)  # API request

	assert errors == []

def create_table():
        schema = [
                bigquery.SchemaField('full_name', 'STRING', mode='REQUIRED'),
                bigquery.SchemaField('age', 'INTEGER', mode='REQUIRED'),
        ]
        table_ref = dataset_ref.table('my_table')
        table = bigquery.Table(table_ref, schema=schema)
        table = bigquery_client.create_table(table)  # API request

        assert table.table_id == 'my_table'

def main(args):
	# Instantiates a client
	#bigquery_client = bigquery.Client(project="di-techops-px-nonprod-7")

	bigquery_client = get_client()

	# The name for the new dataset
	dataset_id = 'my_new_dataset'

	# Prepares a reference to the new dataset
	dataset_ref = bigquery_client.dataset(dataset_id)

	insert_data(dataset_ref)

if __name__ == '__main__':
	parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
	parser.add_argument("-p", "--projectid", action="store", dest="projectid", default=None, required=True, help="REQUIRED. Set to project ID")
	#parser.add_argument("-d", "--dataset", action="store", dest="dataset", default=None, required=True, help="REQUIRED. Set to dataset IDD")
	args = parser.parse_args()

	PROJECT_ID = args.projectid
	#DATASET_ID = args.dataset

	main(args)

Using GitHub flavored markdown can help make your request clearer.
See: https://guides.github.com/features/mastering-markdown/

**Comment by leeparayno** [comment]
Version installed issue, was not updated to 1.3.0 of google-cloud-bigquery on the bastion host running the script.
