### ISSUE TITLE
Cloud Speech API: Fails behind a SSL proxy

### ISSUE THREAD

**Issue by bond-** [GoogleCloudPlatform/google-cloud-python#5591]
1. OS type and version: macOS, High Sierra (10.13.5)
2. Python version and virtual environment information: 3.6.3
3. google-cloud-python version
```
Name: google-cloud-speech
Version: 0.35.0
Summary: Google Cloud Speech API client library
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Users/<user>/softwares/miniconda3/lib/python3.6/site-packages
Requires: google-api-core
```

4. Stacktrace if available: [grpc_error.txt](https://github.com/GoogleCloudPlatform/google-cloud-python/files/2185763/grpc_error.txt)

5. Steps to reproduce, reproducible only within the enterprise network
6. Code example: [speech.py.txt](https://github.com/GoogleCloudPlatform/google-cloud-python/files/2185722/speech.py.txt)

Any pointers on how to resolve this issue or debug information that I can dig into could be helpful.

**Comment by tseaver** [comment]
@bond- Thanks for the report!  Can you provide the Python stacktrace at the point your script errors out?

**Comment by bond-** [comment]
@tseaver 
```
Traceback (most recent call last):
  File "speech.py", line 193, in <module>
    main()
  File "speech.py", line 189, in main
    listen_print_loop(responses)
  File "speech.py", line 128, in listen_print_loop
    for response in responses:
  File "/Users/<user>/softwares/miniconda3/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 78, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 Connect Failed
```

**Comment by tseaver** [comment]
@theacodes The error is being raised from the `google.api_core.grpc_helpers.StreamingResponseIterator.next()`, likely on the first iteration.  Any clue why this would fail behind a normally- / properly-configured SSL proxy?

@bond- Can you show us a dump of the [environment variable(s)](http://docs.python-requests.org/en/master/user/advanced/#proxies) which hold the proxy configuration?  Redact any sensitive information (real hostnames / IP addresses, etc.).

**Comment by bond-** [comment]
@tseaver This is a enterprise wide proxy, it's not set on my local system. Every network call is redirected from this proxy.

**Comment by tseaver** [comment]
@bond- Does Python/requests HTTPS access work for other URLs in that environment?  E.g.:

```bash
$ python
>>> import requests
>>> requests.get('https://google.com/')
```

**Comment by bond-** [comment]
@tseaver Oh I forgot to mention, to browse any make any request I need to add intermediate SSL certificates.

For running the attached python file, speech.py I am setting the env variable GRPC_DEFAULT_SSL_ROOTS_FILE_PATH: 
```
export GRPC_DEFAULT_SSL_ROOTS_FILE_PATH=`pwd`/all.ca_bundle
```

all.ca_bundle has all the pem files that my organization has.

**Comment by bond-** [comment]
When I try to do a curl on the ip it tries to connect, this is what I see:

The error says it tries to connect to a server with hostnames of type: *.googleapis.com but it found a IP which is not on the SSL cert.

```
curl --cacert all.ca_bundle -vL https://172.217.11.42
* Rebuilt URL to: https://172.217.11.42/
*   Trying 172.217.11.42...
* TCP_NODELAY set
* Connected to 172.217.11.42 (172.217.11.42) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: all.ca_bundle
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=*.googleapis.com
*  start date: Jun 19 11:38:18 2018 GMT
*  expire date: Aug 28 11:31:00 2018 GMT
*  subjectAltName does not match 172.217.11.42
* SSL: no alternative certificate subject name matches target host name '172.217.11.42'
* stopped the pause stream!
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (51) SSL: no alternative certificate subject name matches target host name '172.217.11.42'
```

Same error from the python program:
```
D0712 11:35:05.658061000 123145408745472 security_handshaker.cc:129]   Security handshake failed: {"created":"@1531409705.658050000","description":"Cannot check peer: missing selected ALPN property.","file":"src/core/lib/security/security_connector/security_connector.cc","file_line":857}
I0712 11:35:05.658190000 123145408745472 subchannel.cc:646]            Connect failed: {"created":"@1531409705.658050000","description":"Cannot check peer: missing selected ALPN property.","file":"src/core/lib/security/security_connector/security_connector.cc","file_line":857}
I0712 11:35:05.658315000 123145408745472 subchannel.cc:646]            Connect failed: {"created":"@1531409705.658304000","description":"OS Error","errno":65,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":310,"os_error":"No route to host","syscall":"connect"}
```

**Comment by bond-** [comment]
The intermediate SSL calls are do decrypt and re-encrypt. Kind of like 'Man in the middle'.

**Comment by tseaver** [comment]
I don't think there is anything we can do in `google-cloud-logging` to work around a MITM proxy:  such proxies are what SSL/TLS is *supposed* to defeat.

Please reopen if you can suggest differently.

**Comment by bond-** [comment]
@tseaver I switched from using a MITM proxy to a HTTP_PROXY and HTTPS_PROXY

```python
import os
proxy = 'http://<user>:<pass>@<proxy>:<port>'
 
os.environ['http_proxy'] = proxy
os.environ['HTTP_PROXY'] = proxy
os.environ['https_proxy'] = proxy
os.environ['HTTPS_PROXY'] = proxy
```
```
User = user
Pass = password with encoded special characters, like %24 for $
Proxy = gateway.zscloud.net
Port = port
```

This is the new trace:
```
Traceback (most recent call last):
  File "speech.py", line 201, in <module>
    main()
  File "speech.py", line 197, in main
    listen_print_loop(responses)
  File "speech.py", line 136, in listen_print_loop
    for response in responses:
  File "/Users/lok268/softwares/miniconda3/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 78, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 Connect Failed
```

GRPC trace:
```
D0713 12:13:42.958174000 140735948587904 ev_posix.cc:145]              Using polling engine: poll
D0713 12:13:42.959179000 140735948587904 dns_resolver.cc:339]          Using native dns resolver
D0713 12:13:42.959350000 140735948587904 http_proxy.cc:71]             userinfo found in proxy URI
D0713 12:13:43.003350000 140735948587904 dns_resolver.cc:280]          Start resolving.
I0713 12:13:43.158005000 123145368612864 tcp_client_posix.cc:329]      CLIENT_CONNECT: ipv4:165.225.39.27:10336: asynchronously connecting fd 0x7f8fde533e50
I0713 12:13:43.231762000 123145377087488 tcp_client_posix.cc:145]      CLIENT_CONNECT: ipv4:165.225.39.27:10336: on_writable: error="No Error"
I0713 12:13:43.231841000 123145377087488 tcp_client_posix.cc:108]      CLIENT_CONNECT: ipv4:165.225.39.27:10336: on_alarm: error="Cancelled"
I0713 12:13:43.232586000 123145377087488 http_connect_handshaker.cc:300] Connecting to server speech.googleapis.com:443 via HTTP proxy ipv4:165.225.39.27:10336
...
I0713 12:13:43.396028000 123145377087488 tcp_posix.cc:364]             READ 0x7f8fdbfc4660 (peer=ipv4:165.225.39.27:10336): ...
E0713 12:13:43.396966000 123145377087488 ssl_transport_security.cc:1228] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
D0713 12:13:43.396990000 123145377087488 security_handshaker.cc:129]   Security handshake failed: {"created":"@1531498423.396977000","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":248,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0713 12:13:43.397099000 123145377087488 subchannel.cc:646]            Connect failed: {"created":"@1531498423.396977000","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":248,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0713 12:13:43.397227000 123145377087488 subchannel.cc:470]            Subchannel 0x7f8fde534760: Retry in 761 milliseconds
Traceback (most recent call last):
  File "/Users/lok268/softwares/miniconda3/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 76, in next
    return six.next(self._wrapped)
  File "/Users/lok268/softwares/miniconda3/lib/python3.6/site-packages/grpc/_channel.py", line 345, in __next__
    return self._next()
  File "/Users/lok268/softwares/miniconda3/lib/python3.6/site-packages/grpc/_channel.py", line 339, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connect Failed"
	debug_error_string = "{"created":"@1531498423.397246000","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2673,"referenced_errors":[{"created":"@1531498423.397243000","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":210,"referenced_errors":[{"created":"@1531498423.397097000","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":641,"grpc_status":14,"referenced_errors":[{"created":"@1531498423.396977000","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":248,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}]}]}]}"
```

**Comment by bond-** [comment]
@tseaver I am working with my enterprise to bypass SSL inspection/MITM proxy.

Can you please tell me which communication channels(like speech.googleapis.com:443) should be open for Cloud Speech API?

**Comment by tseaver** [comment]
@bond- 

> Can you please tell me which communication channels(like speech.googleapis.com:443) should be open for Cloud Speech API?

That endpoint is the only one used by the Speech API itself.  Using a service account private key for credentials also requires the `accounts.google.com:443` endpoint (check the `auth_uri` / `token_uri` keys in the JSON key file you are using).

**Comment by bond-** [comment]
@tseaver Thanks for the support. After adding a SSL bypass in MITM proxy the connection works now.

**Comment by tseaver** [comment]
@bond- Great!  I'm glad you found a solution.
