### ISSUE TITLE
DataProc: Unable to import dataproc_v1.

### ISSUE THREAD

**Issue by vcolano** [GoogleCloudPlatform/google-cloud-python#5653]
- Debian GNU/Linux 9
- python 2.7
- google-cloud-dataproc 0.1.0. 

I'm getting an error when importing a module which imports dataproc_v1 as `from google.cloud import dataproc_v1`. The error is occurring within a docker container running Debian 9.

Stack trace:
```
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    from my_module.application import MyModule
  File "/usr/local/lib/python2.7/site-packages/my_module/application.py", line 13, in <module>
    from google.cloud import dataproc_v1
  File "/usr/local/lib/python2.7/site-packages/google/cloud/dataproc_v1/__init__.py", line 18, in <module>
    from google.cloud.dataproc_v1.gapic import cluster_controller_client
  File "/usr/local/lib/python2.7/site-packages/google/cloud/dataproc_v1/gapic/cluster_controller_client.py", line 19, in <module>
    import google.api_core.gapic_v1.client_info
  File "/usr/local/lib/python2.7/site-packages/google/api_core/gapic_v1/__init__.py", line 15, in <module>
    from google.api_core.gapic_v1 import client_info
  File "/usr/local/lib/python2.7/site-packages/google/api_core/gapic_v1/client_info.py", line 26, in <module>
    _GRPC_VERSION = pkg_resources.get_distribution('grpcio').version
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 472, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 344, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'grpcio' distribution was not found and is required by the application
```

This maybe related to [issue 5636](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5636)

**Comment by tseaver** [comment]
@vcolano Yes, this is a symptom of the same underlying issue as #5636:  we need a new release of `google-cloud-dataproc`, because the automated release machinery borked.

I'm closing this, as #5636 is already assigned to @crwilcox:  when he makes the release, all should be well.
