### ISSUE TITLE
Integer keys in Map throw invalid property path error

### ISSUE THREAD

**Issue by narsariamanu** [GoogleCloudPlatform/google-cloud-python#5672]
The firestore document has a map of the following type:
```
u'hour': {
    u'6': true,
    u'7': true,
    u'8': true
}
```

When trying to query on the map in the form of:
`db.collection(u'validHours').where(u'hour.6', u'==', True).get()`
it throws error
`InvalidArgument: 400 Invalid property path "hour.6".`

```
Traceback (most recent call last):
  File "/Users/manu/python-projects/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/manu/python-projects/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/manu/python-projects/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/manu/python-projects/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/manu/python-projects/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/manu/python-projects/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/manu/python-projects/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/manu/python-projects/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/manu/Documents/Codes/hours/app/controllers/engines/time.py", line 20, in index
    return str(timeChecker.get_valid_time())
  File "/Users/manu/Documents/Codes/hours/app/models/time.py", line 21, in get_valid_time
    for x in time_value:
  File "/Users/manu/python-projects/lib/python2.7/site-packages/google/cloud/firestore_v1beta1/query.py", line 588, in get
    for index, response_pb in enumerate(response_iterator):
  File "/Users/manu/python-projects/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 78, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/Users/manu/python-projects/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
InvalidArgument: 400 Invalid property path "hour.6".
```

Works fine when trying the same query with NodeJS.
Summary:
Interger keys in a map are not working.

**Comment by tseaver** [comment]
@narsariamanu Thanks for the report!  The `400 InvalidArgument` response from the API indicates that the `hour.6` query itself is not allowed.  The integer key needs to be escaped, e.g.:

```python
db.collection(u'validHours').where(u'hour.`6`', u'==', True).get()
```

There is a [`FieldPath` helper](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/8fa7ab2f9071bc41e610c0ab4f0319f8770d0ea9/firestore/google/cloud/firestore_v1beta1/_helpers.py#L113) which knows how do to that escaping, e.g.:

```python
from google.cloud.firestore_v1beta1._helpers import FieldPath

path = FieldPath.from_string(u'hour6')
escaped_path = path.to_api_repr()

db.collection(u'validHours').where(escaped_path, u'==', True).get()
```

**Comment by narsariamanu** [comment]
@tseaver Thanks for the clarification. I was able to do solve my problem by escaping the integer key.

I tried to import the FieldPath helper and use it but to my surprise, the library installed on my machine did not have this helper class available. I only had FieldPathHelper. I installed the library using pip, I even tried updating the library but is says up to date. Current versions being used:

```
google-api-core          1.2.1    
google-auth              1.5.0    
google-cloud-core        0.28.1   
google-cloud-firestore   0.29.0   
google-cloud-storage     1.10.0   
google-resumable-media   0.3.1    
googleapis-common-protos 1.5.3 
```

I think the code is not updated in the pip package yet.

**Comment by tseaver** [comment]
@narsariamanu You are correct:  the `FieldPath` class is not yet in a released version of `google-cloud-firestore`.  We have an upcoming / planned a review of the library surface, and I have asked that we consider supporting `FieldPath` arguments for any methods taking `field_path` / `field_paths` parameters.

**Comment by narsariamanu** [comment]
@tseaver Thanks for the clarification.
