### ISSUE TITLE
Vision: DefaultCredentialsError raised from ImageAnnotatorClient

### ISSUE THREAD

**Issue by caizhiyuanrise** [GoogleCloudPlatform/google-cloud-python#5743]
Hi

I have a Python Script that requests to google vision API to receive keywords for images.
It ran fine, and I played around with the numbers of size of the images and quality.
I then set it to 5000px, and then it tried that constantly and did not got through, but the script just tried again and again and again.. so I terminates Terminal and then reopened a new session.
Since then I get the error Quoted below.

I already crated a new Service-accounbt JSON file, nothing changes

Anyone an idea?

Thank you!

```bash
Cai-iMac-Pro-2:~ caimac$ find /Users/caimac/visionapi -type f -iname '*.tif' -o -iname '*.tiff' | xargs ~/vision_color.py

Considering /Users/caimac/visionapi/DAO/L01/S_A02/S_A02_DAO_00004_20170806.tif:
/Users/caimac/visionapi/DAO/L01/S_A02/S_A02_DAO_00004_20170806.jpg already exists, no need to transcode
Creating request
Traceback (most recent call last):
  File "/Users/caimac/vision_color.py", line 77, in <module>
    client = client or vision.ImageAnnotatorClient()
  File "/Users/caimac/Library/Python/2.7/lib/python/site-packages/google/cloud/gapic/vision/v1/image_annotator_client.py", line 147, in __init__
    ssl_credentials=ssl_credentials)
  File "/Users/caimac/Library/Python/2.7/lib/python/site-packages/google/gax/grpc.py", line 106, in create_stub
    credentials = _grpc_google_auth.get_default_credentials(scopes)
  File "/Users/caimac/Library/Python/2.7/lib/python/site-packages/google/gax/_grpc_google_auth.py", line 62, in get_default_credentials
    credentials, _ = google.auth.default(scopes=scopes)
  File "/Users/caimac/Library/Python/2.7/lib/python/site-packages/google/auth/_default.py", line 282, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or
explicitly create credential and re-run the application. For more
information, please see
https://developers.google.com/accounts/docs/application-default-credentials.
Robertos-iMac-Pro-2:~ caimac$ 
```

**Comment by tseaver** [comment]
@caizhiyuanrise You need to set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to point to your service account Json file.  E.g.:

```bash
$ export GOOGLE_APPLICATION_CREDENTIALS=/path/to/my/project/service-account.json
```

Please feel free to follow up or reopen if this doesn't answer your question.

**Comment by caizhiyuanrise** [comment]
fantastic, yes that was it. I did it on that day, did not know I might have to do that again... 
Many thanks!
For info: I used this command:
export GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account
worked then
