### ISSUE TITLE
PubSub: Bidirectional RPC unexpectedly exited

### ISSUE THREAD

**Issue by hamzassi** [GoogleCloudPlatform/google-cloud-python#5751]
Debian GNU/Linux 8

Python version == 2.7.9

google-cloud==0.32.0

google-cloud-pubsub==0.35.4

From our logs we see the following error message:
`The bidirectional RPC unexpectedly exited. This is a truly exceptional case. Please file a bug with your logs.`

Followed by:
```[2018-08-06 07:29:27,336 - INFO - Thread-ConsumeBidirectionalStream - bidi] Thread-ConsumeBidirectionalStream exiting
[2018-08-06 07:29:27,347 - ERROR - Thread-CallbackRequestDispatcher - helper_threads] Error in queue callback worker: 'NoneType' object has no attribute 'is_paused'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/_protocol/helper_threads.py", line 112, in __call__
    self._callback(items)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py", line 101, in dispatch_callback
    self.ack(batched_commands.pop(requests.AckRequest))
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py", line 124, in ack
    self.drop(items)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py", line 133, in drop
    self._manager.maybe_resume_consumer()
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 224, in maybe_resume_consumer
    if not self._consumer.is_paused:
AttributeError: 'NoneType' object has no attribute 'is_paused'
[2018-08-06 07:29:27,368 - INFO - Thread-LeaseMaintainer - leaser] Thread-LeaseMaintainer exiting.
[2018-08-06 07:29:27,413 - INFO - Thread-Heartbeater - heartbeater] Thread-Heartbeater exiting.```

**Comment by tseaver** [comment]
This is a clear race condition:  `StreamingPullManager.close` sets `self._consumer = None` (while holding the `self._closing` lock).  However, other methods access `self._consumer` without checking that it could be `None`:

- `StreamingPullManager.maybe_pause_consumer`
- `StreamingPullManager.maybe_resume_consumer`

One method, `StreamingPullManager.is_active`, does check.
