### ISSUE TITLE
datastore: pip install bigquery, datastore fails to install grpc

### ISSUE THREAD

**Issue by evanj** [GoogleCloudPlatform/google-cloud-python#5776]
1. Create a new virtualenv
2. `pip install google-cloud-bigquery google-cloud-datastore`
3. `python -c import google.cloud.datastore`

Produces the following Trackback because grpc is not installed. I believe this is due to a bug in pip: since `google-cloud-bigquery` depends on `google-cloud-core`, it doesn't install `google-cloud-core[grpc]`.  This also happens if these lines are in a `requirements.txt` file. The workaround is to explicitly install google-cloud-core[grpc] before installing google-cloud-bigquery.

It may make sense to add a workaround to `google-cloud-datastore` and any other package that depends on `google-cloud-core[grpc]`. If it did not rely on the extras, this would work. Until pip fixes the bug, more users will run into this.

`pip --version`: pip 18.0
`python --version`: Python 2.7.13

## Traceback

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/evanjones/venv/local/lib/python2.7/site-packages/google/cloud/datastore/__init__.py", line 61, in <module>
    from google.cloud.datastore.batch import Batch
  File "/home/evanjones/venv/local/lib/python2.7/site-packages/google/cloud/datastore/batch.py", line 24, in <module>
    from google.cloud.datastore import helpers
  File "/home/evanjones/venv/local/lib/python2.7/site-packages/google/cloud/datastore/helpers.py", line 29, in <module>
    from google.cloud.datastore_v1.proto import datastore_pb2
  File "/home/evanjones/venv/local/lib/python2.7/site-packages/google/cloud/datastore_v1/__init__.py", line 18, in <module>
    from google.cloud.datastore_v1.gapic import datastore_client
  File "/home/evanjones/venv/local/lib/python2.7/site-packages/google/cloud/datastore_v1/gapic/datastore_client.py", line 18, in <module>
    import google.api_core.gapic_v1.client_info
  File "/home/evanjones/venv/local/lib/python2.7/site-packages/google/api_core/gapic_v1/__init__.py", line 16, in <module>
    from google.api_core.gapic_v1 import config
  File "/home/evanjones/venv/local/lib/python2.7/site-packages/google/api_core/gapic_v1/config.py", line 23, in <module>
    import grpc
ImportError: No module named grpc
```

## Complete console output on a new GCE VM
<details>
<summary>Click to expand</summary>

```
evanjones@ejones-deleteme:~$ virtualenv venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/evanjones/venv/bin/python2
Also creating executable in /home/evanjones/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...venv/done.


evanjones@ejones-deleteme:~$ venv/bin/pip --version
pip 18.0 from /home/evanjones/venv/local/lib/python2.7/site-packages/pip (python 2.7)

evanjones@ejones-deleteme:~$ venv/bin/pip install google-cloud-bigquery google-cloud-datastore
Collecting google-cloud-bigquery
  Downloading https://files.pythonhosted.org/packages/99/b9/fbac0fcbdbf737a44998020c2c090ebbfa37dd89d475ce47a06a5a07418f/google_cloud_bigquery-1.5.0-py2.py3-none-any.whl (77kB)
    100% |████████████████████████████████| 81kB 2.6MB/s 
Collecting google-cloud-datastore
  Downloading https://files.pythonhosted.org/packages/d8/4b/aab0f1578eff1146e019670e079f5f939e46c5b004b65063b450c8d87af0/google_cloud_datastore-1.7.0-py2.py3-none-any.whl (74kB)
    100% |████████████████████████████████| 81kB 4.6MB/s 
Collecting google-cloud-core<0.29dev,>=0.28.0 (from google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/0f/41/ae2418b4003a14cf21c1c46d61d1b044bf02cf0f8f91598af572b9216515/google_cloud_core-0.28.1-py2.py3-none-any.whl
Collecting google-api-core<2.0.0dev,>=1.0.0 (from google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/ab/d0/8393a844c1a4cf9f74908ca1b1a137665519157643e15e112a4a21b71d56/google_api_core-1.3.0-py2.py3-none-any.whl (51kB)
    100% |████████████████████████████████| 61kB 4.8MB/s 
Collecting google-resumable-media>=0.2.1 (from google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/77/95/2e4020a54366423ddba715f89fb7ca456c8f048b15cada6cd6a54cf10e8c/google_resumable_media-0.3.1-py2.py3-none-any.whl
Collecting requests<3.0.0dev,>=2.18.0 (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 4.3MB/s 
Collecting pytz (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 6.5MB/s 
Collecting googleapis-common-protos<2.0dev,>=1.5.3 (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/00/03/d25bed04ec8d930bcfa488ba81a2ecbf7eb36ae3ffd7e8f5be0d036a89c9/googleapis-common-protos-1.5.3.tar.gz
Collecting futures>=3.2.0; python_version < "3.2" (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Collecting protobuf>=3.0.0 (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/27/e7/bf96130ebe633b08a3913da4bb25e50dac5779f1f68e51c99485423f7443/protobuf-3.6.0-cp27-cp27mu-manylinux1_x86_64.whl (7.1MB)
    100% |████████████████████████████████| 7.1MB 3.4MB/s 
Collecting six>=1.10.0 (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=34.0.0 in ./venv/lib/python2.7/site-packages (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery) (40.0.0)
Collecting google-auth<2.0.0dev,>=0.4.0 (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/58/cb/96dbb4e50e7a9d856e89cc9c8e36ab1055f9774f7d85f37e2156c1d79d9f/google_auth-1.5.1-py2.py3-none-any.whl (65kB)
    100% |████████████████████████████████| 71kB 25.6MB/s 
Collecting idna<2.8,>=2.5 (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 24.8MB/s 
Collecting urllib3<1.24,>=1.21.1 (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 37.6MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 31.4MB/s 
Collecting certifi>=2017.4.17 (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
    100% |████████████████████████████████| 153kB 34.2MB/s 
Collecting pyasn1-modules>=0.2.1 (from google-auth<2.0.0dev,>=0.4.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/19/02/fa63f7ba30a0d7b925ca29d034510fc1ffde53264b71b4155022ddf3ab5d/pyasn1_modules-0.2.2-py2.py3-none-any.whl (62kB)
    100% |████████████████████████████████| 71kB 26.7MB/s 
Collecting rsa>=3.1.4 (from google-auth<2.0.0dev,>=0.4.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/e1/ae/baedc9cb175552e95f3395c43055a6a5e125ae4d48a1d7a924baca83e92e/rsa-3.4.2-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 22.0MB/s 
Collecting cachetools>=2.0.0 (from google-auth<2.0.0dev,>=0.4.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/0a/58/cbee863250b31d80f47401d04f34038db6766f95dea1cc909ea099c7e571/cachetools-2.1.0-py2.py3-none-any.whl
Collecting pyasn1<0.5.0,>=0.4.1 (from pyasn1-modules>=0.2.1->google-auth<2.0.0dev,>=0.4.0->google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery)
  Downloading https://files.pythonhosted.org/packages/d1/a1/7790cc85db38daa874f6a2e6308131b9953feb1367f2ae2d1123bb93a9f5/pyasn1-0.4.4-py2.py3-none-any.whl (72kB)
    100% |████████████████████████████████| 81kB 29.1MB/s 
Building wheels for collected packages: googleapis-common-protos
  Running setup.py bdist_wheel for googleapis-common-protos ... done
  Stored in directory: /home/evanjones/.cache/pip/wheels/62/45/af/649bbf07b6595fda010be1bda667cd56d0444d07afc6f8b687
Successfully built googleapis-common-protos
Installing collected packages: idna, urllib3, chardet, certifi, requests, pytz, six, protobuf, googleapis-common-protos, futures, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, google-api-core, google-cloud-core, google-resumable-media, google-cloud-bigquery, google-cloud-datastore
Successfully installed cachetools-2.1.0 certifi-2018.4.16 chardet-3.0.4 futures-3.2.0 google-api-core-1.3.0 google-auth-1.5.1 google-cloud-bigquery-1.5.0 google-cloud-core-0.28.1 google-cloud-datastore-1.7.0 google-resumable-media-0.3.1 googleapis-common-protos-1.5.3 idna-2.7 protobuf-3.6.0 pyasn1-0.4.4 pyasn1-modules-0.2.2 pytz-2018.5 requests-2.19.1 rsa-3.4.2 six-1.11.0 urllib3-1.23


evanjones@ejones-deleteme:~$ venv/bin/pip list 
Package                  Version  
------------------------ ---------
cachetools               2.1.0    
certifi                  2018.4.16
chardet                  3.0.4    
futures                  3.2.0    
google-api-core          1.3.0    
google-auth              1.5.1    
google-cloud-bigquery    1.5.0    
google-cloud-core        0.28.1   
google-cloud-datastore   1.7.0    
google-resumable-media   0.3.1    
googleapis-common-protos 1.5.3    
idna                     2.7      
pip                      18.0     
pkg-resources            0.0.0    
protobuf                 3.6.0    
pyasn1                   0.4.4    
pyasn1-modules           0.2.2    
pytz                     2018.5   
requests                 2.19.1   
rsa                      3.4.2    
setuptools               40.0.0   
six                      1.11.0   
urllib3                  1.23     
wheel                    0.31.1   

evanjones@ejones-deleteme:~$ venv/bin/python -c 'import google.cloud.datastore'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/evanjones/venv/local/lib/python2.7/site-packages/google/cloud/datastore/__init__.py", line 61, in <module>
    from google.cloud.datastore.batch import Batch
  File "/home/evanjones/venv/local/lib/python2.7/site-packages/google/cloud/datastore/batch.py", line 24, in <module>
    from google.cloud.datastore import helpers
  File "/home/evanjones/venv/local/lib/python2.7/site-packages/google/cloud/datastore/helpers.py", line 29, in <module>
    from google.cloud.datastore_v1.proto import datastore_pb2
  File "/home/evanjones/venv/local/lib/python2.7/site-packages/google/cloud/datastore_v1/__init__.py", line 18, in <module>
    from google.cloud.datastore_v1.gapic import datastore_client
  File "/home/evanjones/venv/local/lib/python2.7/site-packages/google/cloud/datastore_v1/gapic/datastore_client.py", line 18, in <module>
    import google.api_core.gapic_v1.client_info
  File "/home/evanjones/venv/local/lib/python2.7/site-packages/google/api_core/gapic_v1/__init__.py", line 16, in <module>
    from google.api_core.gapic_v1 import config
  File "/home/evanjones/venv/local/lib/python2.7/site-packages/google/api_core/gapic_v1/config.py", line 23, in <module>
    import grpc
ImportError: No module named grpc
```
</details>

**Comment by evanj** [comment]
I think this is caused by https://github.com/pypa/pip/issues/4957. This is the same issue that caused https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5023.

**Comment by tseaver** [comment]
@evanj Thanks for the report!  I concur that this issue is due to the `pip` issue you linked.

@theacodes The only workaround I can think of would be to add specific `grcpio` pins to `datastore/setup.py` (and other APIs which use `gprc`), which seems pretty ugly.

**Comment by tseaver** [comment]
@theacodes I'm closing this issue, because duplicating the `grpc` pins everywhere creates roach motels.  The workaround is to include `grpcio` explicitly in the application's `requirements.txt`
