### ISSUE TITLE
Pubsub: Publish hangs on futures.wait intermittently

### ISSUE THREAD

**Issue by nirmalthacker** [GoogleCloudPlatform/google-cloud-python#5807]
Our publish frequently hangs on the future.wait().

Application details:
1. A poller thread subscribes to a topic fetching messages as they come in
2. When messages come in, worker multiprocess is started to do some work
3. When work is done, worker multiprocess publish to a different topic

3 hangs in the publish future.wait() intermittently with the below stack trace. Following the stack trace are details of our runtime. What other details can I provide? This is a pretty severe issue for us having decided to upgrade the pubsub library

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "<snipped>", line 32, in mainloop
    worker.publish_to_topic()
  File "<snipped>", line 505, in publish_to_topic
    if future.exception():
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/pubsub_v1/futures.py", line 133, in exception
    if not self._completed.wait(timeout=timeout):
  File "/usr/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()

```
OS details: Ubuntu 16.04

Python details: Python 3.5.2

pip freeze | grep google:
google-api-core==1.3.0
google-auth==1.5.1
google-cloud==0.34.0
google-cloud-bigquery==0.26.0
google-cloud-bigtable==0.26.0
google-cloud-core==0.26.0
google-cloud-datastore==1.2.0
google-cloud-dns==0.26.0
google-cloud-error-reporting==0.26.0
google-cloud-language==0.27.0
google-cloud-logging==1.2.0
google-cloud-monitoring==0.26.0
google-cloud-pubsub==0.37.0
google-cloud-resource-manager==0.26.0
google-cloud-runtimeconfig==0.26.0
google-cloud-spanner==0.26.0
google-cloud-speech==0.28.0
google-cloud-storage==1.3.2
google-cloud-translate==1.1.0
google-cloud-videointelligence==0.25.0
google-cloud-vision==0.26.0
google-gax==0.15.16
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3
grpc-google-iam-v1==0.11.4

**Comment by theacodes** [comment]
Are you creating a new client in each new process? Multiprocessing can
cause serious issues with the gRPC clients.

**Comment by nirmalthacker** [comment]
@theacodes Yes, a new client per process.

**Comment by nirmalthacker** [comment]
I've resorted to using the REST API for step 3 for the publish and it seems to be a decent workaround. Is the issue concerning multiprocessing and grpc a bug? Can you link it in here? Would we see a fix in the later releases?
