### ISSUE TITLE
./google-cloud-sdk/install.sh error

### ISSUE THREAD

**Issue by jens86** [GoogleCloudPlatform/google-cloud-python#5833]
Trying to install the google cloud sdk locally. Using Mac 64 bit. just installed python 2.7.15.

c02s10gwg8wp:~ szb7493$ /Applications/google-cloud-sdk/install.sh
Welcome to the Google Cloud SDK!
Traceback (most recent call last):
  File "/Applications/google-cloud-sdk/bin/bootstrapping/install.py", line 12, in <module>
    import bootstrapping
  File "/Applications/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 32, in <module>
    import setup  # pylint:disable=g-import-not-at-top
  File "/Applications/google-cloud-sdk/bin/bootstrapping/setup.py", line 66, in <module>
    DoAllRequiredChecks()
  File "/Applications/google-cloud-sdk/bin/bootstrapping/setup.py", line 62, in DoAllRequiredChecks
    properties.VALUES.core.allow_py3.GetBool()):
  File "/Applications/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1740, in GetBool
    value = _GetBoolProperty(self, named_configs.ActivePropertiesFile.Load(),
  File "/Applications/google-cloud-sdk/lib/googlecloudsdk/core/configurations/named_configs.py", line 400, in Load
    force_create=False).file_path])
  File "/Applications/google-cloud-sdk/lib/googlecloudsdk/core/configurations/named_configs.py", line 439, in _ActiveConfig
    config_name = _EffectiveActiveConfigName()
  File "/Applications/google-cloud-sdk/lib/googlecloudsdk/core/configurations/named_configs.py", line 464, in _EffectiveActiveConfigName
    config_name = _ActiveConfigNameFromFile()
  File "/Applications/google-cloud-sdk/lib/googlecloudsdk/core/configurations/named_configs.py", line 504, in _ActiveConfigNameFromFile
    .format(path, config.Paths().named_config_directory), exc)
googlecloudsdk.core.configurations.named_configs.NamedConfigFileAccessError: Active configuration name could not be read from: [/Users/szb7493/.config/gcloud/active_config]. Ensure you have sufficient read permissions on required active configuration in [/Users/szb7493/.config/gcloud/configurations].
  Unable to read file [/Users/szb7493/.config/gcloud/active_config]: [Errno 13] Permission denied: '/Users/szb7493/.config/gcloud/active_config'
c02s10gwg8wp:~ szb7493$ 

Any clues on what this means and how to fix it?

**Comment by tseaver** [comment]
@jens86 I'm sorry you are having trouble installing the Cloud SDK.  Unfortunately, this repository is not where that SDK is maintained / supported.  Please use one of the resources on the [SDK support page](https://cloud.google.com/sdk/docs/getting-support).
