### ISSUE TITLE
firebase-admin - `from firebase-admin import storage` fails

### ISSUE THREAD

**Issue by brianmhunt** [GoogleCloudPlatform/google-cloud-python#5850]
Was unable to find another accounting of this, so reporting here with relevant details.

The problem should be fairly self-explanatory from the below, but I'm happy to provide any more details that might be of assistance.

This also fails with e.g. `from firebase-admin import firestore`, and I suspect others.

### Setup:

```
$ virtualenv env
Using base prefix '/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7'
New python executable in /Users/bmh/tmp/env/bin/python3.7
Also creating executable in /Users/bmh/tmp/env/bin/python
Installing setuptools, pip, wheel...done.

$ env/bin/pip install firebase-admin google-cloud-storage
Collecting firebase_admin
  Using cached https://files.pythonhosted.org/packages/42/ce/973d0dfe29637556c9714749e5a753360414b939840733d50d4918fae20f/firebase_admin-2.13.0-py2.py3-none-any.whl
Collecting google-cloud-storage
  Using cached https://files.pythonhosted.org/packages/d4/1a/8238dda1547b9b6156f4cfc7923558bb67d6c608a28d677d0dc070babd31/google_cloud_storage-1.10.0-py2.py3-none-any.whl
Collecting six>=1.6.1 (from firebase_admin)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting requests>=2.13.0 (from firebase_admin)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting cachecontrol>=0.12.4 (from firebase_admin)
Collecting google-auth>=1.3.0 (from firebase_admin)
  Using cached https://files.pythonhosted.org/packages/58/cb/96dbb4e50e7a9d856e89cc9c8e36ab1055f9774f7d85f37e2156c1d79d9f/google_auth-1.5.1-py2.py3-none-any.whl
Collecting google-cloud-firestore>=0.27.0 (from firebase_admin)
  Using cached https://files.pythonhosted.org/packages/47/97/e0ad4b86ae49ec43f74480a3337952010a08260ed0218d1075b5b0e6f37f/google_cloud_firestore-0.29.0-py2.py3-none-any.whl
Collecting google-resumable-media>=0.3.1 (from google-cloud-storage)
  Using cached https://files.pythonhosted.org/packages/77/95/2e4020a54366423ddba715f89fb7ca456c8f048b15cada6cd6a54cf10e8c/google_resumable_media-0.3.1-py2.py3-none-any.whl
Collecting google-api-core<2.0.0dev,>=0.1.1 (from google-cloud-storage)
  Using cached https://files.pythonhosted.org/packages/ab/d0/8393a844c1a4cf9f74908ca1b1a137665519157643e15e112a4a21b71d56/google_api_core-1.3.0-py2.py3-none-any.whl
Collecting google-cloud-core<0.29dev,>=0.28.0 (from google-cloud-storage)
  Using cached https://files.pythonhosted.org/packages/0f/41/ae2418b4003a14cf21c1c46d61d1b044bf02cf0f8f91598af572b9216515/google_cloud_core-0.28.1-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests>=2.13.0->firebase_admin)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests>=2.13.0->firebase_admin)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.13.0->firebase_admin)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.13.0->firebase_admin)
  Using cached https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl
Collecting msgpack (from cachecontrol>=0.12.4->firebase_admin)
Collecting pyasn1-modules>=0.2.1 (from google-auth>=1.3.0->firebase_admin)
  Using cached https://files.pythonhosted.org/packages/19/02/fa63f7ba30a0d7b925ca29d034510fc1ffde53264b71b4155022ddf3ab5d/pyasn1_modules-0.2.2-py2.py3-none-any.whl
Collecting cachetools>=2.0.0 (from google-auth>=1.3.0->firebase_admin)
  Using cached https://files.pythonhosted.org/packages/0a/58/cbee863250b31d80f47401d04f34038db6766f95dea1cc909ea099c7e571/cachetools-2.1.0-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from google-auth>=1.3.0->firebase_admin)
  Using cached https://files.pythonhosted.org/packages/e1/ae/baedc9cb175552e95f3395c43055a6a5e125ae4d48a1d7a924baca83e92e/rsa-3.4.2-py2.py3-none-any.whl
Collecting pytz (from google-api-core<2.0.0dev,>=0.1.1->google-cloud-storage)
  Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
Collecting googleapis-common-protos<2.0dev,>=1.5.3 (from google-api-core<2.0.0dev,>=0.1.1->google-cloud-storage)
Requirement already satisfied: setuptools>=34.0.0 in ./env/lib/python3.7/site-packages (from google-api-core<2.0.0dev,>=0.1.1->google-cloud-storage) (40.2.0)
Collecting protobuf>=3.0.0 (from google-api-core<2.0.0dev,>=0.1.1->google-cloud-storage)
  Using cached https://files.pythonhosted.org/packages/77/78/a7f1ce761e2c738e209857175cd4f90a8562d1bde32868a8cd5290d58926/protobuf-3.6.1-py2.py3-none-any.whl
Collecting pyasn1<0.5.0,>=0.4.1 (from pyasn1-modules>=0.2.1->google-auth>=1.3.0->firebase_admin)
  Using cached https://files.pythonhosted.org/packages/d1/a1/7790cc85db38daa874f6a2e6308131b9953feb1367f2ae2d1123bb93a9f5/pyasn1-0.4.4-py2.py3-none-any.whl
Installing collected packages: six, urllib3, idna, chardet, certifi, requests, google-resumable-media, pytz, pyasn1, pyasn1-modules, cachetools, rsa, google-auth, protobuf, googleapis-common-protos, google-api-core, google-cloud-core, google-cloud-storage, msgpack, cachecontrol, google-cloud-firestore, firebase-admin
Successfully installed cachecontrol-0.12.5 cachetools-2.1.0 certifi-2018.8.24 chardet-3.0.4 firebase-admin-2.13.0 google-api-core-1.3.0 google-auth-1.5.1 google-cloud-core-0.28.1 google-cloud-firestore-0.29.0 google-cloud-storage-1.10.0 google-resumable-media-0.3.1 googleapis-common-protos-1.5.3 idna-2.7 msgpack-0.5.6 protobuf-3.6.1 pyasn1-0.4.4 pyasn1-modules-0.2.2 pytz-2018.5 requests-2.19.1 rsa-3.4.2 six-1.11.0 urllib3-1.23
```

### Reproduction

```
$ env/bin/python -c 'from firebase_admin import storage'
Traceback (most recent call last):
  File "/Users/bmh/tmp/env/lib/python3.7/site-packages/firebase_admin/storage.py", line 23, in <module>
    from google.cloud import storage
  File "/Users/bmh/tmp/env/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 37, in <module>
    from google.cloud.storage.batch import Batch
  File "/Users/bmh/tmp/env/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 30, in <module>
    from google.cloud import exceptions
  File "/Users/bmh/tmp/env/lib/python3.7/site-packages/google/cloud/exceptions.py", line 24, in <module>
    from google.api_core import exceptions
ModuleNotFoundError: No module named 'google.api_core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/bmh/tmp/env/lib/python3.7/site-packages/firebase_admin/storage.py", line 25, in <module>
    raise ImportError('Failed to import the Cloud Storage library for Python. Make sure '
ImportError: Failed to import the Cloud Storage library for Python. Make sure to install the "google-cloud-storage" module.
```

### Background Info

```
$ env/bin/python --version
Python 3.7.0

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

$ env/bin/pip list
Package                  Version
------------------------ ---------
CacheControl             0.12.5
cachetools               2.1.0
certifi                  2018.8.24
chardet                  3.0.4
firebase-admin           2.13.0
google-api-core          1.3.0
google-auth              1.5.1
google-cloud-core        0.28.1
google-cloud-firestore   0.29.0
google-cloud-storage     1.10.0
google-resumable-media   0.3.1
googleapis-common-protos 1.5.3
idna                     2.7
msgpack                  0.5.6
pip                      18.0
protobuf                 3.6.1
pyasn1                   0.4.4
pyasn1-modules           0.2.2
pytz                     2018.5
requests                 2.19.1
rsa                      3.4.2
setuptools               40.2.0
six                      1.11.0
urllib3                  1.23
wheel                    0.31.1

$ env/bin/pip show firebase-admin
Name: firebase-admin
Version: 2.13.0
Summary: Firebase Admin Python SDK
Home-page: https://firebase.google.com/docs/admin/setup/
Author: Firebase
Author-email: UNKNOWN
License: Apache License 2.0
Location: /Users/bmh/tmp/env/lib/python3.7/site-packages
Requires: google-auth, six, google-cloud-storage, google-cloud-firestore, cachecontrol, requests
Required-by:

$ env/bin/pip show google-cloud-storage
Name: google-cloud-storage
Version: 1.10.0
Summary: Google Cloud Storage API client library
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Users/bmh/tmp/env/lib/python3.7/site-packages
Requires: google-api-core, google-cloud-core, google-resumable-media
Required-by: firebase-admin
```

**Comment by hiranya911** [comment]
Works fine on my Mac:

```
$ ./env/bin/python -c 'from firebase_admin import storage; print(storage.__name__)'
firebase_admin.storage
```

**Comment by brianmhunt** [comment]
Thanks @hiranya911 ; I'd need some info to do a differential here.  What's the output from the above commands?

**Comment by tseaver** [comment]
@brianmhunt Sorry you are having trouble with the Firebase SDK.  However, this repository is not its home: please use one of the [Firebase support resources](https://firebase.google.com/support/) to ask for help.

**Comment by brianmhunt** [comment]
Thanks for the redirect, @tseaver

**Comment by hiranya911** [comment]
I think this is the right place for this issue. `firebase-admin` doesn't have its own storage implementation. It just uses `google-cloud-storage` underneath. @brianmhunt see if you can run `from google.cloud import storage` in your environment.

**Comment by brianmhunt** [comment]
Thanks @hiranya911 

Here's the output:

```
>>> from google.cloud import storage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bmh/tmp/x/env/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 37, in <module>
    from google.cloud.storage.batch import Batch
  File "/Users/bmh/tmp/x/env/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
  File "/Users/bmh/tmp/x/env/lib/python3.7/site-packages/google/cloud/_helpers.py", line 31, in <module>
    import google.auth
ModuleNotFoundError: No module named 'google.auth'
```

It looks like it's installed though:

```
$ env/bin/pip install google-auth
Requirement already satisfied: google-auth in ./env/lib/python3.7/site-packages (1.5.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./env/lib/python3.7/site-packages (from google-auth) (0.2.2)
Requirement already satisfied: cachetools>=2.0.0 in ./env/lib/python3.7/site-packages (from google-auth) (2.1.0)
Requirement already satisfied: rsa>=3.1.4 in ./env/lib/python3.7/site-packages (from google-auth) (3.4.2)
Requirement already satisfied: six>=1.9.0 in ./env/lib/python3.7/site-packages (from google-auth) (1.11.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.1 in ./env/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth) (0.4.4)
```

However when I run this I get:

```
>>> import google.auth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.auth'
```

I believe I've discovered the problem:

```
>>> import google
>>> google.__path__
['/Users/bmh/google-cloud-sdk/platform/google_appengine/google']
```

Which is outside the virtualenv.  I'm not sure why it'd being preferred over the virtualenv; perhaps  because my `PYTHONPATH=/Users/bmh/google-cloud-sdk/platform/google_appengine/`?

Looking into it.

**Comment by brianmhunt** [comment]
⭐️  When I clear the `PYTHONPATH` this issue resolves.

So it would appear that there's some conflict between the Google Cloud SDK and virtualenv.

I believe I've posted enough details that this can be sorted or otherwise documented, but please don't hesitate to reach out for more details that might be of assistance.
