### ISSUE TITLE
google-cloud-bigtable 0.30.0 doesn't work with non-admin context

### ISSUE THREAD

**Issue by andyhky** [GoogleCloudPlatform/google-cloud-python#5874]
We are seeing an issue with the newly release google-cloud-bigtable (0.30.0):

Python version:
```
$ pipenv run python --version
Python 2.7.12
```

Package version:
```
        "google-cloud-bigtable": {
            "hashes": [
                "sha256:0b82e3c77db6ac89f9111551042146fc1d829fb67f77c809bb8465923ef0455b",
                "sha256:bd39cabfd6e816646940a10e1576d59f2e4f272b3ba0c5e040c834b949a9ba4f"
            ],
            "index": "pypi",
            "version": "==0.30.0"
        },
```

A simple repro script:

```
#!/usr/bin/env python

import sys

from google.cloud import bigtable

proj, inst, tbl = sys.argv[1:]

thandle = bigtable.Client(project=proj, admin=False).instance(inst).table(tbl)
row = thandle.read_row('some_arbitrary_key')(venv)
```

With 0.30.0, this fails:

```
$ pipenv run python ./repro.py <project> <instance> <table>
/Users/andy/.local/share/virtualenvs/btscene-9KYRlr-O/lib/python2.7/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
Traceback (most recent call last):
  File "./repro.py", line 10, in <module>
    row = thandle.read_row('some_arbitrary_key')
  File "/Users/andy/.local/share/virtualenvs/btscene-9KYRlr-O/lib/python2.7/site-packages/google/cloud/bigtable/table.py", line 292, in read_row
    self.name, row_key=row_key, filter_=filter_,
  File "/Users/andy/.local/share/virtualenvs/btscene-9KYRlr-O/lib/python2.7/site-packages/google/cloud/bigtable/table.py", line 125, in name
    table_client = self._instance._client.table_admin_client
  File "/Users/andy/.local/share/virtualenvs/btscene-9KYRlr-O/lib/python2.7/site-packages/google/cloud/bigtable/client.py", line 179, in table_admin_client
    raise ValueError('Client is not an admin client.')
ValueError: Client is not an admin client.
```

After downgrading to 0.29.0, we receive the expected output:

```
$ pipenv run python ./repro.py <project> <instance> <table>
/Users/andy/.local/share/virtualenvs/btscene-9KYRlr-O/lib/python2.7/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
```
(there was no row with that key on our table)

**Comment by tseaver** [comment]
@andyhky Thanks for the report!  I can reproduce, and am working on a fix right now.
