### ISSUE TITLE
`/` is not welcome to `export_output` (gcloud.ml-engine.local.predict) Expected ) in projection expression [table(class_id *HERE* /name_tree1

### ISSUE THREAD

**Issue by ricoms** [GoogleCloudPlatform/google-cloud-python#5991]
Hi,

Is this the correct place for submitting a bug like this?
https://stackoverflow.com/questions/52339759/error-gcloud-ml-engine-local-predict-expected-in-projection-expression-tab

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
    ML Engine
2. OS type and version
    Ubuntu 16.04
3. Python version and virtual environment information `python --version`
    Python 3.5.2
4. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
    Google Cloud SDK 216.0.0
    alpha 2018.09.07
    app-engine-python 1.9.75
    app-engine-python-extras 1.9.75
    beta 2018.09.07
    bq 2.0.34
    core 2018.09.07
    gsutil 4.33
    kubectl 2018.09.07

5. Stacktrace if available
```
DEBUG: (gcloud.ml-engine.local.predict) Expected ) in projection expression [table(
                  class_id *HERE* /name_tree1, class_id/name_tree2, class_id/name_tree3, class_id/name_tree4, class_id/name_tree5, class_str/name_tree1, class_str/name_tree2, class_str/name_tree3,class_str/name_tree4, class_str/name_tree5, probabilities/name_tree1, probabilities/name_tree2, probabilities/name_tree3, probabilities/name_tree4, probabilities/name_tree5
              )].
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 839, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 772, in Run
    display_info=self.ai.display_info).Display()
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/display.py", line 450, in Display
    self._InitPrinter()
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/display.py", line 424, in _InitPrinter
    self._format, defaults=self._defaults, out=log.out)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_printer.py", line 221, in Printer
    console_attr=console_attr)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/resource/table_printer.py", line 185, in __init__
    defaults=defaults)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_printer_base.py", line 264, in Printer
    return self._printer(*args, **kwargs)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_printer.py", line 203, in Printer
    defaults=defaults, symbols=resource_transform.GetTransforms()))
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_projector.py", line 525, in Compile
    expression, defaults=defaults, symbols=symbols, compiler=Compile)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_projection_parser.py", line 524, in Parse
    compiler=compiler).Parse(expression)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_projection_parser.py", line 486, in Parse
    self._ParseKeys()
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_projection_parser.py", line 429, in _ParseKeys
    self._lex.Annotate()))
ExpressionSyntaxError: Expected ) in projection expression [table(
                  class_id *HERE* /name_tree1, class_id/name_tree2, class_id/name_tree3, class_id/name_tree4, class_id/name_tree5, class_str/name_tree1, class_str/name_tree2, class_str/name_tree3,class_str/name_tree4, class_str/name_tree5, probabilities/name_tree1, probabilities/name_tree2, probabilities/name_tree3, probabilities/name_tree4, probabilities/name_tree5
              )].
ERROR: (gcloud.ml-engine.local.predict) Expected ) in projection expression [table(
                  class_id *HERE* /name_tree1, class_id/name_tree2, class_id/name_tree3, class_id/name_tree4, class_id/name_tree5, class_str/name_tree1, class_str/name_tree2, class_str/name_tree3,class_str/name_tree4, class_str/name_tree5, probabilities/name_tree1, probabilities/name_tree2, probabilities/name_tree3, probabilities/name_tree4, probabilities/name_tree5
              )].
Makefile:135: recipe for target 'test-predict' failed
```
6. Steps to reproduce
    explained here: https://stackoverflow.com/questions/52339759/error-gcloud-ml-engine-local-predict-expected-in-projection-expression-tab
7. Code example
```
def model_fn(features, labels, mode, params):
    global LIST_OF_LABELS
    global LEN_OF_LABELS
    get_model_fn = MODEL_FCS.get(params['model_name'])

    if get_model_fn is not None:
        if not LIST_OF_LABELS:
            with open(os.path.join(os.path.split(params['train_data_path'])[0], 'data.json')) as flabel:
                classes_dump = json.load(flabel)
            LIST_OF_LABELS = {'name_tree{}'.format(i): classes_dump['name_tree{}'.format(i)] for i in range(1,6)}
        if not LEN_OF_LABELS:
            LEN_OF_LABELS = {k: len(it) for k, it in LIST_OF_LABELS.items()}

        if isinstance(features, dict):
            features = features["image"]
        tf.logging.info('Features sizing ... features={}'.format(features.get_shape()))
        base_model = get_model_fn(
            weights=None,
            include_top=False,
            input_tensor=features,
            pooling='max'
        )
        tf.logging.info('Loaded {} model'.format(params['model_name']))
        
        feature_map = base_model.output
        tf.logging.info(feature_map)
        feature_map = tf.keras.layers.Dense(
            params['latent_size'],
            activation='sigmoid',
            kernel_initializer='glorot_uniform',
            name='latent'+str(params['latent_size'])
        )(feature_map)
        feature_map = tf.keras.layers.Dropout(0.25)(feature_map)
        tf.logging.info('Latent layer sizing ... latent_size={}'.format(feature_map.get_shape()))

        logits = []
        predictions = {}
        def get_key(a1, a2):
            return '%s_%s' % (a1, a2)
        for head_name, it in sorted(LIST_OF_LABELS.items()):
            _logit = tf.layers.batch_normalization(
                tf.keras.layers.Dense(
                    units=len(it),
                    activation=None,
                    kernel_initializer='glorot_uniform',
                    name='fc_'+head_name)(feature_map),
                training=(mode == tf.estimator.ModeKeys.TRAIN)
            )
            logits.append(_logit)
            prob_key = get_key("probabilities", head_name)
            id_key = get_key("class_id", head_name)
            str_key = get_key("class_str", head_name)
            predictions[prob_key] = tf.nn.softmax(_logit, name="softmax_tensor_"+head_name)
            # tf.logging.info('predictions[prob_key]={}'.format(predictions[prob_key].get_shape()))
            predictions[id_key] = tf.cast(tf.argmax(predictions[prob_key], 1), tf.int32)
            predictions[str_key] = tf.gather(LIST_OF_LABELS[head_name], tf.cast(predictions[id_key], tf.int32))
         
        if mode == tf.estimator.ModeKeys.TRAIN or mode == tf.estimator.ModeKeys.EVAL:
            evalmetrics, accuracy = {}, {}
            for i, (head_name, it) in enumerate(sorted(LIST_OF_LABELS.items())):
                accuracy[head_name] = tf.metrics.accuracy(predictions[get_key("class_id", head_name)], labels[head_name])
                evalmetrics['accuracy/'+head_name] =  accuracy[head_name]
                tf.summary.scalar('accuracy/'+head_name, accuracy[head_name][1])
            predictions = None
            export_outputs = None
            loss = 0
            for i, logit in enumerate(logits):
                k = CLASS_NAMES[i]
                loss_i = tf.losses.softmax_cross_entropy(
                    onehot_labels=tf.one_hot(labels[k], LEN_OF_LABELS[k]),
                    label_smoothing=0.1,
                    logits=logit
                )
                loss += loss_i
                tf.summary.scalar('loss/name_tree{}'.format(i+1), loss_i)
            if mode == tf.estimator.ModeKeys.TRAIN:
                def rate_decay(learning_rate, global_step):
                    return tf.train.exponential_decay(learning_rate, global_step,
                        decay_steps=131000, decay_rate=0.94)
                update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
                train_op_fn = tf.contrib.layers.optimize_loss(
                    loss, 
                    tf.train.get_global_step(),
                    learning_rate=params['learning_rate'],
                    optimizer="Adam",
                    update_ops=update_ops,
                    learning_rate_decay_fn=rate_decay
                )
            else:
                train_op_fn = None
        else:
            loss = None
            train_op_fn = None
            evalmetrics = None
            export_outputs = {_DEFAULT_SERVING_KEY:
                tf.estimator.export.PredictOutput(predictions)}

        for var in tf.trainable_variables():
            tf.summary.histogram(var.name.replace(':', '_'), var)
        return tf.estimator.EstimatorSpec(
            mode=mode,
            predictions=predictions,
            loss=loss,
            train_op=train_op_fn,
            eval_metric_ops=evalmetrics,
            export_outputs=export_outputs
        )
    else:
        raise Exception('The model input must be one of this options: %s' % MODEL_FCS)
```

**Comment by tseaver** [comment]
I am sorry you are having troubles with the Cloud SDK.  However, this repository is not the right place to report issues with it (we maintain the `google-cloud-*` API client libraries for Python here).

Please see the [Cloud SDK Getting Support page](https://cloud.google.com/sdk/docs/getting-support).
